### ISSUE TITLE
Add documentation for how dihedral angle is determined

### ISSUE THREAD

**Issue by Charlottez112** [glotzerlab/hoomd-blue#1027]
## Description and proposed solution

When @danevans09 and I were writing tests for the dihedral potential, we found the diagram showing how dihedral angle is determined in the doc is not clear enough. More specifically, we think it would be helpful if it can include some angles between 0 deg and 180 deg

**Comment by joaander** [comment]
I'm going to close this one as it will be covered in #1078. It's not really a duplicate, but a subset.
