### ISSUE TITLE
Check all C++ asserts triggered by pytests

### ISSUE THREAD

**Issue by j-proc** [glotzerlab/hoomd-blue#1029]
## Description

Run `python -m pytest hoomd` with a Debug build and fix failing asserts. 

## Motivation and context

I was running test with a Debug compiled build and found that [this assert](https://github.com/glotzerlab/hoomd-blue/blob/a7585d01293166cd86665de63ee75c0f22138877/hoomd/md/NeighborList.cc#L1489) fails for `test_write_gsd_dynamic`. I'm not clear on if it's a bad assert or another issue, but I thought we should sort it and any other failing asserts out before v3 is finalized. We can also consider if these calls point out important edge cases that are missed by our ctests.

**Comment by j-proc** [comment]
I just checked and that is the only one triggered with just the md module.

**Comment by joaander** [comment]
Debug builds run extremely slow, so unfortunately this is not something we can add to the CI tests.

I'll look into this assert.
