### ISSUE TITLE
Remove r_on for potentials that do not support "xplor" mode

### ISSUE THREAD

**Issue by b-butler** [glotzerlab/hoomd-blue#1047]
## Description
Many potentials do not support the "xplor" energy/force shifting, but allow setting `default_r_on` and `obj.r_on[(type, type)]`. This does not make much sense as they can never be meaningfully set. I think removing the typeparameter and constructor argument would be best.

## Motivation and context
I believe this would increase the API coherence.

**Comment by joaander** [comment]
We document that `r_on` exists in the base class: https://hoomd-blue.readthedocs.io/en/latest/module-md-pair.html#hoomd.md.pair.Pair.r_on . Users could reasonably expect that all base class properties are available in sub classes. How would you clarify this?

**Comment by b-butler** [comment]
We could approach this in a few ways:

1. Make `mode` immutable. `r_on` only exists if `mode="xplor"` otherwise it would not be an attribute.
2. Document clearly that `r_on` is an optional type parameter that only exist for `Pair` subclasses that have the `"xplor"` mode.
3. Just remove the constructor argument and keep the type parameter for consistency.

**Comment by joaander** [comment]
We could add a property `r_on` documentation to those classes that don't support `"xplor"` and note there that it does not exist. That clarifies it closer to where the user makes use of the method.

**Comment by joaander** [comment]
#1138 will have a similar issue for LJ potentials and a tail correction parameter.

In this case, I think it makes the most sense to only add the parameter to the classes that actually have it. In the tail correction case, that will be only 1 (initially).

**Comment by joaander** [comment]
Once #1189 is merged and SLJ is removed, these are the remaining potentials that lack one or more shifting modes:
* DPD
* DPDConservative
* DPDLJ
* Table
* Ewald
* ForceShiftedLJ

Technically, only the DPD and DPDLJ potentials completely lack support for smoothing. DPD and DPD have a built in shift, so the shift mode is redundant. Users should apply any shift or smoothing directly in their table potentials. Ewald is meant to be used without a shift as it works with the long range PPPM solver, and ForceShiftedLJ implements its own type of shift different from `mode='shift'` and `mode='xplor'`.
