### ISSUE TITLE
Table writer throws a confusing error when logging pressure

### ISSUE THREAD

**Issue by SamSavitz** [glotzerlab/hoomd-blue#1048]
## Description

`hoomd.write.Table` doesn't set `pDataFlags[pdata_flag::pressure_tensor]` to `1` when logging `ThermodynamicQuantities.pressure` like `hoomd.write.GSD` does.

## Output

```python
Traceback (most recent call last):
  File "SIBCI.py", line 417, in <module>
    run(100)
  File "SIBCI.py", line 403, in run
    sim.run(s, write_at_start=was)
  File "/home/ssavitz/miniconda3/lib/python3.8/site-packages/hoomd/simulation.py", line 393, in run
    self._cpp_sys.run(steps_int, write_at_start)
  File "/home/ssavitz/miniconda3/lib/python3.8/site-packages/hoomd/write/table.py", line 285, in act
    self._write_row(output_dict)
  File "/home/ssavitz/miniconda3/lib/python3.8/site-packages/hoomd/write/table.py", line 264, in _write_row
    self.delimiter.join(
  File "/home/ssavitz/miniconda3/lib/python3.8/site-packages/hoomd/write/table.py", line 265, in <genexpr>
    (self._fmt(data[k], headers[k]) for k in headers)))
  File "/home/ssavitz/miniconda3/lib/python3.8/site-packages/hoomd/write/table.py", line 97, in __call__
    return self.format_num(value, column_width)
  File "/home/ssavitz/miniconda3/lib/python3.8/site-packages/hoomd/write/table.py", line 112, in format_num
    min_len_repr = int(log10(max(abs(value), 1))) + 1
ValueError: cannot convert float NaN to integer
```

If a `hoomd.write.GSD` happens to output the pressure on that frame, or `hoomd.Simulation.always_compute_pressure` is set, then it can work.

## Passible resolutions

- `hoomd.write.Table` should include logic like `hoomd.write.GSD`. (I'd add it myself, if I could easily find the segment of code where this is handled in the `GSD` module.)  This is the most reasonable solution in my opinion.
- Some `string` value like `"nan"` should be printed in the table.
- A warning should be printed when creating a `hoomd.write.Table` with a `hoomd.logging.Logger` which includes `ThermodynamicQuantities.pressure`.

## My workaround

My solution was

1. To write a simple function:
```python
def pressure():
    p = thermo.pressure

    if isnan(p):
        return "nan"
    else:
        return str(p)
```
2. Add it to the Table Logger with:
```python
tableLogger[ ("pressure") ] = (pressure, "string")
```
3. And add an additional `GSD` writer which just saves the pressure with a period that is quadruple that of table and a filename of `"/tmp/pressure.gsd"`.

Thus, in the table, I get three `nan`s per valid scalar, which I figure is good for efficiency.

### A further extension

I also added six analogous functions `Pxx`, `Pyy`, . . ., `Pyz`, which do a similar thing for `ThermodynamicQuantities.pressure_tensor`, which would otherwise be in the `hoomd.logging.Logger` category `sequence`, and hence impossible to logged in a table.  These should perhaps be combined into the `strings` category, but then `hoomd.write.Table` would have to support `strings`.

## Configuration

Versions:
- **HOOMD-blue** `v3.0.0-beta.7`
  -  (The rest is probably irrelevant)
- Python version: 3.8.5

Platform:
- Linux

Installation method:
- Compiled from source in a `Conda` `venv`

**Comment by b-butler** [comment]
Hey, @SamSavitz thanks for the bug report. `GSD` doesn't have this problem because if its `log` attribute is set then it sets all flags including for pressure. We can do this too for the `Table` logger backend. For how to request flags see the documentation for `hoomd.custom.Action` https://hoomd-blue.readthedocs.io/en/latest/module-hoomd-custom.html#hoomd.custom.Action, and set the flags accordingly.

This change will slow down HOOMD on all logging frames making logging more costly overall, but since logging pressure is likely to be a common use-case for the `Table` logging backend, but is likely worth it. We can also add a function that would explicitly tell the `Table` logger that pressure is not needed.

**Comment by joaander** [comment]
@SamSavitz we accept pull requests from the community if you would like to help solve this issue for all users. I suggest modifying the `Table` writer to always set the appropriate flag.

**Comment by SamSavitz** [comment]
This fix I think I'll leave up to experts, as there seem to a few options for how to remedy it, with varying efficiency and elegance.

I will be submitting an `LPGaussian` pair potential in the next few weeks as [we discussed](https://groups.google.com/g/hoomd-users/c/MogpUIAembY) on the mailing lists, however.
