### ISSUE TITLE
Compatibility of HOOMD with the newest ROCm

### ISSUE THREAD

**Issue by niktre** [glotzerlab/hoomd-blue#1101]
Hi! Is there any information that HOOMD v3.0.0 beta 8 supports ROCm 4.3.0? The requirement [here](https://hoomd-blue.readthedocs.io/en/latest/building.html) says ROCm >= 3.5.0 but is it up-to-date?

While building HOOMD I get a lot of errors like:
`error: no matching function for call to ‘hip_impl::Scalar_accessor<double, double [4], 0>::Scalar_accessor(int)’`
that are similar (or maybe even the same) as  @jglaser pointed to here: https://github.com/ROCm-Developer-Tools/HIP/issues/1675

**Comment by b-butler** [comment]
@niktre, all of the HOOMD developers besides @jglaser do not have access to AMD GPU systems, and HOOMD is not tested with AMD for that reason as well. @jglaser is your best bet to get something working. If `ROCm >= 4.3.0` is not working, we can modify the support claim assuming it works with prior versions.

**Comment by Dann239** [comment]
I've encountered the same problem, HOOMD doesn't properly compile on our system as well. I've made some small workaround tweaks to the code to make it compile on our system. If you're interested, you can check it out [here](https://github.com/Dann239/hoomd-blue/tree/hip-workaround). Though it still doesn't work with HPMC and i can't really guarantee that changes i've made aren't breaking :)
Anyway, i hope you find it useful

**Comment by joaander** [comment]
Feel free to submit a pull request even it if only partially improves support for AMD GPUs. Our situations hasn't changed, the core HOOMD-blue developers currently have no access to any AMD GPU systems so we need to rely on community support to keep it functioning.

**Comment by vvsteg** [comment]
@niktre , could you please make a try with the fork of v3.0.0-beta.12 made by @Dann239 ? 

This fork works on our MI50 equipped cluster under ROCm 3.7. Unfortunately, it is not easy for us at the moment to upgrade ROCm to the newest version.

```
export HCC_AMDGPU_TARGET=gfx906

export HIP_PLATFORM=hcc

cmake -DENABLE_MPI=on -DENABLE_GPU=on -DENABLE_MPI_CUDA=on -DCMAKE_CUDA_COMPILER=hipcc -DBUILD_HPMC=off -DBUILD_TESTING=off ..

make -j6

make install
```
