### ISSUE TITLE
Cosine squared potential

### ISSUE THREAD

**Issue by YouriRan** [glotzerlab/hoomd-blue#1106]
## Description

Implement cosine/squared potential as described in [Cooke 2005](https://aip.scitation.org/doi/10.1063/1.2135785).

## Proposed solution

Implement based on the format of the other pair potentials. Include switch for WCA repulsion. 

## Additional context

This potential is used for the coarse-grained modelling of membrane systems. 

## Developer

Me.

**Comment by YouriRan** [comment]
I implemented this pair potential on a local branch and can make a pull request to contribute. I would want some help to check if the math is implemented efficiently and on how to implement tests.

**Comment by joaander** [comment]
Please submit a draft pull request so we can see the diff and you can ask any questions you have before marking the request ready for review.
