### ISSUE TITLE
Compiling Errors with Single Precision

### ISSUE THREAD

**Issue by danevans09** [glotzerlab/hoomd-blue#1120]
## Description

HOOMD gives compiling errors in the _hoomd/UpdaterRemoveDrift.h_, _hoomd/md/EvaluatorPairLJ1208.h_, and _hoomd/md/EvaluatorPairLJ0804.h_ files when using single precision. This occurs in _UpdaterRemoveDrift.h_ because the `double` data type is used instead of `Scalar`, and occurs in _EvaluatorPairLJ1208.h_ and _EvaluatorPairLJ0804.h_ because the call to `fast::pow` is ambiguous.

## Script

Occurs when compiling with single precision

## Configuration

Platform:
- Mac, CPU
- Linux, GPU

Installation method:
- Compiled from source

Versions:
- **HOOMD-blue** version: latest commit of master, 922fa73

## Developer

I have a local branch that fixes these errors, I can open a pull request

**Comment by joaander** [comment]
While I do not actively support builds with `SINGLE_PRECISION=on`, I will accept PRs that fix compile errors in that mode. Feel free to submit.

In #355, scheduled for v3.1 or later, I plan to enable a full mixed precision mode to enable fast performance on single precision optimized GPUs without sacrificing accuracy.
