### ISSUE TITLE
Add long-range tail correction to Lennard-Jones potential

### ISSUE THREAD

**Issue by jennyfothergill** [glotzerlab/hoomd-blue#1139]
## Description

In working on https://github.com/mosdef-hub/reproducibility_study, @ramanishsingh noted that the Trappe-UA forcefield was getting different density results in the MD and MC engines. In order to compare to the paper in which this forcefield was developed, we must use a long-range correction method. These methods are common in other engines and will help users of atomistic forcefields to represent the forces as they are intended by the forcefield developers.

## Proposed solution

Equation 5 from https://doi.org/10.1021/jp980939v is the correction used by LAMMPS

**Comment by joaander** [comment]
@jennyfothergill has a great start on this in #1138 and I have given detailed review comments on the next steps needed. We need another developer to step up and take the steps and move this work to completion.
