### ISSUE TITLE
File not included in hoomd/md/CMakeLists.txt

### ISSUE THREAD

**Issue by NathanDavisBarrett** [glotzerlab/hoomd-blue#1142]
## Description

There appears to be a missing file in the _md_headers portion of the hoomd/md/CMakeLists.txt file.
I propose that the file "EvaluatorPairDLVO.h" be added so that it can be included externally from hoomd (i.e. in a plugin)

## Script

```C++
// From an external plugin:
#include <hoomd/md/EvaluatorPairDLVO.h>

```

```console
# From terminal, build folder within external plugin
cmake ..
cmake --build ../build/
```

## Output

fatal error:  hoomd/md/EvaluatorPairDLVO.h: No such file or directory

## Expected output

none (compile successfully)

## Configuration

Platform:
- Linux

Installation method:
- Compiled from source

Versions:
- Python version: 3.9
- **HOOMD-blue** version: 2.9

## Developer

I will submit a pull request fixing the issue.

**Comment by joaander** [comment]
Thanks for reporting and submitting the pull request!
