### ISSUE TITLE
error creating object

### ISSUE THREAD

**Issue by zhangsan5213** [glotzerlab/hoomd-blue#1150]
The example gives ConvexPolygon(), yet the function found in the package file is convex_polygon() (The version was downloaded from conda and is 2.9.7). Besides, the example cannot run.
![image](https://user-images.githubusercontent.com/32975453/134554673-c51d4516-a1b2-4cf2-adf3-e6e7464090a6.png)
![image](https://user-images.githubusercontent.com/32975453/134554705-38a9aa79-0735-4956-bd03-1c829cdbdb3b.png)

Any thoughts?

**Comment by joaander** [comment]
This is not a bug. Please review the documentation for HOOMD 2.9.7: https://hoomd-blue.readthedocs.io/en/v2.9.7/ which requires a call to `context.initialize` and `init.*` call before you can instantiate an integrator.

**Comment by zhangsan5213** [comment]
Thanks, joaander. I've got more problems where the documentation does not cover on https://hoomd-blue.readthedocs.io/en/stable/module-hoomd-lattice.html?highlight=unit%20cell#hoomd.lattice.unitcell

what does it mean by the argument "position"? is it the vertex nearest to the origin of the coordinate system? is it the centroid of the polyhedron? (I preferred the latter)

how is the polyhedron actually defined? if the vertices are already defined in a list and assigned using "mc.shape_param.set(, vertices = verts)", how does the argument "diameter" in "hoomd.lattice.unitcell" work? is it a scaling factor to the coordinates of "verts"? (then it would be easier to alter the shape by normalizing the definition in verts)

**Comment by joaander** [comment]
@zhangsan5213 please use the hoomd-users mailing list for support. This issue tracker is meant only to track defects and enhancement requests to the software.
