### ISSUE TITLE
HOOMD restricted to CUDA compute capability >=6

### ISSUE THREAD

**Issue by ianrgraham** [glotzerlab/hoomd-blue#1169]
## Description

I was surprised to find that in jumping from HOOMD-blue 2 to 3, the CUDA compute capability requirement has also been stepped up. At home I'm able to test on a 20 series card (where my code worked), but at my university we have a handful of old but still functional K80s to launch jobs to. Is there a technical reason for this (HOOMD now uses features from CC 6 that aren't available in later generations)? Additionally, I can't find any documentation in the main repo, migration guide, or elsewhere that cites this change.

## Script

```python
import hoomd
device = hoomd.device.GPU()

# ...
# rest of simulation
# ...
```

## Output

```
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    device = hoomd.device.GPU()
  File ".../.venv/lib/python3.8/site-packages/hoomd/device.py", line 214, in __init__
    self._cpp_exec_conf = _hoomd.ExecutionConfiguration(
RuntimeError: No supported GPUs are present on this system.
The device Tesla K80 with computed capability 3.7 does not support HOOMD-blue.
```

## Expected output

The K80 would be detected as a supported device.

## Configuration

Platform:
- Linux
- GPU

Installation method:
- Compiled from source

Versions:
- Python version: 3.8
- **HOOMD-blue** version: 3.0-beta10

**Comment by ianrgraham** [comment]
After fiddling with this for it bit, it appears that the `atomicAdd_system` calls from the `hpmc` module are the only feature that requires compute >= 6.0. Could we modify the CMake files so that during configuration it will fail with compute < 6 and the `hpmc` module enabled, but succeed as long as compute is >= 3.5 and `hpmc` is disabled? 

Though, I'm also a bit more confused by the hard restriction since compiling with HIP allows compute >= 3.5, while I'm sure (though I haven't built it myself) the `hpmc` module is designed to work in that case. In this case, maybe the preprocessor should select the HIP codepath, if one exists, when compiling for compute < 6?

**Comment by joaander** [comment]
HOOMD-blue v3 uses unified memory to manage syncing parameters and other memory buffers between the CPU and GPU. P100 is the first GPU architecture that supports driver backed unified memory migration. v3 relaxes many barriers and allows users to set parameters at any time, even during the simulation run. So it is not possible to meet the strict device synchronization requirements that the K80 unified memory runtime emulation requires. If you enable the 3.5 compute capability in CMake, HOOMD will build but you will get unified memory errors randomly when running.

Most institution level compute centers retire systems as obsolete after 4 years. K80 GPUs were released 7 years ago. P100 was released 5 years ago. While we don't go out of our way to disable support for old GPUs, we do take advantage of new features offered on GPUs widely available at compute centers and will not expend extra developer effort to be remain backwards compatible with obsolete hardware.

I will amend the `ARCHITECTURE.md` file to clarify the level of hardware support HOOMD-blue developers offer.

**Comment by ianrgraham** [comment]
Understood, thanks for the clarification. Though I'm still a bit confused as it appears the current CMake configuration supports CC >= 3.5 when compiling with HIP. Is this an error?

```
# hoomd-blue/CMake/hoomd/HOOMDCUDASetup.cmake 
# line 47
elseif(HIP_PLATFORM STREQUAL "hip-clang")
    set(_cuda_min_arch 35)
endif()
```

**Comment by joaander** [comment]
At the time we implemented the HIP code, HIP's AMD GPU implementation emulated AMD GPUs as having CUDA 8.0 features and compute capability 3.5.
