### ISSUE TITLE
`hoomd.md.special_pair.LJ` constructor causes TypeError when upgrading from 3.0.0dev12 to 3.0.0dev13

### ISSUE THREAD

**Issue by justinGilmer** [glotzerlab/hoomd-blue#1202]
## Description

When upgrading from `hoomd=3.0.0dev12` to `hoomd=3.0.0dev13`, calling the `hoomd.md.special_pair.LJ` constructor immediately errors out with a `TypeError` during initialization.

## Script

```bash
conda install -c conda-forge/label/hoomd_dev hoomd=3.0.0dev12
python mwe.py # runs successfully

conda install -c conda-forge/label/hoomd_dev hoomd=3.0.0dev13
python mwe.py # TypeError: descriptor '__init__' of 'super' object needs an argument
```
`mwe.py`
```python
# Include a minimal script that reproduces the problem
from hoomd.md import special_pair
lj_14 = special_pair.LJ()
```

## Output

```bash
Traceback (most recent call last):
  File "mwe.py", line 3, in <module>
    lj_14 = special_pair.LJ()
  File "/Users/justingilmer/mambaforge/envs/mbuild-dev/lib/python3.7/site-packages/hoomd/md/special_pair.py", line 101, in __init__
    super.__init__()
TypeError: descriptor '__init__' of 'super' object needs an argument
```

## Expected output

```bash

```

## Configuration

Platform:
- Mac
- CPU

Installation method:
- Conda package

Versions:
- Python version: 3.7.12
`python                    3.7.12          haf480d7_100_cpython    conda-forge`
- **HOOMD-blue** version: 3.0.0dev12
`hoomd                     3.0.0dev12      cpu_py37hc99a739_0    conda-forge/label/hoomd_dev`
- **HOOMD-blue** version: 3.0.0dev13

## Developer

Not sure what fix is necessary. The changelog from dev12 to dev13, did not seem to include any changes to this code?

**Comment by b-butler** [comment]
This is what I get for not testing everything at first. We have an open issue for testing special pair #857 which is yet to be done. Is using beta 12 sufficient for your use currently? We will of course fix this, but wanted to gauge the urgency.

**Comment by justinGilmer** [comment]
No worries! Beta12 is completely fine for our use cases currently. Are you able to replicate the same error as above with my mwe? 

Note that I haven’t tested any of the other special_pair objects like the coulomb one, so those might be problematic too.
