### ISSUE TITLE
[question] Why install C++ header files?

### ISSUE THREAD

**Issue by yurivict** [glotzerlab/hoomd-blue#1208]
The project is a Python project.

But it also installs C++ headers into ```%%PYTHON_SITELIBDIR%%/hoomd/include/hoomd```.

What's the purpose? How can they be used without C++ libraries installed along with them? Is this a mistake?

**Comment by joaander** [comment]
The purpose of the headers is so that users can build external components that link to HOOMD-blue's C++ code: https://hoomd-blue.readthedocs.io/en/latest/components.html
This is the same pattern followed by many Python packages, such as **numpy**.

**Comment by yurivict** [comment]
Ok, thank you.
