### ISSUE TITLE
Directly extract all data in gs.hoomd.HOOMDTrajectory object as a an array

### ISSUE THREAD

**Issue by mChoakumchild** [glotzerlab/hoomd-blue#1212]
## Description

I would like to directly access to all of the data stored in the gs.hoomd.HOOMDTrajectory object with one command. The current method of obtaining particle positions from this object is to iterate over each frame (f) of the object and append each frame (f.particles.positions) to different array. Being able to directly access the data from the object would save time. 

## Proposed solution

Update the gsd.hoomd package so that there is a method to directly access all the position files over all the frames from the gs.hoomd.HOOMDTrajectory object. 

## Additional context

I am interested in the position data over all the frames.

**Comment by joaander** [comment]
Thanks for the request. However, you filed the issue to the HOOMD-blue repository. No changes to HOOMD-blue can modify the API of the `gsd` package.
