### ISSUE TITLE
EvaluatorPairTable.h not included in _md_headers in hoomd/md/CMakelists.txt

### ISSUE THREAD

**Issue by spraharsh** [glotzerlab/hoomd-blue#1286]
## Description

EvaluatorPairTable.h not included in _md_sources in hoomd/md/CMakelists.txt. This means that `#include<hoomd/md/AllPairPotentials.h>` using an external component with CMake fail

## Script

```c++
#include<hoomd/md/AllPairPotentials.h>
```

## Output
on compilation
```
/home/praharsh/anaconda3/envs/cb3-3.9/lib/python3.9/site-packages/hoomd/include/hoomd/md/AllPairPotentials.h:26:10: fatal error: EvaluatorPairTable.h: No such file or directory
   26 | #include "EvaluatorPairTable.h"
```

## Expected output

Succesful Compilation

Platform:
- Linux

Installation method:
- Compiled from source

Versions:
- Python version: 3.9.7
- **HOOMD-blue** version: 3.0.0beta

## Developer
I'd be happy to submit a pull request since it's a single line (unless there is a particular reason it was not included)

**Comment by b-butler** [comment]
@spraharsh We would be happy to accept a PR! Thanks! Use the `trunk-patch` branch since this is a bug fix.
