### ISSUE TITLE
Accumulating memory allocation in nlist.Cell & nlist.Stencil

### ISSUE THREAD

**Issue by ianrgraham** [glotzerlab/hoomd-blue#1289]
## Description

When using an nlist.Cell or nlist.Stencil as a neighbor list in HOOMD v3.0.0, the python process accumulates memory until the process is killed. The script executes normally with nlist.Tree. From the behaviour, it seems to have something to do with the _buffer_ parameter.

## Script

```python

BUFFER=0.1

cpu = hoomd.device.CPU()  # or GPU

sim = hoomd.Simulation(device=cpu)

N = 512
phi = 1.2

# Helper functions to setup the snapshot, produces valid states that worked fine in v3-beta9
L = prep.len_from_phi(N, phi)
rng = prep.init_rng(0)
snap = prep.approx_euclidean_snapshot(N, L, rng, dim=3)

sim.create_state_from_snapshot(snap)

integrator = hoomd.md.Integrator(dt=1e-3)
cell = hoomd.md.nlist.Cell(BUFFER)
pot_pair = hoomd.md.pair.LJ(cell, default_r_cut=2.5)
pot_pair.params[('A', 'A')] = dict(epsilon=1.0, sigma=1.0)
integrator.forces.append(pot_pair)

nvt = hoomd.md.methods.NVT(
    kT=1.5,
    filter=hoomd.filter.All(),
    tau=0.5)
integrator.methods.append(nvt)
sim.operations.integrator = integrator

sim.run(0)
```

## Output

On CPU w/ BUFFER>0.0:
_The python process keeps accumulating memory until it is killed by the OS_
[1]    646584 killed     python scripts/test/test_v3.py

On CPU  w/ BUFFER=0.0:
_The process consumes roughly 10GB of memory over 5 seconds, holds steady for about 20 seconds, and then ends in an abrupt segfault. It seems the buffer has some responsibility here since it is affecting the behaviour._
[1]    646749 segmentation fault (core dumped)  python scripts/test/test_v3.py

On GPU:
_Similarly, the process runs out of heap memory, but instead on the GPU_
**ERROR**: out of memory before /hoomd/GPUArray.h:1022

## Expected output

None.

## Configuration

At first I saw this after updating my forked branch of HOOMD to v3 and updating my scripts to be compatible, but I also get the same behavior using the latest build for v3.0.0 on conda-forge.

Platform:
- Linux
- GPU
- CPU

Installation method:
- Conda package
- Compiled from source

Versions:
- Python version: 3.8.12
- **HOOMD-blue** version: 3.0.0

## Developer

I'd be happy to help fix this, though it's a bit out of my expertise how to debug mixed python/C++ projects with proper debugger tools (I can't find an easy way to step into the C++ function calls from the python script). Any advice there would be appreciated.

**Comment by b-butler** [comment]
@ianrgraham  I did a quick `git diff` between beta 9 and 3.0.0, but couldn't see anything that made me suspect a new memory leak.

I also ran a modified version of the code you sent without issue.

```python
import freud
import hoomd
import numpy as np

BUFFER=0.1

cpu = hoomd.device.CPU()  # or GPU

sim = hoomd.Simulation(device=cpu)

N = 512
phi = 1.2

# Helper functions to setup the snapshot, produces valid states that worked fine
# in v3-beta9
box, pos = freud.data.UnitCell.sc().generate_system(int(512 ** (1 / 3)))
snap = hoomd.Snapshot()
snap.configuration.box = box
N_actual = len(pos)
snap.particles.N = N_actual
snap.particles.types = ["A"]
snap.particles.typeid[:] = np.zeros(N_actual)
snap.particles.position[:] = pos

sim.create_state_from_snapshot(snap)

integrator = hoomd.md.Integrator(dt=1e-3)
cell = hoomd.md.nlist.Cell(BUFFER)
pot_pair = hoomd.md.pair.LJ(cell, default_r_cut=2.5)
pot_pair.params[('A', 'A')] = dict(epsilon=1.0, sigma=1.0)
integrator.forces.append(pot_pair)

nvt = hoomd.md.methods.NVT(
    kT=1.5,
    filter=hoomd.filter.All(),
    tau=0.5)
integrator.methods.append(nvt)
sim.operations.integrator = integrator

sim.run(0)
```
So I am unable to reproduce your error.

In other news, to step into a C++ function using a debugger, you need to compile HOOMD with debug symbols and create a python script that you know to lead to some error (SEGFAULT, etc.), or you can set breakpoints like normal. You then run `gdb python` and debug like normal.

**Comment by ianrgraham** [comment]
Huh, well that executes just fine for me, using freud to build up the SC lattice. I don't think I'm doing anything crazy building up my initial states? But that's the only thing that seems to differ.

``` python
def approx_euclidean_snapshot(
        N: int,
        L: float,
        rng: np.random.Generator,
        dim: int = 2,
        particle_types: Optional[List[str]] = None,
        ratios: Optional[List[int]] = None
        ) -> gsd.hoomd.Snapshot:
    '''Constucts hoomd simulation snapshot with regularly spaced particles on a
    euclidian lattice.

    Easy way to initialize simulations states for pair potentials like
    Lennard-Jones where large particle overlaps can leading to particles being
    ejected from the box. Simulation should be thoroughly equilibrated after
    such setup.

    Arguments
    ---------
        `N`: Number of particles.
        `L`: Side length of the simulation box.
        `rng`: `numpy` RNG to choose where to place species.
        `dim`: Physical dimension of the box (default=2).
        `particle_types`: List of particle labels (default=['A', 'B']).
        `ratios`: List of particle ratios (default=[50, 50]).

    Returns
    -------
        `Snapshot`: A valid `hoomd` simulation state.
    '''

    if particle_types is None:
        particle_types = ['A', 'B']
    
    if ratios is None:
        ratios = [50, 50]

    # only valid dims in hoomd are 2 and 3
    assert dim in [2, 3], "Valid dims in hoomd are 2 and 3"
    assert L > 0, "Box length cannot be <= 0"
    assert N > 0, "Number of particles cannot be <= 0"
    len_types = len(particle_types)
    assert np.sum(ratios) == 100, "Ratios must sum to 100"
    assert len_types == len(ratios), "Lens of 'particle_types' and 'ratios' must match" 

    n = int(np.ceil(np.power(N, 1/dim)))
    x = np.linspace(-L/2, L/2, n, endpoint=False)
    X = [x for _ in range(dim)]
    if dim == 2:
        X.append(np.zeros(1))
    grid = np.meshgrid(*X)
    grid = [x.flatten() for x in grid]
    pos = np.stack(grid, axis=-1)

    if dim == 2:
        Lz = 0.0
    else:
        Lz = L
    # build snapshot and populate particles positions
    snapshot = gsd.hoomd.Snapshot()
    snapshot.particles.N = N
    snapshot.particles.position = pos[:N]
    snapshot.configuration.box = [L, L, Lz, 0.0, 0.0, 0.0]
    snapshot.particles.types = particle_types
    snapshot.particles.typeid = [0] * N

    # assign particle labels with rng
    idx = 0
    limits = np.cumsum(ratios)
    j = 0
    for i in rng.permutation(np.arange(N)):
        snapshot.particles.typeid[i] = idx
        if j/N*100 > limits[idx]:
            idx += 1
        j += 1

    return snapshot
```

And oh okay, yes I compiled with Debug symbols but I was trying to use the integrated VSCode debugger to step into the C++ call to `run` (which didn't work). I'll try from the command line.

**Comment by ianrgraham** [comment]
Oh I'm sorry, it's very dumb. The box was accidentally being made absurdly large (like L=10^7), which was requiring an absurdly large Cell to be constructed. Sorry to bother!
