### ISSUE TITLE
ALJ Overlap Check

### ISSUE THREAD

**Issue by tommy-waltmann** [glotzerlab/hoomd-blue#1293]
## Description

The code which implements the overlap check in ALJ may give false positives and false negatives. When scripts are run using a debug build, this can cause unwanted failures in an assert statement in the evaluator code. This bug does not affect simulation results given a proper initial condition, so it does not affect any hoomd releases.

This issue would require significant developer time and effort to fix, and would require a detailed knowledge of the GJK algorithm as a prerequisite for trying to fix it.

I am making this issue to document that this is something that can happen in the ALJ code in debug builds, not to try and get an immediate solution for the bug.

Platform:
- Mac
- Linux
- GPU
- CPU

Installation method:
- Compiled from source

Versions:
- **HOOMD-blue** version: 3.0.0

## Developer

Any developer who has the time, prerequisite knowledge, and the motivation to do it.

**Comment by joaander** [comment]
Fixed in #1292

**Comment by vyasr** [comment]
I believe that #1292 fixes #1282. This issue was opened by @tommy-waltmann to track future work.

**Comment by joaander** [comment]
You are correct.
