### ISSUE TITLE
Number of dimensions inconsistent between python and c++ if 2D system initialized from gsd file with Lz != 0

### ISSUE THREAD

**Issue by tcmoore3** [glotzerlab/hoomd-blue#1312]
Feel free to make a more succinct title.

## Description
I've initialized a simulation from a gsd file (via `create_state_from_gsd`) that was created from a 2D simulation in HOOMD v2.
Since the gsd was created with v2, the `Lz` value of the box is not zero.
`sim.state.box.dimensions` returns 3, whereas `sim.state._cpp_sys_def.getNDimensions` returns the correct value of 2.
This causes errors anywhere that `sim.state.box.dimensions` is used, e.g., in [the SDF compute](https://github.com/glotzerlab/hoomd-blue/blob/50e1fb3e3cc3d294f002bcb000667673c130a5f3/hoomd/hpmc/compute.py#L315).

## Script

```python
device = hoomd.device.CPU()
sim = hoomd.Simulation(device=device, seed=0)
sim.timestep = 0 
gsd_init_fn = job.fn('hello.gsd')  # 2D sim from v2.9.6, box.Lz = 1
sim.create_state_from_gsd(gsd_init_fn)
print(f'sim.state.box.dimensions = {sim.state.box.dimensions}')
print(f'sim.state._cpp_sys_def.getNDimensions = {sim.state._cpp_sys_def.getNDimensions()}')
```

## Output

```
sim.state.box.dimensions = 3
sim.state._cpp_sys_def.getNDimensions = 2
````

## Expected output

```
sim.state.box.dimensions = 2
sim.state._cpp_sys_def.getNDimensions = 2
```

## Configuration

Platform:
- Linux
- GPU
- CPU

Installation method:
- Compiled from source

Versions:
- Python version: 3.9.7
- **HOOMD-blue** version: 3.1.0

## Developer

I'm happy to implement the fix, but will need to discuss with @b-butler and/or @joaander to make sure we do it The Right Way™.

**Comment by b-butler** [comment]
Resolved by #1313.
