### ISSUE TITLE
Inconsistant use of `hoomd.filter` and `hoomd.filter.ParticleFilter`

### ISSUE THREAD

**Issue by b-butler** [glotzerlab/hoomd-blue#1319]
## Description
We document the type as `hoomd.filter` for some constructors that take a filter and `hoomd.filter.ParticleFilter` for others. Since `hoomd.filter.Custom` is not a `ParticleFilter` we document the type as `hoomd.filter` in some places. Regardless of preference we should be consistent in this.

## Fix
Choose a style and stick to it.

**Comment by joaander** [comment]
Should we be pedantic and document it as "`hoomd.filter.ParticleFilter` or `hoomd.filter.Custom`"?

**Comment by b-butler** [comment]
We could be. We could also use type annotations here to expose the type `ParticleFilterType` which is `typing.Union[(hoomd.filter.Custom, hoomd.filter.ParticleFilter)]`.

**Comment by joaander** [comment]
I thought that the the standard was not to use type annotations in documentation.

**Comment by b-butler** [comment]
You can document type annotations NumPy does this https://numpy.org/devdocs/reference/typing.html, and sphinx shows this if type annotations exist in the method/function. However, doing so in the docstring is less common. In this case it is a fairly simple type definition, so I don't know if it would hurt readability. This would just keep it a little less verbose, but I am fine with either solution.

**Comment by joaander** [comment]
I can't find it, but I remember a discussion early in the v3 development. We had been using the type hints format to document all types in docstrings and Bradley pointed to some standard saying we should use an alternate format. That is the format we use everywhere in the hoomd docs now.

Whatever we choose to do, we should be consistent across the codebase.

**Comment by b-butler** [comment]
I am not recommending documenting types with `Union[(a, b, c, ...)]`, but creating a type which we can point to document what we accept. The way NumPy addresses this is through documenting things as `array_like` which is not linked to any explanation. We could do this with a `filter_like` or `trigger_like` object as well for more complicated parameter typing. NumPy also uses `ndarray or tuple of ndarray` in their documentation of types, so we could do that although the length may get ponderous.

**Comment by joaander** [comment]
Ah, now I understand. That makes sense.

**Comment by joaander** [comment]
Should we also document `box_like`? There is a `box_preprocessing` that automatically applies `from_box`.

**Comment by b-butler** [comment]
I was thinking this actually, and was planning on doing it in #1340 before merging. This case though has a more difficult type annotation as it is very duck-typed, but we should document it at least.
