### ISSUE TITLE
LjGauss potential is not documented correctly. 

### ISSUE THREAD

**Issue by ishamalhotra612** [glotzerlab/hoomd-blue#1334]
## Description
In the second term, it is 2*(1/r)**6 rather than (2/r)**6. 

## Script

```python
# Include a minimal script that reproduces the problem

```

## Configuration

Platform:
- Mac
- Linux
- GPU
- CPU

Installation method:
- Conda package
- Compiled from source
- glotzerlab-software container

Versions:
- Python version: ?.?.?
- **HOOMD-blue** version: ?.?.?

**Comment by joaander** [comment]
Fixed in #1342.
