### ISSUE TITLE
More useful error message on md external field for not assigning E to all particle types.

### ISSUE THREAD

**Issue by syjlee** [glotzerlab/hoomd-blue#1345]
## Description
It'd be good if users can have a more detailed error message when not assigning E value to all the particle types. When partially assigned, the current error message is:
```
e_field = hoomd.md.external.field.Electric()
e_field.E['A'] = (1, 0, 0)
integrator.forces.append(e_field)
```
```
RuntimeError: Unable to cast Python instance to C++ type (compile in debug mode for details)
```

## Motivation and context
More detailed error message would help users trouble shoot

**Comment by joaander** [comment]
Fixed in #1361
