### ISSUE TITLE
Provide more detailed error messages when there are too many bond or particle types

### ISSUE THREAD

**Issue by joaander** [glotzerlab/hoomd-blue#1370]
## Description

Add a check that the requested shared memory does not exceed the available before launching kernels. Throw an exception with a meaningful error message when there is not enough shared memory.

## Motivation and context

Presently, the error message comes from an unrelated GPUArray file. See https://groups.google.com/g/hoomd-users/c/wfQHv5Gocxk for an example.

**Comment by joaander** [comment]
List of kernels using dynamic shared memory:
- HPMC
  - [x] ComputeFreeVolumeGPU
  - [x] IntegratorHPMCMonoGPU
  - [x] IntegratorHPMCMonoGPUDepletants
  - [x] IntegratorHPMCMonoGPUDepletantsPhase1
  - [x] IntegratorHPMCMonoGPUDepletantsPhase2
  - [x] IntegratorHPMCMonoGPUJIT
  - [x] IntegratorHPMCMonoGPUMoves
  - [x] UpdaterClustersGPU
  - [x] UpdaterClustersGPUDepletants
- MD
  - [x] AnisoPotentialPairGPU
  - [x] BondTablePotentialGPU
  - [x] ~~NeighborListGPU~~
  - [x] NeighborListGPUBinned
  - [x] NeighborListGPUStencil
  - [x] PotentialBondGPU
  - [x] PotentialExternalGPU
  - [x] PotentialPairDPDThermoGPU
  - [x] PotentialPairGPU
  - [x] PotentialTersoffGPU
  - [x] PPPMForceComputeGPU
  - [x] TwoStepBDGPU
  - [x] TwoStepLangevinGPU
  - [x] TwoStepRATTLEBDGPU
  - [x] TwoStepRATTLELangevinGPU
  - [x] ComputeThermoGPU
  - [x] ForceCompositeGPU
  - [x] FIREEnergyMinimizerGPU
  - [x] ComputeThermoHMAGPU
- Other
  -  [x] CommunicatorGPU

These kernels need to either a) Raise an exception when using too much shared memory or b) Switch to a global memory code path when the shared memory usage is too high.

**Comment by joaander** [comment]
Planned kernels to update with global memory code path:
- MD
  - [x] NeighborListGPUBinned
  - [x] PotentialPairGPU
  - [x] PotentialBondGPU
  - [x] TwoStepBDGPU
  - [x] TwoStepLangevinGPU

Other kernels may be expanded in future work, as needed by users.

**Comment by mphoward** [comment]
I believe `PotentialBondGPU` is also using shared memory

**Comment by joaander** [comment]
> I believe `PotentialBondGPU` is also using shared memory

Indeed, as are some other kernels. Apparently `extern __shared__` is still valid HIP syntax. I had been searching for `HIP_DYNAMIC_SHARED`.

**Comment by joaander** [comment]
This is the performance (on GV100) of a MD LJ liquid benchmark with the shared and global code paths.
![image](https://user-images.githubusercontent.com/2197568/187477802-b824c0df-3439-4c3f-94b1-cea50314fa1c.png)

**Comment by joaander** [comment]
auto-selection works:
![output](https://user-images.githubusercontent.com/2197568/187553255-f726da8f-4612-46f7-b233-5c73d804b279.png)
