### ISSUE TITLE
Improve documentation of ALJ potential and default rounding_radii to 0

### ISSUE THREAD

**Issue by Charlottez112** [glotzerlab/hoomd-blue#1395]
## Motivation and context

1. Currently the documentation does not include examples for setting parameters of AWCA, but this is a popular user case.   
2. Several people have also reported similar problems when first trying out this potential, and there are tricks to solve the issue that are not in the doc.
3. One of the `params` users need to set is `rounding_radii`, which probably **should** be set to 0 if the user wishes to simulate purely repulsive and anisotropic particles? The documentation of this parameter is kinda confusing because it does not explain what the rounding ellipsoid/sphere is. It may be easily confused with the contact sphere. So it may make sense to default this parameter to 0. (A similar parameter in HPMC is defaulted to 0).

**Comment by b-butler** [comment]
@Charlottez112 from my understanding the algorithm then becomes unstable at sharper edges so some small amount of rounding is recommended.

**Comment by Charlottez112** [comment]
> @Charlottez112 from my understanding the algorithm then becomes unstable at sharper edges so some small amount of rounding is recommended.

@joaander told me that the `rounding_radii` applies another level of rounding to that convex hull - much like `ConvexSphereopolyhedron` in HPMC, and Vyas used it to model ellipsoids. Personally I'm still not sure what this is for. Originally I set it to 1, and after I changed it to 0, I noticed significant speed-up in TPS. So I think it's probably important to explain to users what this does?

**Comment by joaander** [comment]
@vyasr can you confirm that most users should set `rounding_radii` to `(0,0,0)`? What cases should users set a non-zero `rounding_radii`?

**Comment by vyasr** [comment]
That is correct. The `rounding_radius` controls the actual geometry of the shape and can be used to simulate spheropolyhedra or ellipsoids (in the limit of no vertices). The `contact_ratio` parameter controls the size of the contact sphere that mediates the contact point interaction, i.e. it corresponds to the sigma of the LJ interaction imposed between the closest points of the shapes. The first one can be thought of as purely geometric since it defines the extent of the shape, whereas the latter is really a parameter of the interaction potential. As @b-butler, making the `contact_ratio` too small will result in an extremely hard potential and a very sharp shape, both of which will lead to simulations that explode very quickly unless `dt` is very small. Users trying to simulate polyhedra/polygons (as opposed to spherpolyhedra/spheropolygons) should be setting the rounding radius to 0.

**Comment by Charlottez112** [comment]
> That is correct. The `rounding_radius` controls the actual geometry of the shape and can be used to simulate spheropolyhedra or ellipsoids (in the limit of no vertices). The `contact_ratio` parameter controls the size of the contact sphere that mediates the contact point interaction, i.e. it corresponds to the sigma of the LJ interaction imposed between the closest points of the shapes. The first one can be thought of as purely geometric since it defines the extent of the shape, whereas the latter is really a parameter of the interaction potential. As @b-butler, making the `contact_ratio` too small will result in an extremely hard potential and a very sharp shape, both of which will lead to simulations that explode very quickly unless `dt` is very small. Users trying to simulate polyhedra/polygons (as opposed to spherpolyhedra/spheropolygons) should be setting the rounding radius to 0.

What do you think about defaulting this parameter to 0? Based on what you described, it seems like in the most cases this should be set to 0. The only cases are when users want to simulate spheropolyhedra or ellipsoids, or when the sims explode and there's no other parameters to tune?

**Comment by joaander** [comment]
Yes, the default should be 0.

**Comment by vyasr** [comment]
> The only cases are when users want to simulate spheropolyhedra or ellipsoids, 

Mainly this one. The parameter should be used to define the geometry, nothing else really.

> when the sims explode and there's no other parameters to tune?

I would avoid this. You can always tune the `contact_radius` instead if you need to soften the potential. The rounding radius affects both the central potential and the contact potential, and the contact potential will practically always be the reason for the potential being too hard.
