### ISSUE TITLE
The mpi-test_communication test requires excessive resources

### ISSUE THREAD

**Issue by yurivict** [glotzerlab/hoomd-blue#1396]
## Description

On a computer with 24GB of memory this test causes heavy swapping.

Versions:
- Python version: 3.9
- mpich-3.4.3
- **HOOMD-blue** version: 3.4.0
- FreeBSD 13.1

**Comment by joaander** [comment]
Thanks for reporting this behavior. I am not able to reproduce it:
```
$ /usr/bin/time -v mpirun -n 8 test_communication
        Command being timed: "mpirun -n 8 test_communication"
        User time (seconds): 148.17
        System time (seconds): 3.51
        Percent of CPU this job got: 727%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:20.83
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 279088
...
```
279088 kiB * 8 = 2.12 GiB. Actual usage will be less than 2.12 GB as ranks 1-7 do not use as much memory as rank 0.

**Comment by yurivict** [comment]
Apparently all of them run in 2+GB.

**Comment by joaander** [comment]
> Apparently all of them run in 2+GB.

No, not on my test system (Ubuntu 22.04, CUDA 11.7, gcc 11.2). `free -m` reports 979 MiB more memory available after the test completes compared to when it was running.

**Comment by yurivict** [comment]
not stale

**Comment by joaander** [comment]
I was unable to reproduce the issue as described. Regardless, HOOMD-blue is a simulation software and should be expected to use large amounts of memory. The unit tests cover a wide range of parameters users may choose which may lead to high memory utilization.
