### ISSUE TITLE
Project still installs MPI-related files when built with ENABLE_MPI=OFF

### ISSUE THREAD

**Issue by yurivict** [glotzerlab/hoomd-blue#1398]
## Description
These MPI-related files are installed:
```
%%PYTHON_SITELIBDIR%%/hoomd/include/hoomd/HOOMDMPI.h
%%PYTHON_SITELIBDIR%%/hoomd/include/hoomd/MPIConfiguration.h
%%PYTHON_SITELIBDIR%%/hoomd/include/hoomd/extern/dfftlib/CUDA_MPI.cmake
```

Versions:
- Python version: 3.9
- **HOOMD-blue** version: 3.4.0

**Comment by joaander** [comment]
Thanks for reporting. These files must be present for users to build external components. They may have MPI in the name, but they are included by other files even when `ENABLE_MPI` is not set:
https://github.com/glotzerlab/hoomd-blue/blob/e17d2d391d8734fd5e8538de9ee45179a175db37/hoomd/Messenger.h#L8-L14
