### ISSUE TITLE
"Modern" integrator

### ISSUE THREAD

**Issue by MartinGirard** [glotzerlab/hoomd-blue#1419]
### Description

The Nosé-Hoover thermostat/barostat implemented in hoomd are "primitive" and better integrators have been developed over the years. Two refinements are easy to implement and would provide better behavior, in particular related to ergodicity: the stochastic velocity rescale (thermostat), and the langevin piston (barostat). 

### Proposed solution

On the API side, new python classes can be exported. 

For the implementation, the langevin piston can be implemented by making the langevin piston class inherit from the NPT integrator, make the advanceBarostat function of the NPT integrator virtual, and override it. 

The stochastic velocity rescale is similar to the currently implemented Berendsen thermostat. I should point out that many integrators would then also share similar kernels, see NVTMTK, Berendsen (+proposed v-rescale); as well as NPTMTK + the proposed v-rescale + langevin piston. They typically differ by a rescaling constant passed in. The kernels could potentially be abstracted out. 

### Additional context

I had written custom integrators for hoomd 2.9.7 that I should update. However, my implementation had to include a large amount of boilerplate code. The proposed solution, which includes making some functions virtual, would simplify this.

**Comment by joaander** [comment]
Yes, I would welcome the addition of these modern integration methods to HOOMD and a refactoring of the existing integration methods to facilitate code reuse. This will be a great benefit for the HOOMD user community as the existing NVT and NPT integrators have a number of pain points.

Will you be contributing this as a pull request @MartinGirard? Will the new methods integrate and thermostat the rotational degrees of freedom?

Berendsen exists in the codebase, but I don't think it is well used. I just discovered that it was not documented in v3 and no one has commented on it yet. The implementation has a number of issues, as it lacks MPI support and it does not integrate the rotational degrees of freedom.

**Comment by MartinGirard** [comment]
@joaander I will, although I cannot give you a precise timetable right now. I intend for them to work with anisotropic dofs.

**Comment by joaander** [comment]
Excellent, let us know if you have any questions.
