### ISSUE TITLE
Remove error message with the word freud in it

### ISSUE THREAD

**Issue by tommy-waltmann** [glotzerlab/hoomd-blue#1426]
### Description

An error message in the `hoomd.Box.from_box` method appears to have been copied from freud, see line 300 in `hoomd/box.py`. Fixing this just requires re-wording an error message.

### Motivation and context

The person who implemented the `from_box` method likely got a bit lazy and didn't remember to change the error message.

**Comment by b-butler** [comment]
@tommy-waltmann guilty as charged.
