### ISSUE TITLE
Molecules and operations on molecules (e.g. semi-grand ensemble, configurational bias insertion, etc.)

### ISSUE THREAD

**Issue by MartinGirard** [glotzerlab/hoomd-blue#1445]
### Description

I want to implement molecular operations in hoomd. For instance, semi-grand canonical moves, where a chemical potential can be assigned to each molecule independently. 

### Proposed solution

The API can define a group of molecules by using hoomd.group:
`my_molecules = molecules(group, ...)`
where ... could define how to group the beads, for instance by grouping all beads that are connected by bonds, or only with the group etc.

Monte-Carlo moves required to update the molecule would have to define which parts of the molecule can change, for instance:
`bead_move = bead_swap(my_molecules, another_group, bead_types = ['A', 'B'])`

The set of molecules need to provide an iterator that describe which molecules can arise out of this, so that chemical potentials can be assigned. Internally, we would need to assign a hash to every molecule. This iterator needs to fully describe the molecule state, including associated bonded force-field changes. An idealized version would be:
`for mol in my_molecules:
    my_molecules.set_mu(mol, value)
`
where the quantity `mol` also returns chemical information, e.g. bead_types, bonded types, ... 

Practically, we also need to ensure that there are paths between every "chemistry". Efficient beadtype swaps require parallelization over a checkerboard. Swaps can therefore only be done on single beads, or directly bonded beads if they are excluded from non-bonded interactions. 

### Additional context

I already have a plugin that implements some of these ideas (for hoomd 2.9.x, https://gitlab.mpcdf.mpg.de/mgirard/sgc-molecules) that I was in the process of porting to hoomd 3.x. Some aspects already have to be generalized, e.g. to handle beadtype swaps on two connected beads. I would open a pull request (or multiple).

**Comment by joaander** [comment]
Some users are generally interested in more molecule orientated data structures. The existing MolecularForceCompute has some severe limitations, so this would be a good addition to the core HOOMD. I'd like to understand more what you are proposing.

* How specifically will users define molecules? Will there be option flags, a Python callback, and/or something else?
* Does this introduce new per-particle quantities, or is it a separate data structure?
* What types of lookups does the data structure make efficient? Is it geared toward finding all particles given a molecule id, finding the molecule id given a particle, or both?

You mention an iterator that describes what molecules can arise. Is this some sort of rules based system that computes a set of molecules matching potential rules? What can the user do with the generated molecules? Can they add them to the system? How do they define the rules for generating the molecules? How does the hash of the generated molecule interact with the particles in the simulation state?

**Comment by MartinGirard** [comment]
@joaander I would propose that users define a set of molecules by passing a particle filter to the cpp side. The code would then iterate over bonds and determine which of these particules are within a molecule. Introduced quantities would be a per-molecule hash that describes the current "state" of the molecule.

We could attach molecular "computes" and "updaters" to this structure. Each object would compute/update a part of the hash. 

The molecular ensemble + these computes would be used to generate an iterator over the chemical space so that chemical potentials can be assigned. 

Interaction of the hash and the molecular simulation would be determined by what the updaters do. A specific one I have in mind is a semi-grand ensemble, where the updater would alter particle properties, i.e. diameters / charge / particle type or even bonded FF types.

I should be able to generate a draft soon, and we can then discuss a bit more.
