### ISSUE TITLE
TypeError("expected x and y to have same length") in SDF.betaP.

### ISSUE THREAD

**Issue by joaander** [glotzerlab/hoomd-blue#1455]
https://github.com/glotzerlab/hoomd-blue/blob/008828051e9030451f2dc84b69f8df851b75f9d1/hoomd/hpmc/compute.py#L331-L336

This code can results in different lengths for the arrays, resulting in `TypeError("expected x and y to have same length")`.

Reported in: https://groups.google.com/g/hoomd-users/c/qMqIWIr0jUs

**Comment by tcmoore3** [comment]
I will fix this in #1391

**Comment by joaander** [comment]
Will #1391 be complete for the next release (early-mid January)? If not, it is a one line fix to complete in a separate PR based on `trunk-patch`. I would do something like:
```
x_fit = numpy.arange(0, n_fit, 1) * self.dx
```
