### ISSUE TITLE
Attaching a logger to a writer prevents GC from cleaning up memory

### ISSUE THREAD

**Issue by ianrgraham** [glotzerlab/hoomd-blue#1457]
### Description

I was recently running a number of simulations in a loop, instantiating a new simulation object on each pass, and I noticed that upon each pass the GPU memory used by my process kept growing linearly. I tracked this down to the use of the standard logger. Removing the logger from the writer, or removing all analyzers from the logger eliminates the leak. This effects both CPU and GPU memory.

### Script

```python
import hoomd
import freud
import matplotlib.pyplot as plt

import gc
import os
import psutil

# memory leak occurs both on CPU and GPU
device = hoomd.device.GPU()
# device = hoomd.device.CPU()

def setup_sim(snap):
    sim = hoomd.Simulation(device, seed=0)
    sim.create_state_from_snapshot(snap)

    integrator = hoomd.md.Integrator(1e-3)

    nlist = hoomd.md.nlist.Tree(buffer=0.3)
    lj = hoomd.md.pair.LJ(nlist, default_r_cut=2.5)
    lj.params[('A', 'A')] = dict(sigma=1.0, epsilon=1.0)

    nve = hoomd.md.methods.NVT(hoomd.filter.All(), 1.0, 0.1)
    integrator.forces = [lj]
    integrator.methods = [nve]
    sim.operations.integrator = integrator

    return sim


def make_snapshot():
    snap = hoomd.Snapshot()

    box, pos = freud.data.UnitCell.fcc().generate_system(20)

    snap.particles.N = len(pos)
    snap.particles.position[:] = pos
    snap.particles.typeid[:] = 0
    snap.particles.types = ["A"]
    snap.configuration.box = box
    return snap

snap = make_snapshot()

mem_usage = []

for i in range(10):
    process = psutil.Process(os.getpid())
    mem = process.memory_info().rss//1024**2
    mem_usage.append(mem)
    print("Iter:", i, "Memory Usage (MB):", mem)

    sim = setup_sim(snap)

    log = hoomd.logging.Logger()
    analyzer = hoomd.md.compute.ThermodynamicQuantities(filter=hoomd.filter.All())

    sim.operations.computes.append(analyzer)

    log.add(sim, quantities=["timestep"])  # commenting out this line removes the leak

    write_trigger = hoomd.trigger.Periodic(1000, phase=sim.timestep)
    # removing the log parameter from the writer also removes the leak
    writer = hoomd.write.GSD(filename="test.gsd", trigger=write_trigger, mode="wb", log=log)
    sim.operations.writers.append(writer)

    sim.run(1)
    del sim, analyzer, log, writer, write_trigger
    gc.collect()

plt.plot(mem_usage)
plt.ylabel("Memory Usage (MB)")
plt.xlabel("Simulation Iteration")

plt.show()
```

### Output

```shell
Iter: 0 Memory Usage (MB): 319
Iter: 1 Memory Usage (MB): 452
Iter: 2 Memory Usage (MB): 582
Iter: 3 Memory Usage (MB): 712
Iter: 4 Memory Usage (MB): 842
Iter: 5 Memory Usage (MB): 972
Iter: 6 Memory Usage (MB): 1102
Iter: 7 Memory Usage (MB): 1231
Iter: 8 Memory Usage (MB): 1361
Iter: 9 Memory Usage (MB): 1491
```

### Platform

CPU, GPU, Linux

### Installation method

Compiled from source

### HOOMD-blue version

3.6.0

### Python version

3.10.6

**Comment by joaander** [comment]
As long as there is at least one references to the System object that is not garbage collected, then you should expect the memory usage to increase as you observe. To obtain the behavior you intend, one needs to determine why the garbage collector is not able to release the analyzers in the logger.

**Comment by ianrgraham** [comment]
Outside of the `hoomd` internals, all of the references to `sim` in this example are being cleaned up.

The reasoning here doesn't quite make sense with me, but the leak crops up if a `Logger` has a `_LogEntry` that also refers to the simulation state, like done by the line 

``` python
log.add(sim, quantities=["timestep"])
```

and reference cycles that refer back to the `Simulation` like these are all over `hoomd`, and the GC has no problem cleaning them up.

This only becomes an issue when the logger is attached to a `GSD` writer, which is then attached to the simulation. Surprisingly, `Table` also suffers from this problem. The only commonality I see is that the cpp classes that back them pass the logger in as a `pybind11::object`. Should this instead by some kind of `shared_ptr`?

**Comment by joaander** [comment]
No, `GSDDumpWriter` must store a `pybind11::object` because the stored object is a (possibly user-created) object implemented only at the Python level. `pybind11::object` handles reference counting using the standard CPython API: https://pybind11.readthedocs.io/en/stable/reference.html?highlight=object#with-reference-counting. `pybind11` binds `shared_ptr`s handles the interoperation between C++ and Python reference counts and the objects are destroyed when both Python and C++ counts go to 0. HOOMD uses `weak_ptr` where necessary to break cycles at the C++ level.

`Table` is implemented in pure Python: https://github.com/glotzerlab/hoomd-blue/blob/trunk-patch/hoomd/write/table.py. This may prove an easier path to troubleshoot which objects/references the garbage collector is unable to resolve as intended.

@b-butler any ideas?

**Comment by b-butler** [comment]
I am not sure why this is happening. Circular references should be able to be cleaned up by the garbage collector, and otherwise the reference counter should do its work. If `Table` does this, then this is likely not a pybind11 or C++ HOOMD issue though.

**Comment by joaander** [comment]
Testing this, `gc.collect()` returns 0 and `gc.garbage` (https://docs.python.org/3/library/gc.html#gc.garbage) is an empty list.

As a workaround, clear the writers list:
```
sim.operations.writers.clear()
```
Then the garbage collector is able to free the `sim` object.

`log.remove(sim, quantities=["timestep"])` also results in the garbage collector working as intended. It appears that the the collector examines the loop `sim -> writer -> internal action -> log -> sim` and determines that `sim` is still accessible. It is strange that the `sim -> writer -> internal action -> log -> analyzer -> sim` is handled properly.  Perhaps it has something to do with how `Logger` stores its members? Any ideas @b-butler?

I didn't find the other debugging facilities in `gc` helpful: `gc.get_referrers(sim)` gives the same list before and after `log.remove(sim, quantities=["timestep"])`.

**Comment by b-butler** [comment]
We have a lot of indirection in the Python side with `sim -> writer -> internal action -> logger -> logger entry -> sim` but other than that, no idea.
