### ISSUE TITLE
Add a quick starter guide for adding isotropic interactions in HPMC

### ISSUE THREAD

**Issue by Charlottez112** [glotzerlab/hoomd-blue#1505]
## Tutorial description

This is inspired by the tutorial on how to model patchy particles with HPMC glotzerlab/hoomd-examples#84. 
The goal of this guide: demonstrate how to add isotropic interactions in HPMC. 
Like in glotzerlab/hoomd-examples#84, it would be helpful to mention the commonly used potentials, why one might want to use this, etc.

**Comment by joaander** [comment]
@tcmoore3 Could you add a short howto guide in hoomd for a square well potential? These consist of one fully functioning example code along with a brief description (see https://hoomd-blue.readthedocs.io/en/v3.9.0/howto/molecular.html for the only current example).

The commonly used isotropic potential id square well, and the reason one would want to use HPMC is when they have a discontinuous potential.

**Comment by joaander** [comment]
Fixed in #1508.
