### ISSUE TITLE
Build fails due to the use of deprecated C++ feature std::unary_function

### ISSUE THREAD

**Issue by yurivict** [glotzerlab/hoomd-blue#1590]
### Description

```
/wrkdirs/usr/ports/science/py-hoomd-blue/work/hoomd-blue-4.0.1/hoomd/ParticleData.cc:2893:32: error: no template named 'unary_function' in namespace 'std'; did you mean '__unary_function'?
struct comm_flag_select : std::unary_function<const unsigned int, bool>
                          ~~~~~^~~~~~~~~~~~~~
                               __unary_function
/usr/include/c++/v1/__functional/unary_function.h:46:1: note: '__unary_function' declared here
using __unary_function = __unary_function_keep_layout_base<_Arg, _Result>;
^
1 error generated.
```

clang-16 is more strict than the previous versions and it now fails when deprecated C++ features are used.

std::unary_function was removed in C++17, see [here](https://en.cppreference.com/w/cpp/utility/functional/unary_function), and you use C++17.

You need to remove the use of deprecated features and make a release.

Thank you,
Yuri

FreeBSD 13.2

### Script

```python
n/a
```

### Input files

n/a

### Output

```shell
n/a
```

### Expected output

n/a

### Platform

Linux

### Installation method

Compiled from source

### HOOMD-blue version

4.0.1

### Python version

3.9

**Comment by joaander** [comment]
I am not able to reproduce this with clang 16.0.0 in Ubuntu 23.04: https://github.com/glotzerlab/hoomd-blue/actions/runs/5657214958/job/15325797221?pr=1593#step:6:13

Feel free to make a pull request that fixes this.

**Comment by yurivict** [comment]
This might also depend on the C++ library that is used.

How can I fix it? The feature should be removed and replaced. I don't know what it is used for in your project.

**Comment by joaander** [comment]
Per https://stackoverflow.com/a/63577511, you would remove the unnecessary use of `std::unary_function` as a base class everywhere it is used. Then test that HOOMD-blue compiles as expected.

**Comment by tcmoore3** [comment]
I see this error now after updating to the latest Apple command line tools (version 15.0.0.0.1.1694021235) on an M2 mac. The fix in the linked SO post raises a different error that I'll need help debugging.
