### ISSUE TITLE
Slow compression in HPMC simulations.

### ISSUE THREAD

**Issue by joaander** [glotzerlab/hoomd-blue#1641]
### Description

Add a method that slowly compresses in HPMC simulations.

### Proposed solution

Either implement `SlowCompress` or add optional arguments to `QuickCompress`. In either case, apply the `QuickCompress` algorithm to a variable box size.

### Additional context

`QuickCompress` works extremely well, but always quenches to the chosen box size. Some simulation workflows require slow annealing. MD simulations can use `BoxResize`. HPMC simulations need an alternate method that accounts for particle overlaps.

**Comment by joaander** [comment]
@tcmoore3 you asked about this once. Would you be interested in implementing it?

**Comment by tcmoore3** [comment]
I am interested, but since I don't have a research need for this at the moment I cannot commit to implementing it.

**Comment by tcmoore3** [comment]
Now that I'm thinking about it, it should be fairly straightforward. Unless I'm missing something, shouldn't this consist of adding a variant to `UpdaterQuickCompress` and using that variant to compute the new box in `UpdaterQuickCompress::getNewBox` by modifying the minimum scale factor?

**Comment by joaander** [comment]
Yes, we can replace `target_box` with a box that varies over time. Work on this should wait pending the outcome of #1640 where I am suggesting a new `BoxVariant` API.

**Comment by joaander** [comment]
Now that #1685 is merged, we make `target_box` a `BoxVariant` in `QuickCompress`. @tcmoore3 do you plan to implement this? I would like to put it in the next release.

**Comment by tcmoore3** [comment]
I'm not sure why GitHub didn't automatically close this when #1736 was merged, but #1736  resolves this issue.

**Comment by joaander** [comment]
> I'm not sure why GitHub didn't automatically close this when #1736 was merged, but #1736 resolves this issue.

GitHub automatically closes issues only when a pull request is merged into the default branch (`trunk-patch`).
