### ISSUE TITLE
How to implement a polymer in hoomd 2.9.6

### ISSUE THREAD

**Issue by DavidGomez82** [glotzerlab/hoomd-blue#1766]
I'm a beginner in hoomd and started using the version 2.9.6. I want to implement a polymer using the following code:
hoomd.init.create_random_polymers(box=data.boxdim(L=31),
                            polymers=[polymer2],
                            separation=dict(B=0.35), seed=52);

but I get the following error:

AttributeError: module 'hoomd.init' has no attribute 'create_random_polymers'

How can I solve this issue? Thank you so much

**Comment by joaander** [comment]
HOOMD-blue 2.9.6 is no longer supported.
