### ISSUE TITLE
Add contraction-expansion geometry for MPCD

### ISSUE THREAD

**Issue by tzortziskoul** [glotzerlab/hoomd-blue#1775]
### Description

We want to implement a new channel for mpcd streaming geometry in hoomd v4. It will be a constriction-expansion channel described by two cosines.

### Proposed solution

The new geometry will be implemented as follows:
```
channel = hoomd.mpcd.geometry.CosineExpansionContraction(...)
hoomd.mpcd.stream.BounceBack(period=..., geometry=channel)
```

### Additional context

We already have a plugin that implements some of the necessary infrastructure for hoomd v2, which we will port to hoomd v4. A similar issue will be opened for the symmetric wavy channel.

**Comment by mphoward** [comment]
I have discussed this with @tzortziskoul and @astatt, and we will support them in implementing this feature.

**Comment by mphoward** [comment]
Completed in #1836
