### ISSUE TITLE
List modules at the top of the documentation.

### ISSUE THREAD

**Issue by joaander** [glotzerlab/hoomd-blue#1857]
### Description

Move the "Modules" section of the documentation to the top.

### Motivation and context

This would make pages like https://hoomd-blue.readthedocs.io/en/v4.8.1/module-hoomd-variant-box.html easier to discover.

**Comment by Brijeshthummar02** [comment]
@joaander can you show me the path for the repo.

**Comment by joaander** [comment]
> @joaander can you show me the path for the repo.

https://github.com/glotzerlab/hoomd-blue/

**Comment by joaander** [comment]
Will be addressed by #1914.
