### ISSUE TITLE
Incorrect Pybind Version in `install-prereq-headers.py` Script

### ISSUE THREAD

**Issue by pietro-sillano** [glotzerlab/hoomd-blue#1910]
Hello,

I’m compiling HooMD from source on an HPC cluster, and I encountered a potential issue.

I followed the installation guide using a Python virtual environment and ran the `install-prereq-headers.py` script. Since my environment didn’t have Pybind configured, the script prompted me to install it. However, the script downloaded Pybind version 2.10.1 instead of the required version 2.12 for HooMD.

I recommend updating the script (specifically around line 220) to reference the correct Pybind version (2.12).

Thanks!

### Platform

Linux

### Installation method

Compiled from source

### HOOMD-blue version

4.8.3

### Python version

3.10.12

**Comment by joaander** [comment]
I recently revised the build documentation and removed `install-prereq-headers.py`: #1909
