### ISSUE TITLE
MPCD Taylor Couette Virtual Particle Filler for GPU import missing 

### ISSUE THREAD

**Issue by astatt** [glotzerlab/hoomd-blue#1933]
### Description

With the new Taylor Couette Geometry (`ConcentricCylinders`) for MPCD, it appears that some import statements for the virtual particle filler are missing on the GPU in the `mpcd/module.cc` file. Additionally, there might be performance issues as well, which require further investigation. 

**Suggested fix:** 
Add the following import statements to `mpcd/module.cc` : 

```
void export_ConcentricCylindersGeometryFillerGPU(pybind11::module&); 
export_ConcentricCylindersGeometryFillerGPU(m);
```

### Script

```python
import numpy as np
import hoomd
import gsd, gsd.hoomd

density = 10  # density
L= 10 # box size

device = hoomd.device.GPU()

simulation = hoomd.Simulation(device=device, seed=1)

frame = gsd.hoomd.Frame()
frame.particles.types = ['A']
frame.configuration.box = [L,L,L, 0, 0, 0]
frame.particles.N = 0

simulation.create_state_from_snapshot(frame)

snapshot  = simulation.state.get_snapshot()

Nmpcd = int(np.round(density*L**3))

pos = np.random.uniform(-L/2.,+L/2.,size=(Nmpcd,3))
snapshot.mpcd.types = ['A','W']
snapshot.mpcd.N = len(pos)
snapshot.mpcd.position[:] = pos

simulation.state.set_snapshot(snapshot)

cylinders = hoomd.mpcd.geometry.ConcentricCylinders(inner_radius=1,
                                                        outer_radius=4)

stream = hoomd.mpcd.stream.BounceBack(period=20, geometry=cylinders)
collide = hoomd.mpcd.collide.StochasticRotationDynamics(period=20,angle=130,kT=1.0)
filler = hoomd.mpcd.fill.GeometryFiller(type="W",
                                             density=density,
                                             kT=1.0,
                                             geometry=cylinders)

integrator = hoomd.mpcd.Integrator(
    dt=0.005,
    streaming_method=stream,
    collision_method=collide,
    virtual_particle_fillers=[filler],
    mpcd_particle_sorter=hoomd.mpcd.tune.ParticleSorter(trigger=400))

simulation.operations.integrator = integrator

simulation.run(1)
```

### Output

```shell
Traceback (most recent call last):
  File "/projects/bbhc/statt/MPCD_TC_test/test.py", line 52, in <module>
    simulation.run(1)
  File "/u/statt/.conda/envs/utilities/lib/python3.10/site-packages/hoomd/simulation.py", line 555, in run
    self.operations._schedule()
  File "/u/statt/.conda/envs/utilities/lib/python3.10/site-packages/hoomd/operations.py", line 211, in _schedule
    self.integrator._attach(sim)
  File "/u/statt/.conda/envs/utilities/lib/python3.10/site-packages/hoomd/operation.py", line 315, in _attach
    self._attach_hook()
  File "/u/statt/.conda/envs/utilities/lib/python3.10/site-packages/hoomd/mpcd/integrate.py", line 241, in _attach_hook
    self._virtual_particle_fillers._sync(self._simulation,
  File "/u/statt/.conda/envs/utilities/lib/python3.10/site-packages/hoomd/data/syncedlist.py", line 246, in _sync
    raise err
  File "/u/statt/.conda/envs/utilities/lib/python3.10/site-packages/hoomd/data/syncedlist.py", line 242, in _sync
    self._register_item(item)
  File "/u/statt/.conda/envs/utilities/lib/python3.10/site-packages/hoomd/data/syncedlist.py", line 190, in _register_item
    value._attach(self._simulation)
  File "/u/statt/.conda/envs/utilities/lib/python3.10/site-packages/hoomd/operation.py", line 315, in _attach
    self._attach_hook()
  File "/u/statt/.conda/envs/utilities/lib/python3.10/site-packages/hoomd/mpcd/fill.py", line 152, in _attach_hook
    assert class_ is not None, ("Virtual particle filler for geometry "
AssertionError: Virtual particle filler for geometry not found
```

### Expected output

Nothing, simulation should run. It does work on the CPU.

### Platform

GPU

### Installation method

Compiled from source

### HOOMD-blue version

4.9.1 (trunk-minor, commit a86cbe76426)

### Python version

3.10

**Comment by astatt** [comment]
Additionally, we should have a unit test that checks for the existence of the virtual particle filler method for all geometries.

**Comment by mphoward** [comment]
Thanks @astatt ! You are correct that these lines need to be added to `module.cc`. This error should have been caught by this unit test:

https://github.com/glotzerlab/hoomd-blue/blob/ec0b84cdf49987f9d6fdd5d1f6d4bfa216edbfc7/hoomd/mpcd/pytest/test_fill.py#L51

but unfortunately was not because we missed adding the class to that list.

This is a quick fix, but we will investigate separately if there are performance issues as well. I assume this means you think the GPU code path is not being taken correctly for some virtual particle fillers?

@jinnyjc can you please create a branch based off `trunk-patch` to add these missing bits to `module.cc` and `test_fill.py` and open a PR? Make sure to sync `trunk-patch` in your fork and locally before you do so. Thanks!

**Comment by astatt** [comment]
@mphoward Yes - my suspicion is that a part of the virtual particle filler is not executed on the GPU. In the exact same system, I observe a drop from ~ 900TPS with no filler to 9TPS with filler. 9TPS is identical to the performance of the CPU. I can't spot something obviously wrong, so I suspect some function accidentally being not inherited correctly.
