### ISSUE TITLE
Support for LLVM >= 17

### ISSUE THREAD

**Issue by Crivella** [glotzerlab/hoomd-blue#1963]
### Description

Allow HOOMD-blue to compile against LLVM versions >= 17.

### Proposed solution

It seems that several symbols in use by HOOMD-blue have been replaced in LLVM >= 17 (https://github.com/llvm/llvm-project/commit/8b1771bd9f304be39d4dcbdcccedb6d3bcd18200)

I've tried compiling the latest version (4.9.1) building against `libLLVM.so` from LLVM 19.1.1, but encountered errors of the type 

```
In file included from /home/crivella/.local/easybuild/build/HOOMDblue/4.9.1/foss-2024a/hoomd-4.9.1/hoomd/hpmc/EvalFactory.h:11,
                from /home/crivella/.local/easybuild/build/HOOMDblue/4.9.1/foss-2024a/hoomd-4.9.1/hoomd/hpmc/PatchEnergyJIT.h:13,
                from /home/crivella/.local/easybuild/build/HOOMDblue/4.9.1/foss-2024a/hoomd-4.9.1/hoomd/hpmc/PatchEnergyJIT.cc:4:
/home/crivella/.local/easybuild/build/HOOMDblue/4.9.1/foss-2024a/hoomd-4.9.1/hoomd/hpmc/KaleidoscopeJIT.h: In member function llvm::Expected<llvm::JITEvaluatedSymbol> llvm::orc::KaleidoscopeJIT::findSymbol(std::string):
/home/crivella/.local/easybuild/build/HOOMDblue/4.9.1/foss-2024a/hoomd-4.9.1/hoomd/hpmc/KaleidoscopeJIT.h:134:26: error: could not convert llvm::orc::ExecutionSession::lookup(llvm::ArrayRef<llvm::orc::JITDylib*>, llvm::orc::SymbolStringPtr, llvm::orc::SymbolState)(llvm::ArrayRef<llvm::orc::JITDylib*>(const std::initializer_list<llvm::orc::JITDylib*>{((llvm::orc::JITDylib* const*)(& llvm::orc::JITDylib* const [1]{(&((llvm::orc::KaleidoscopeJIT*)this)->llvm::orc::KaleidoscopeJIT::mainJD)})), 1}), llvm::orc::MangleAndInterner::operator()(llvm::StringRef)(llvm::StringRef(Name)), llvm::orc::SymbolState::Ready) from Expected<llvm::orc::ExecutorSymbolDef> to Expected<llvm::JITEvaluatedSymbol>
  134 |         return ES->lookup({&mainJD}, Mangle(Name));
      |                ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
      |                          |
      |                          Expected<llvm::orc::ExecutorSymbolDef>
```

Naively applying the following replacement in `hoomd/hpmc/KaleidoscopeJIT.h`:

- `JITEvaluatedSymbol` -> `ExecutorSymbolDef`
- `JITTargetAddress` -> `ExecutorAddr`

Results in the compilation proceeding further but than stopping with errors of the type:

```
invalid cast from type const llvm::orc::ExecutorAddr to type float**
```

I am not sure if more type replacement will be enough to enable hoomd + LLVM to work or if more involved changes will be required related to how the JIT is implemented.

See also a related issue: https://github.com/easybuilders/easybuild-easyconfigs/issues/21960

**Comment by joaander** [comment]
Using LLVM for code generation in HOOMD-blue has been deprecated since 4.5.0 is is now removed in (the just released) 5.0.0. You can copy and paste code you previously used into a [template repository](https://github.com/glotzerlab/hpmc-energy-template/), then configure with cmake and build.
