### ISSUE TITLE
Package on Spack

### ISSUE THREAD

**Issue by physkets** [glotzerlab/hoomd-blue#1973]
### Description

A lot of HPC software is available on Spack ( https://spack.io/ ) making it the defacto package management system in a lot of scenarios.

### Proposed solution

It would be very helpful if HOOMD-blue was also made available there.

Has this been considered? I see that an old version (2.2.2) is available, but not any of the newer ones.

**Comment by tgamblin** [comment]
Note that this is already in Spack: https://packages.spack.io/package.html?name=hoomd-blue

Thanks to these folks:
<img width="701" alt="Screenshot 2024-12-20 at 9 30 14 AM" src="https://github.com/user-attachments/assets/7bf224c4-d10d-48e9-9651-11f51fc9b256" />

You can submit a pull request adding more recent versions by modifying this part of the package to include newer releases:
* https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/hoomd-blue/package.py#L26-L36

**Comment by joaander** [comment]
I maintain the conda-forge hoomd package (https://github.com/conda-forge/hoomd-feedstock/) and a set of scripts to help build conda packages with HPC administrator-provided CUDA and MPI libraries (https://github.com/glotzerlab/software/). I have no plans to maintain a spack script as well. You are welcome to contribute changes to the spack project directly.
