### ISSUE TITLE
Use 64-bit time step counters

### ISSUE THREAD

**Issue by joaander** [glotzerlab/hoomd-blue#229]
**[Original report](https://bitbucket.org/glotzer/hoomd-blue/issue/229) by me.**

----------------------------------------

* There are many "unsinged int timestep" and "unsigned int m_timestep" phrases in the code that can be bulk replaced.
* System.h and System.cc will need a read-through to find all instances where it stores a timestep like variable in an unsinged int (even temporarily in a delta).
* Special care must be taken in DPD and anywhere else that uses the current timestep in a Saru RNG - the easiest thing to do is cast out the lower 32 bits of the number and use that for the seed, though that will make RNGs repeat every ~4 billion steps. Alternately, one could mix the higher 32 bits into one of the other seed entries.
* the gsd file format already stores time step as a uint64_t, so no changes are needed there.

**Comment by joaander** [comment]
We will implement this in v3.0.

Questions: The DCD file format cannot represent 64-bit timestep counters. Should we remove DCD, let the counter wrap around, or error when attempting to write an invalid step to DCD?

Aside: DCD can also only represent fixed periods and the new `Trigger` API in HOOMD will make it even easier for users to use non-fixed period outputs.

**Comment by mphoward** [comment]
I think we should keep supporting DCD because users of other simulation packages casually trying or transitioning to HOOMD might prefer having this file format for their other tools.

I would error out if the timestep exceeds the DCD spec. This can be clearly documented, and the user should decide how they want to handle longer runs (reset the step, create a new file, etc.)

**Comment by vyasr** [comment]
I agree with @mphoward, removing DCD would probably alienate significant portions of our user base. There's no need to improve its support, just to keep it where it is now.
