### ISSUE TITLE
Write a unit test for GPU shapes that use ManagedArray

### ISSUE THREAD

**Issue by joaander** [glotzerlab/hoomd-blue#276]
**[Original report](https://bitbucket.org/glotzer/hoomd-blue/issue/276) by Jens Glaser (Bitbucket: [jens_glaser](https://bitbucket.org/jens_glaser), GitHub: [jglaser](https://github.com/jglaser)).**

----------------------------------------

Such as convex polyhedron. The test should run for a few thousand steps,
and then check for zero overlaps. This makes sure a regression like the one
fixed in pull request #395 doesn't sneak in again.

**Comment by bdice** [comment]
@jglaser Is this still relevant? If so, could you define the scope of this and determine whether it would make a good hackathon project?
