### ISSUE TITLE
Improve performance of tree neighbor lists

### ISSUE THREAD

**Issue by joaander** [glotzerlab/hoomd-blue#286]
**[Original report](https://bitbucket.org/glotzer/hoomd-blue/issue/286) by Michael Howard (Bitbucket: [mphoward](https://bitbucket.org/mphoward), GitHub: [mphoward](https://github.com/mphoward)).**

----------------------------------------

`nlist.tree` is slower than `nlist.cell` for certain simulations, especially standard things like the Lennard-Jones fluid. We are trying to optimize tree building / traversal and particle distance checks to boost the performance of `nlist.tree`.

1. Pull the LBVH tree out of `NeighborListGPUTree` to compartmentalize some of the tree operations and to make optimization easier.

2. Improve the way that particles are grouped into leaf nodes in the tree. Reduce the number of required traversals.

3. Vectorize the particle distance checks from the leaf nodes, and try to use shared memory when possible.

I have an undergrad student working on this. I am planning to polish off the code depending on how successful the above optimizations are and how far he gets. Tentatively, this could be completed by Spring 2018, and so I'm targeting for version 2.4 now.

**Comment by joaander** [comment]
@mphoward What release should we target for improving the tree neighbor lists?

**Comment by mphoward** [comment]
@joaander Do you have tentative release dates for 2.7 and 3.0? I am working on a project now where I would like to use them, so I think I will have time for it this month, next at latest.
