### ISSUE TITLE
hoomd.group.all prints script when newline is present

### ISSUE THREAD

**Issue by joaander** [glotzerlab/hoomd-blue#297]
**[Original report](https://bitbucket.org/glotzer/hoomd-blue/issue/297) by Vyas Ramasubramani (Bitbucket: [vramasub](https://bitbucket.org/vramasub), GitHub: [vyasr](https://github.com/vyasr)).**

----------------------------------------

When `hoomd.group.all()` is called with a newline between parentheses, it results in printing out the entire script. I can reproduce this on our vislab linux machines with the following script.

````
#!/usr/bin/python
import hoomd
from hoomd import hpmc
hoomd.context.initialize('--mode=cpu')
system = hoomd.init.create_lattice(
        hoomd.lattice.sc(1), 1)
mc = hpmc.integrate.sphere(seed=int(3018423), d = 0.1)
mc.shape_param.set("A", diameter = 1)
gsd = hoomd.dump.gsd(
    filename='test.gsd', group=hoomd.group.all(
        ), period=1, phase=0)
````

The problem goes away if the newline inside `group.all()` is removed. The issue can be seen by diffing the output of these options (undesirable output on the left):

````
< operations.py:000  |  #!/usr/bin/python
< import hoomd
< from hoomd import hpmc
< hoomd.context.initialize('--mode=cpu')
< system = hoomd.init.create_lattice(
<         hoomd.lattice.sc(1), 1)
< mc = hpmc.integrate.sphere(seed=int(3018423), d = 0.1)
< mc.shape_param.set("A", diameter = 1)
< gsd = hoomd.dump.gsd(
<     filename='test.gsd', group=hoomd.group.all(
37,38c27,29
<     filename='test.gsd', group=hoomd.group.all(
<         ), period=1, phase=0)
---
>     filename='test.gsd', group=hoomd.group.all(), period=1, phase=0)
> operations.py:009  |  gsd = hoomd.dump.gsd(
>     filename='test.gsd', group=hoomd.group.all(), period=1, phase=0)
````
On the right, it prints the usual hoomd output indicating the script, the line number, and the HOOMD function call. On the left, it instead outputs the script with line 0 and then proceeds to dump the entire script.

**Comment by bdice** [comment]
This should be re-tested with Python 3.7. One possible solution (untested) would be to change the scan upward from the opening parenthesis. If the scan reaches the top of the file without finding a balancing parenthesis, then try to start the scan from the next line down.

This is the function to inspect. https://github.com/glotzerlab/hoomd-blue/blob/maint/hoomd/util.py#L61

**Comment by joaander** [comment]
Solution: Remove `print_status_line` entirely.
