### ISSUE TITLE
HOOMD crashes when no rigid body parameters are set, but central particles exist

### ISSUE THREAD

**Issue by joaander** [glotzerlab/hoomd-blue#311]
**[Original report](https://bitbucket.org/glotzer/hoomd-blue/issue/311) by Jens Glaser (Bitbucket: [jens_glaser](https://bitbucket.org/jens_glaser), GitHub: [jglaser](https://github.com/jglaser)).**

----------------------------------------

The bug occurs after `run()` when `md.constrain.rigid()` is constructed without a call to `set_param()`. Alyssa Travitz reported this, and it doesn't even really 'crash' it just plain exits with errorcode 0.

**Comment by bdice** [comment]
@jglaser If you know more information about this or how to solve it, could you write some more detail here? Thanks!

**Comment by joaander** [comment]
I believe this issue is no longer present in v3.0 as the parameters are validated at the python level.
