### ISSUE TITLE
restore_state in HPMC fails to throw an error when state information is missing in the GSD file

### ISSUE THREAD

**Issue by joaander** [glotzerlab/hoomd-blue#326]
**[Original report](https://bitbucket.org/glotzer/hoomd-blue/issue/326) by me.**

----------------------------------------

It should be an error to restore state that doesn't exist.

**Comment by bdice** [comment]
In the lines like this one, we need to throw an error if the `readChunk` returns `false`. This indicates the chunk is not present. The same pattern is repeated for several HPMC integrators.
https://github.com/glotzerlab/hoomd-blue/blob/f5a7e6ae59eaa7ce01214d460a43e78543463d65/hoomd/hpmc/GSDHPMCSchema.h#L122
