### ISSUE TITLE
PPPM Energy not excluding properly

### ISSUE THREAD

**Issue by joaander** [glotzerlab/hoomd-blue#328]
**[Original report](https://bitbucket.org/glotzer/hoomd-blue/issue/328) by Bradley Dice (Bitbucket: [bdice](https://bitbucket.org/bdice), GitHub: [bdice](https://github.com/bdice)).**

----------------------------------------

I was working with @jglaser and @csadorf when we discovered that the PPPM energy reported in the log may not be accounting for exclusions. @jglaser, can you clarify the problem? I can make a minimal script to reproduce the discrepancy if needed.

**Comment by bdice** [comment]
Self-assigning this task to make a minimal example to reproduce the bug.

**Comment by bdice** [comment]
Possible starting point: https://github.com/glotzerlab/hoomd-blue/blob/f5a7e6ae59eaa7ce01214d460a43e78543463d65/hoomd/md/PPPMForceCompute.cc#L1599

**Comment by ahy3nz** [comment]
I'm interested in this issue as I'm trying to validate whether or not atomistic molecular models are getting translated to hoomd from mbuild/parmed properly

**Comment by vyasr** [comment]
Copying my comment from the relevant Slack thread:
> offhand, it looks like there's a fixExclusions method that is called in computeForces that subtracts off the energy of the excluded interactions, but no similar call in computePE (which is is used to compute the logged quantity)
> This is a not uncommon problem in parts of hoomd where the log quantity is computed by a separate function because the main logic is directly embedded in computeForces which we don't want to call. Adding an extra layer of abstraction there to minimize the duplication would be nice and I've thought that before, but have done minimal research to know what the pitfalls are
