### ISSUE TITLE
map_overlaps() should return the full overlap matrix

### ISSUE THREAD

**Issue by joaander** [glotzerlab/hoomd-blue#334]
**[Original report](https://bitbucket.org/glotzer/hoomd-blue/issue/334) by Jens Glaser (Bitbucket: [jens_glaser](https://bitbucket.org/jens_glaser), GitHub: [jglaser](https://github.com/jglaser)).**

----------------------------------------

currently it returns a matrix with only the upper diagonal matrix filled

**Comment by bdice** [comment]
@jglaser Can you elaborate on the intended use case for this? Would it be an appropriate hackathon project?

**Comment by joaander** [comment]
Not enough information.
