### ISSUE TITLE
system.restore_snapshot() should check that the number of types stays constant

### ISSUE THREAD

**Issue by joaander** [glotzerlab/hoomd-blue#335]
**[Original report](https://bitbucket.org/glotzer/hoomd-blue/issue/335) by Jens Glaser (Bitbucket: [jens_glaser](https://bitbucket.org/jens_glaser), GitHub: [jglaser](https://github.com/jglaser)).**

----------------------------------------

Otherwise all kinds of unchecked situations can occur, e.g. seg faults

**Comment by lyrivera** [comment]
@joaander Can you provide a brief description of what needs to be done? I hardly remember what we discussed last time.
