### ISSUE TITLE
FindCUDA prefers static CUDA libraries

### ISSUE THREAD

**Issue by jglaser** [glotzerlab/hoomd-blue#357]
Reported by @AdamSimpson 

```OpenMPI/4.0.0 has deprecated OpenIB in favor of UCX.  When building HOOMD-Blue CMake prefers the static cudart libraries by default, which causes an issue with UCX. Memory hooks can be disabled as noted in the issue or HOOMD-Blue can be configured with "-DCUDA_USE_STATIC_CUDA_RUNTIME=OFF```

We should force FindCUDA to use shared libraries.

**Comment by joaander** [comment]
Complete with #381 .

**Comment by joaander** [comment]
Complete in #419
