### ISSUE TITLE
Implement "Sphinx Union" on HPMC

### ISSUE THREAD

**Issue by lsmin1151** [glotzerlab/hoomd-blue#362]

**Comment by joaander** [comment]
@lsmin1151 @thiv89 do you plan to submit a PR for this?

**Comment by lyrivera** [comment]
@lsmin1151 @thiv89 @joaander if further development is required I'd be happy to help.

**Comment by lsmin1151** [comment]
Oh, I am sorry @joaander @thiv89. I've forgotten this work for a while... 
Thanks @lyrivera ! I am still not familiar with the workflow of GIT, so if you have about 15 min before tomorrow literature review, can I ask some question on this?

**Comment by lyrivera** [comment]
@lsmin1151 Sure. Which branch are you working on? I don't see any branch with `sphinx` in its name. Perhaps you have it locally on your machine? If so, can you push it?

**Comment by lsmin1151** [comment]
@lyrivera Thank you! I am not sure I did correctly, I just made a branch 'sphinx_union' and did "git push --all". Can you see the new branch?

**Comment by lyrivera** [comment]
@lsmin1151 Yes. Thanks.
