### ISSUE TITLE
Include orientable attribute in HPMC sphere integrator state

### ISSUE THREAD

**Issue by lyrivera** [glotzerlab/hoomd-blue#363]
## Description
 
The HPMC sphere integrator does not store the ```orientable``` attribute of the particles as part of its state. Therefore, restoring the integrator state from a GSD file results in said attribute to be set to ```False``` always, as seen below
```c++
for(unsigned int i = 0; i < Ntypes; i++)
            {
            shape[i].radius = data[i];
            shape[i].isOriented = false;
            shape[i].ignore = 0;
            }
```
Obviously, this leads to wrong behavior in case of anisotropic patch interactions.

## Developer
Luis Y. Rivera-Rivera

**Comment by joaander** [comment]
Before this can be implemented in HOOMD, the necessary fields need to be added to the GSD HOOMD specification: https://gsd.readthedocs.io/en/stable/schema-hoomd.html#state-data

**Comment by lyrivera** [comment]
Thanks. I'll work on it.
