### ISSUE TITLE
CUDA with first-class CMake support

### ISSUE THREAD

**Issue by mphoward** [glotzerlab/hoomd-blue#381]
## Description

Since CMake 3.8, CUDA has been supported as a "first-class" language. In principle, this means that you can simply specify the files for the target, set their properties with some simple syntax, and then it will automatically use the appropriate compiler. FindCUDA was deprecated in CMake 3.10, and the current version is CMake 3.14. At some point, it would probably be a good idea to bump the minimum version of CMake and take advantage of these more powerful capabilities.

The downside is that we have increased the minimum CMake version. Is this acceptable for most computing centers / build environments?

## Proposed solution

The CMake build system, at least as it relates to CUDA, needs a pretty substantial overhaul.

## Additional context

https://devblogs.nvidia.com/building-cuda-applications-cmake/

## Developer

Not at this time, but I can help as needed.

**Comment by joaander** [comment]
ubuntu18.04 includes cmake 3.10, so requiring this seems reasonable

**Comment by joaander** [comment]
Complete in #419
