### ISSUE TITLE
Release version info missing

### ISSUE THREAD

**Issue by YaohuaLi-Phy** [glotzerlab/hoomd-blue#384]
## Description

I don't know if this is the right place, but the log of changes for each release on the hoomd download page is missing (http://glotzerlab.engin.umich.edu/hoomd-blue/download.html), it returns a 404 error.

## Script

```python
# Include a minimal script that reproduces the problem

```

## Configuration

Platform:
- Mac
- Linux
- GPU
- CPU

Installation method:
- Conda package
- Compiled from source
- glotzerlab-software container

Versions:
- Python version: ?.?.?
- **HOOMD-blue** version: ?.?.?

**Comment by joaander** [comment]
Thank you for reporting. I have fixed the broken link.
