### ISSUE TITLE
Split HPMC integrators into packages

### ISSUE THREAD

**Issue by joaander** [glotzerlab/hoomd-blue#400]
## Description

Simplify the HPMC integrator implementation, documentation, and user API.

## Proposed solution

Instead of choosing the integration mode via parameters to the integrator, provide different packages. `lmc` for local monte carlo, `implicit_depletant` for implicit depletants, etc...
```
hpmc.lmc.convex_polyhedron(...)
hpmc.implicit_depletant.sphere()
```

## Additional context

This allows more natural expansion as we add additional integration modes. It also more clearly documents which shape classes are available in which mode and what parameters are specific to that mode.

**Comment by jglaser** [comment]
With #505 the HPMC integrators for LMC and LMC with depletants are unified on the C++ level. However, we can still decide not to support depletant related options on the python level in other, future integrators.

**Comment by joaander** [comment]
With that refactor, we no longer need to separate out implicit.
