### ISSUE TITLE
can hoomd record atom id and molecule id?

### ISSUE THREAD

**Issue by Roy-Kid** [glotzerlab/hoomd-blue#411]
## Description

Here is the situation. When i plot or compute some parameter from hoomd, i always need to identify A molecule or some atoms. Due to my model is generated by other program, so sometimes i dont now exactly the range of atoms index of molecule so it takes me a lot time to figure out. I personally consider that it may batter to add atom id and molecule id to hoomd system and gsd file, to make the both data structure and data topo info more clearly. 

## Proposed solution

GSD use order list(array) to store position, type and mass are correspond one by one in order. I think it is easy to add a section in this way to seperately store id. like:
```
<position>
1.23  4.24 5.63
1.56  6.23 6.44
</position>
<type>
A
B
</type>
<atom_id>
1
2
</atom_id>
<mol_id>
1
1
</mol_id>

## Developer

If you think this issue has a little valuable and worth improving, maybe i can try my best to do this under your help

**Comment by joaander** [comment]
Use the values -2, -3, ... in the [body field](https://gsd.readthedocs.io/en/stable/schema-hoomd.html#chunk-particles/body). These values will only modify the simulation if you enable [nlist body exclusions](https://hoomd-blue.readthedocs.io/en/latest/module-md-nlist.html)
