### ISSUE TITLE
Allow HPMC with depletants in NPT ensemble

### ISSUE THREAD

**Issue by jglaser** [glotzerlab/hoomd-blue#412]
## Description

We should allow using depletants as a multi-body potential, without the grand-canonical aspect for the box resize moves (which would result in an unstable ensemble).

## Proposed solution

Provide an option to disable the pressure contribution of depletants in `update.muvt()`, implement a box resize criterion with random depletant insertion to check for depletant-generated overlaps.

## Additional context

This came up in the discussion of #403 

## Developer

I might be, but if anyone else wants to volunteer.... @tcmoore3 @vyasr

**Comment by vyasr** [comment]
I follow how you would convert this to a canonical ensemble, but how would you impose the potential? The behavior of depletants for non-box moves should be unchanged, what would be the Boltzmann factor computed for box resizes based on this potential?

**Comment by jglaser** [comment]
> I follow how you would convert this to a canonical ensemble, but how would you impose the potential? The behavior of depletants for non-box moves should be unchanged, what would be the Boltzmann factor computed for box resizes based on this potential?

It could either be based on inserting depletants in the free volume, or on inserting in the overlap volume. Both approaches would lead to slightly different code. There already is an example of the former kind in `UpdaterMuVT.h` (`boxResizeAndScale`). It would suffice if that one was slightly adapted and moved into the `attemptBoxResize` method in `IntegratorHPMCMono.h`.
