### ISSUE TITLE
provide python API for recent TPS during the simulation

### ISSUE THREAD

**Issue by zhou-pj** [glotzerlab/hoomd-blue#418]
## Description

Provide python API for recent TPS during the simulation

## Proposed solution

Change hoomd.context.current.system.getLastTPS() to update TPS every period instead of just at the end of run.

**Comment by joaander** [comment]
Feel free to submit a PR, this would take one line of code to implement. A few more are needed if you also opt to provide a documented python API call to query TPS.

**Comment by joaander** [comment]
@zhou-pj @csadorf - are either of you interested in implementing this?

**Comment by csadorf** [comment]
I could give it a shot. What is the expected timeline?

**Comment by joaander** [comment]
I expect this feature will only require a few hours to develop.

**Comment by csadorf** [comment]
> I expect this feature will only require a few hours to develop.

I rather meant, by *when* would you expect this to be done?

**Comment by joaander** [comment]
> I rather meant, by _when_ would you expect this to be done?

I have no expectation. When do the relevant stakeholders (@zhou-pj @csadorf) need it completed by?

**Comment by mikemhenry** [comment]
I'm happy to submit a PR for this, I was thinking of a different implementation where the `run` or the `run_upto` would return a float that is the average TPS, thoughts?

**Comment by joaander** [comment]
I don't think `run` should return the TPS. `run` is a command that modifies the state of the system. In v3, `run` will be a method of the Context object. If anything, `run` should return the Context object to reflect that it produced a context with new state and support method chaining.

Instantaneous and average TPS should be properties of the context (``SimulationContext``) in 2.x.

Both instantaneous and average TPS can be implemented in the same PR. Making instantaneous TPS available requires adding a few lines
https://github.com/glotzerlab/hoomd-blue/blob/4c68b26cb787b65bb41359164524dc7d9694d001/hoomd/System.cc#L629-L635
 to `generateStatusLine`:
https://github.com/glotzerlab/hoomd-blue/blob/4c68b26cb787b65bb41359164524dc7d9694d001/hoomd/System.cc#L840-L845

Do you need average TPS over the entire run? That will require some additional logic at the start and end of `System::run` to compute the overall average.

There is currently no user-facing way to get TPS (other than `benchmark.series`). Both of these will need 1-line (+ docstring) properties added to the `SimulationContext` object that call the underlying C++ method on `System`.

**Comment by joaander** [comment]
After looking at the code, I realized that I made some incorrect assumptions.
1. `m_last_TPS` (returned by `getLastTPS()`) *is* the average TPS over the whole run
2. `m_cur_tps` is the instantaneous TPS, and is already set.

So the average TPS property can simply return the result of `context.system.getLastTPS()`. Implementing instantaneous TPS requires adding a new `getCurTPS()` method that returns `m_cur_tps`.

**Comment by mikemhenry** [comment]
Okay I will take a stab at implementing `context.system.getLastTPS()`.
Thanks!

**Comment by mikemhenry** [comment]
Okay so `context.system.getLastTPS()` actually does what I need it to, so sorry for hijacking this issue.

**Comment by joaander** [comment]
Except that `context.system.getLastTPS()` accesses a C++ API which is undocumented at the user level. To resolve both issues with a documented user API, we need to:
1. Add `System::getCurTPS()`
2. Add and document the property `SimulationContext.tps` (returning `getCurTPS`)
3. Add and document the property `SimulationContext.avg_tps` (returning `getLastTPS`)

**Comment by mikemhenry** [comment]
Yes this should be documented! I will attempt to figure it out.

**Comment by joaander** [comment]
We will implement this as part of #395

**Comment by joaander** [comment]
@b-butler suggested that we could provide a full list of all TPS samples taken during the run. We could also allow the user to set the update rate. To avoid infinite memory usage, we could limit it to the most recent N samples. We could make this limit unnecessary by limiting the update rate to be no more than 1/second.

Users could then use that list to look at performance over time. The API should also provide a simple way to access the most recent sample as well. I don't see a need for Simulation to provide an average TPS, users can always average the list if they wish.

Given this script:
```
s = Simulation()
# setup
s.run(1000)
s.run(1000)
some_long_operation_outside_hoomd()  # takes 100 seconds
s.run(1000)
print(s.tps_list)
```
Should the output only cover the last 1000 steps? Or should it include all samples since the creation of the `s`? If it should include all time, then there will be missing samples while the non-hoomd long operation takes place and the first sample after that will be very small. Does this matter to the user? To get the best accuracy at the cost of more complexity for the user to analyze, should we instead provide the user with a list of (timestamp, timestep) tuples?

**Comment by b-butler** [comment]
I think it is reasonable to reset this at the beginning of a run command.

**Comment by joaander** [comment]
`Simulation` now provides a `tps` property. We plan to make this loggable in #797
