### ISSUE TITLE
hoomd.group unit test fails without md

### ISSUE THREAD

**Issue by mphoward** [glotzerlab/hoomd-blue#421]
## Description

The `hoomd.group` python unit tests import the md module, breaking the isolation of `hoomd` from subcomponents. (Noticed in a debug build.) It looks like it is used to test the rigid groups, which introduces the dependence.

## Script

Build hoomd with `BUILD_MD=OFF`.

## Output

```
Traceback (most recent call last):
  File "/home1/05798/mphoward/code/github/glotzerlab/hoomd-blue/hoomd/test-py/test_group.py", line 5, in <module>
    from hoomd import md
ImportError: cannot import name 'md' from 'hoomd' (/scratch/05798/mphoward/hoomd-blue/build/hoomd/__init__.py)
```

## Expected output

The test should run.

## Configuration

Platform:
- Linux
- GPU

Installation method:
- Compiled from source

Versions:
- Python version: 3.7
- **HOOMD-blue** version: 2.6.0

## Developer

@jglaser this looks like it would be your code. Can you think of a way to separate these?

**Comment by mphoward** [comment]
@jglaser pr #422 should be a quick fix for this, if it looks OK to you.

**Comment by joaander** [comment]
I ran into this myself when testing the new CMake code. Thanks for fixing it!
