### ISSUE TITLE
General way to define moments of inertia

### ISSUE THREAD

**Issue by cpgoodri** [glotzerlab/hoomd-blue#426]
Currently, when defining a rigid body you set the moment of inertia through (Ixx, Iyy, Izz), rather than the full 3x3 moment of inertia tensor, meaning that it is assumed that the rigid body is defined so that its principle axes coincide with x, y and z. While it is possible for a user to diagonalize the moment of inertia tensor and use the eigenvectors to rotate the rigid body manually, it would be nicer if you could simply feed in the full moment of inertia tensor. 

My guess is this would be a relatively easy feature to add, but if it is in fact more complicated, perhaps a temporary solution would be to:

1. Update the documentation so that it is clear to new users that HOOMD is assuming that the tensor is diagonal (I don't remember ever seeing this stated in the documentation, but if it is there and I missed it then I apologize).

2. Include an example of the diagonalization/rotation procedure in the documentation (e.g. for hoomd.md.constrain.rigid).

**Comment by joaander** [comment]
Thanks for the suggestion. The integrators are defined in terms of the principle moments of interia, and we aren't likely to rewrite those. Better documentation and a script that performs the procedure, either in the documentation or as a helper integrated with md.constrain.rigid are both great suggestions. Are you interested in contributing those changes in a pull request?
