### ISSUE TITLE
Integrate HIP

### ISSUE THREAD

**Issue by jglaser** [glotzerlab/hoomd-blue#427]
## Description

Implement initial support for compilation to CUDA using HIP.

## Proposed solution

the 'hip' branch has been created for tracking progress.

## Additional context

HOOMD support for AMD GPUs. More context will be added as available.

## Developer

Work in progress.

**Comment by joaander** [comment]
This is implemented on `next`. There have been discussions about replacing HIP with our own header translation layer so that HIP is not required on NVIDIA only builds. Leaving this issue open as a reminder.

**Comment by mphoward** [comment]
With PR #560, HOOMD now has a copy of [hipper](https://github.com/mphowardlab/hipper) that can be used to support both HIP and CUDA builds. The hipper API is similar to HIP but will require a lot of find-replace and/or someone will need to update the script in PR #587 (and scrap that copy of the runtime).
