### ISSUE TITLE
GTAR uses deprecated C++ features

### ISSUE THREAD

**Issue by joaander** [glotzerlab/hoomd-blue#430]
## Description

GTAR uses deprecated C++ features.

## Script

Compile hoomd on the **next** branch.

## Output

```
hoomd/hoomd/extern/libgetar/src/DirArchive.cpp:187:47: warning: ‘int readdir_r(DIR*, dirent*, dirent**)’ is deprecated [-Wdeprecated-declarations]
hoomd/hoomd/extern/libgetar/src/GTAR.hpp:122:14: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
hoomd/hoomd/extern/libgetar/src/GTAR.hpp:165:14: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
hoomd/hoomd/extern/libgetar/src/GTAR.hpp:253:10: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
hoomd/hoomd/extern/libgetar/src/GTAR.hpp:260:25: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
hoomd/hoomd/extern/libgetar/src/GTAR.hpp:262:25: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
hoomd/hoomd/GetarInitializer.h:90:18: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
```

## Expected output

No deprecation warnings.

## Configuration

Platform:
- Linux

Installation method:
- Compiled from source

Versions:
- Python version: 3.7
- **HOOMD-blue** version: **next** branch

## Developer

@bdice I think you are maintaining GTAR functionality in hoomd. Can you fix this?

**Comment by bdice** [comment]
@joaander I'm able to reproduce this just by compiling libgetar on its own. I am familiar with the culprit source code that is using `auto_ptr`. I'll take a look at this via https://github.com/glotzerlab/libgetar/issues/14.

**Comment by bdice** [comment]
This was resolved in libgetar.
https://github.com/glotzerlab/libgetar/issues/14
https://github.com/glotzerlab/libgetar/pull/16

@joaander Do you want me to make a pull request that updates the submodule, and if so, should it target **next** or **master**?

**Comment by joaander** [comment]
Thanks. Go ahead and target the PR on next.
