### ISSUE TITLE
Possible documentation typos in md.pair.buckingham

### ISSUE THREAD

**Issue by sottcap** [glotzerlab/hoomd-blue#439]
## Description

I guess Buckingham potential has the form of A*exp(-r/rho)-C/r^6 but the document says it is A*exp(-r/rho)-C/r instead of r^6. Is this just a typo or the potential is implemented as -C/r? Either way I think it should be corrected.
## Script

```python
# Include a minimal script that reproduces the problem

```

## Configuration

Platform:
- Mac
- Linux
- GPU
- CPU

Installation method:
- Conda package
- Compiled from source
- glotzerlab-software container

Versions:
- Python version: ?.?.?
- **HOOMD-blue** version: ?.?.?

**Comment by mphoward** [comment]
This is only a typo in the documentation, not an bug in the code.

https://github.com/glotzerlab/hoomd-blue/blob/1743c67f00821e0a44de31e137a128f84d114079/hoomd/md/EvaluatorPairBuckingham.h#L110-L112

Please feel free to submit a PR correcting the docs.

**Comment by joaander** [comment]
Fixed in #459
