### ISSUE TITLE
MPCD pore streaming geometry

### ISSUE THREAD

**Issue by mphoward** [glotzerlab/hoomd-blue#440]
## Description

A new mpcd streaming geometry that includes the entrance / exit from a pore (a slit, a cylinder, etc.) as expansion/constriction within the PBCs, which is useful for simulating polymer translocation, etc.

## Proposed solution

Implement as a streaming geometry, called like:

```
mpcd.stream.slit_pore()
```

## Additional context

I will likely also implement a `mpcd.stream.cylinder` and `mpcd.stream.cylinder_pore`, but this will get a separate issue and PR.

## Developer

I will work on this.

**Comment by mphoward** [comment]
@joaander I'm close to finishing with this on `feature/mpcd-slit-pore`. Do you want me to rebase onto the azp branch for testing before opening a PR targeting `master`?

**Comment by joaander** [comment]
Yes, rebasing on azp would be great. Azure pipelines is working out really well for testing - a lot more stable than Jenkins.

**Comment by mphoward** [comment]
Great, done. Are the GPU-enabled builds run on Microsoft's agents & are they also free? I'm using CircleCI for [azplugins](https://github.com/mphoward/azplugins) following our discussion, but I can only test CUDA builds (not run them) there. This would be a great solution if so.

**Comment by joaander** [comment]
I use self-hosted agents (https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops) for the GPU tests. They are free on the public tier, provided as one brings their own hardware. I'm using the same hardware that supported the Jenkins infrastructure.
