### ISSUE TITLE
Singularity Pull Installation Instructions Out of Date

### ISSUE THREAD

**Issue by rcplane** [glotzerlab/hoomd-blue#442]
## Description

The documented Singularity pull command now fails.
https://hoomd-blue.readthedocs.io/en/stable/installation.html

Is the new singularity image collection csadorf/software:latest ?
https://singularity-hub.org/collections/1027

## Script

singularity pull --name "software.simg" shub://glotzerlab/software

## Output

FATAL:   Failed to get manifest from Shub: The requested manifest was not found in singularity hub

## Expected output

Successfully pull image from Singularity Hub.

## Configuration

Platform:
Linux CentOS 7

Installation method:
- glotzerlab-software container

Versions:
- Python version: 2.7.5
- **HOOMD-blue** version: latest

## Developer

Documentation revision suggestion above.

**Comment by csadorf** [comment]
@rcplane Hi! @joaander will need to advise on the necessary correction of the instructions in the documentation, however the containers hosted under my account (csadorf) are definitely out of date and I only updated those for my personal use. Just thought I would let you know right away.

**Comment by joaander** [comment]
Singularity-hub now imposes severe limits on how many times an image may be pulled. We now host the containers on our website.
```
curl -o software.simg https://glotzerlab.engin.umich.edu/downloads/glotzerlab/software-nompi.simg
```
Full documentation: https://glotzerlab-software.readthedocs.io/en/latest/

HOOMD-blue v2.7 will fix this in the HOOMD documentation.
