### ISSUE TITLE
Compute capability isn't detected, Volta + CUDA 10.1.150

### ISSUE THREAD

**Issue by keipertk** [glotzerlab/hoomd-blue#464]
## Description

I compiled HOOMD-blue with CUDA 10.1.150 on a node with four V100 GPUs:

```cmake ../ -DCMAKE_INSTALL_PREFIX=`python3 -c "import site; print(site.getsitepackages()[0])"` -DCMAKE_CXX_FLAGS=-march=native -DCMAKE_C_FLAGS=-march=native -DENABLE_CUDA=ON -DENABLE_MPI=ON -DCUDA_CUDART_LIBRARY=/cm/extra/apps/CUDA.linux86-64/10.1.150_418.39/lib64/libcudart.so -DCMAKE_C_COMPILER=/cm/extra/apps/GCC/7.3.0/GCC-4.8.5_GMP-6.1.2_MPFR-4.0.1_MPC-1.1.0/bin/gcc -DCMAKE_CXX_COMPILER=/cm/extra/apps/GCC/7.3.0/GCC-4.8.5_GMP-6.1.2_MPFR-4.0.1_MPC-1.1.0/bin/g++ -DCUDA_ARCH_LIST="70"```

Upon running `ctest -VV`, all of the `--mode=gpu` tests fail with:

`Notice: GPU id 0 is not available for computation because it's compute capability is not high enough
3: notice(2): This build of hoomd was compiled for a minimum capability of of 3.5 but the GPU is only 0.0`

I tried querying cudaDeviceProp in a standalone kernel and the correct compute capabilities were reported. I proceeded to re-build with CUDA 9.2.88 (no other changes to the configuration), and ctest reported 100% success.

## Configuration

Platform:
- Linux: CentOS 7, kernel 3.10-0
- GPU: 4 x V100
- CPU: Xeon E5-2698 v3

Installation method:
- Compiled from source

Versions:
- Python version: 3.7.3
- HOOMD-blue version: 2.6.0-91-gee1691d 
- CUDA driver 418.67
- CUDA version 10.1.150

**Comment by joaander** [comment]
What is the output of `nvidia-smi`?

**Comment by keipertk** [comment]
https://gist.github.com/keipertk/2b11c7c66c47ca529f25285de3c65099

https://gist.github.com/keipertk/960d312cbe2e5315631e7c142092f93c

**Comment by joaander** [comment]
Thanks. Your `nvidia-smi` reports CUDA driver 10.1 capability, so it should work.

I don't think this is a bug in HOOMD. HOOMD calls cudaGetDeviceProperties():
https://github.com/glotzerlab/hoomd-blue/blob/034615d08c618f3e125925b6e793affc8b55416b/hoomd/ExecutionConfiguration.cc#L505
And then checks that the reported compute capability is valid:
https://github.com/glotzerlab/hoomd-blue/blob/034615d08c618f3e125925b6e793affc8b55416b/hoomd/ExecutionConfiguration.cc#L524-L536

Your output indicates that `cudaGetDeviceProperties` returned 0.0 for the device compute capability. This usually means that CUDA runtime is newer than the driver.   

If possible, can you try a newer NVIDIA CUDA toolkit and/or driver? I have no issues with V100 on local test machines with: CUDA 10.1.243 and driver version 430.40.

**Comment by keipertk** [comment]
You're right - there was a mismatch between the driver and toolkit. I tried an updated toolkit and we're up and running. Thanks!
