### ISSUE TITLE
Anisotropic Wall Potentials

### ISSUE THREAD

**Issue by vtelezki** [glotzerlab/hoomd-blue#469]
## Description

Particles interacting with walls should experience a torque if the potential is anisotropic. 

## Proposed solution
Write anisotropic versions of PotentialExternal and EvaluatorWalls:
 - AnisoPotentialExternal
 - AnisoEvaluatorWalls
 - ... 

## Additional context
Rod-like shaped particles should experience a torque from simply repellent walls such as 'shifted Lennard-Jones' in the sense of that the torque is given by \vec T = \vec e \cross \vec F

## Developer
I started writing the template classes but I am not really sure how to actually implement e.g. a torque generating version of the shifted Lennard-Jones potential and would appreciate it if someone could give me advice/guidance. Thanks!

**Comment by joaander** [comment]
Thanks for the suggestion. To implement this, one would need to implement a `ForceCompute` class that computes the energy, force, and torque of each particle-wall interaction. The details of the computation are highly dependent on the shape of the particle and the wall. 

HOOMD-blue currently supports Gay-Berne ellipsoids and DEM polyhedra. Which of these are you interested in using with walls? And what type of walls?

**Comment by vtelezki** [comment]
Actually, I was thinking of starting with Lennard-Jones spheres, where the "torque" is a result of an effective (steric, hydrodynamic ...) interaction with the walls. But I figured that I could extend it to be more general/realistic with i.e. Gay-Berne potentials for the particles and planar/ perpendicular anchoring at LJ walls. I am open for suggestions to make the implementation more applicable for other cases. 

I was hoping to somehow recycle the already existing `EvaluatorWalls` class that takes the geometry of the walls into consideration and calculates the force, energy and virial and extend it with the calculation of the torque.

**Comment by joaander** [comment]
Are you planning to apply this to point LJ particles, or LJ particles that are constituents of rigid bodies?

**Comment by vtelezki** [comment]
To point LJ particles

**Comment by joaander** [comment]
Sorry, I don't understand. Could you explain more completely what you hope to accomplish?

For an isotropic particle, the pairwise interaction with the nearest point on a wall will always produce a torque of 0.

**Comment by vtelezki** [comment]
I am trying to reproduce the behaviour of active particles near walls. Usually, there is some kind of reorientation happening when an active particle interacts with an obstacle. Now, without worrying about the details of the nature of the interaction, I would like to reproduce that effect. Although the particles are described by an isotropic potential, I would like them to reorient at a wall.

**Comment by joaander** [comment]
OK, so you have some expression specific to your system that computes a torque between a point particle and a wall and you want this torque to apply to the equations of motion. You need to

1. Give your particles non-zero moment of inertia so that HOOMD will integration rotational degrees of freedom
2. Use the `orientation_link` flag with `md.force.active`. 
3. Implement a custom `ForceCompute` that computes the torque you want using the particle orientations. 

You may be able to reuse portions of the `EvaluatorWalls` machinery to implement this, but I don't see any simple way to extend `EvaluatorWalls`. `EvaluatorWalls` treats the particle-wall interaction as a conservative particle-particle interaction with a virtual particle placed at the nearest point on the wall.

**Comment by mphoward** [comment]
> `EvaluatorWalls` treats the particle-wall interaction as a conservative particle-particle interaction with a virtual particle placed at the nearest point on the wall.

Could the virtual particle at the wall be given a nominal orientation pointing in the direction of the surface normal? Then, EvaluatorWalls could be generalized to the aniso pair evaluators accepting this orientation and the actual orientation of the particle interacting with the wall.

**Comment by vtelezki** [comment]
>     1. Give your particles non-zero moment of inertia so that HOOMD will integration rotational degrees of freedom
Ok. I am already doing that. 

>     2. Use the `orientation_link` flag with `md.force.active`.
I had to write my own version of `md.force.active` because I ran into some problems with dipole interactions and active particles. But that is probably a separate issue.

>     3. Implement a custom `ForceCompute` that computes the torque you want using the particle orientations.
I will give it a try. Thank you for your help!

>     Could the virtual particle at the wall be given a nominal orientation pointing in the direction of the surface normal? Then, EvaluatorWalls could be generalized to the aniso pair evaluators accepting this orientation and the actual orientation of the particle interacting with the wall.

As far as I understand it `Planes` have the method `normal` and a normal vector is calculated to get `drv` for the other wall types. Or what do you mean?

**Comment by mphoward** [comment]
For the current wall interactions, the force is evaluated using the distance between a point particle and the closest point on the surface. The direction of this force is computed by `vecPtToWall` and must then be the surface normal at the closest point. If I understood correctly, the scheme you have in mind is to apply torques when particles are in certain orientations relative to the surface--this could be achieved using a mechanism like `EvaluatorWalls` by specifying one quaternion in the AnisoPotentialPair evaluator as the surface normal and the other as the quaternion of the particle, in addition to the vector pointing between the two.
