### ISSUE TITLE
GSD restart from trajectory

### ISSUE THREAD

**Issue by mphoward** [glotzerlab/hoomd-blue#485]
## Description

The restart feature of `hoomd.init.read_gsd` could be more useful if the last frame is always read from the `restart` file rather than the one specified by `frame`. My reasoning is similar to #321: I think `frame` is probably more commonly used to specify a specific frame to be read from `filename` in the same way that `time_step` resets only `filename`. But, in my uses (at least), it isn't important to me what `frame` to specify for the restart--I just want whatever the last entry of the GSD file is. This is useful for restarting a simulation where a trajectory is already being written frequently with all of the particles, and so there doesn't seem to be a need to save a separate restart.

## Proposed solution
Solution: replace `abs(frame)` by 1 and `frame < 0` by True here:

https://github.com/glotzerlab/hoomd-blue/blob/dcab8fce47ef4ec2c896a33d76dd7d44ca411a83/hoomd/init.py#L290-L292

Logic like this:
```python
if os.path.isfile('trajectory.gsd'):
    hoomd.init.read_gsd('trajectory.gsd', frame=-1)
else:
    hoomd.init.read_gsd('init.gsd', frame=3, time_step=0)
```
could then be replaced by this:
```python
hoomd.init.read_gsd(filename='init.gsd', restart='trajectory.gsd', frame=3, time_step=0)
```
On first pass, frame 3 of `init.gsd` is read and the time step is set to 0. The last frame of `trajectory.gsd` is read on restart.

## Additional context

None.

## Developer

This is only a few lines, so I can implement if there is agreement to change this.

**Comment by joaander** [comment]
@b-butler and I have discussed removing the restart argument in the v3 API, making the API simpler and easier to understand and allowing the user to implement whatever logic they need in their script. What are your thoughts on that @mphoward ?

I like the idea of a combined trajectory/restart file. I am planning to encourage this workflow in the rewritten examples to go with the new v3 API. I plan to avoid file selection logic by using a single gsd file for initialization, trajectory, and restart using  `frame=-1`. Perhaps `frame=-1` should be the default.

**Comment by mphoward** [comment]
I think having `frame=-1` would be a very good default. It makes more sense than defaulting to 0, especially for the case you describe of a single trajectory. I also don't necessarily mind if I need to write the selection logic myself, as this is more flexible. But, there is a certain value (of convenience) to keeping the init and restart options since the logic "if restart exists use it else use init" is extremely common and not always worth the python boilerplate. If those options were to exist, I would just clarify that options like frame and time_step don't apply to restart, and the last frame is always read.

In any case, I think the key thing is to avoid confusion over what the behavior of the init command, as here I accidentally restarted my simulation from frame 0, thinking that I was getting the last file of the trajectory, and then I had to kill the job, lop off the frames that got appended before I saw what was happening, and then restart it correctly. :-)

I'm also not sure how often I would use a "one trajectory" workflow, since I would be a little nervous appending to a file I created elsewhere. I often recycle the same init file between different simulations where the configuration starts the same but parameters vary. If I had one trajectory file, I would need to make multiple copies of it, and this makes file management messier. So, this could definitely be useful for some types of simulations, but having a way to avoid it is also helpful.

**Comment by joaander** [comment]
@b-butler any thoughts on this discussion?

I agree this use case should be convenient. Can we think of a better API for `create_state_from_gsd` that this?
```
def create_state_from_gsd(filename, restart_filename, frame)
```
My concern is that just from looking at the arguments it is not clear that frame should only apply to `filename`, not `restart_filename`. Yes, we can document it, but there will be users that don't look closely at the docs. Also, we changed how the initial time step can be set:
```
sim = Simulation()
sim.timestep = 100000
sim.create_from_gsd('init.gsd') # ignores the timestep in the gsd and uses 100000
```

What if `create_from_gsd` returned `False` if the file didn't exist? Then the user could implement the proposed restart logic with:
```
sim = Simulation()
if not sim.create_state_from_gsd('restart.gsd'):
    sim.timestep = my_timestep_override
    sim.create_state_from_gsd('init.gsd', frame=my_frame)
```
I'm not sure I like that. It wouldn't raise an error if 'init.gsd' is also missing. Any other ideas?

**Comment by b-butler** [comment]
I would say that returning `False` isn't a good idea. In python, the user should catch the error as the boilerplate instead of using an if statement. I would suggest if we want to support multi file projects we should do something like this
```
sim = Simulation()
sim.create_state_from_gsd(['restart.gsd', 'prod.gsd', 'init.gsd'], frames=[-1, -1, -1])
```
where filenames is a list of filenames or a string of one filename. The first names in the list get priority, and frames can either be a list of frame values for each file or a single interger. The default could and still should be -1. Then we can still raise an error if `init.gsd` doesn't exist, and this is quite flexible.

Those are my thoughts @mphoward @joaander

**Comment by joaander** [comment]
No comments in the last 6 months. Is this something someone is motivated enough to work on, or should we just close this issue?

**Comment by mphoward** [comment]
I would vote to close and reopen this if someone gets the motivation to implement it later.

**Comment by joaander** [comment]
Will do. Of course, anyone is free to reopen, I'm trying to clean up the issue list and prioritize the important tasks.
