### ISSUE TITLE
Rename all

### ISSUE THREAD

**Issue by joaander** [glotzerlab/hoomd-blue#488]
## Description

`all` is a python keyword and should not be used for group or variable names.

## Proposed solution

Perhaps use `all_particles`.

**Comment by mphoward** [comment]
`all_particles` is clear but more verbose. PEP 8 recommends a trailing underscore to avoid conflicts with keywords if you want to keep a short version.

**Comment by b-butler** [comment]
This is going to be solved by the v.3.0 API change to use the python class `All(ParticleSelector)`. This keeps the verbosity down, while maintaining a descriptive name without the overwriting of the keyword.

**Comment by bdice** [comment]
@joaander I would like to understand this problem a little better, for the context of the signac issue with adding a property `job.id`, referenced above. Was the problem with `hoomd.group.all` only when logging lines from the user script, or is it something different / deeper?

It seems that `all` is a function but not a keyword, which is the same case we would face with `job.id`.
```python
>>> import keyword
>>> keyword.kwlist
['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']
```

**Comment by mphoward** [comment]
I think the main issue is that docs have tons of examples like:
```
all = hoomd.group.all()
```
which stomps on the built-in function. I suppose it could also cause issues depending on how `hoomd.group` is imported.

**Comment by joaander** [comment]
The new examples will encourage direct use of the filters:
```
gsd = hoomd.dump.gsd(filter = hoomd.filter.All(), ...)
```
In the new API there is no need or reason to hold filters in variables.

**Comment by joaander** [comment]
Implemented in `feature/new-object-API`
