### ISSUE TITLE
Templated bond, angle, and dihedral evaluators

### ISSUE THREAD

**Issue by mphoward** [glotzerlab/hoomd-blue#490]
## Description

Internally, the bond, angle, and dihedral potentials could be simplified by using template logic for the potential evaluator, similar to the pair potentials. This is especially useful for angles and dihedrals, where alot of duplicate code is needed to evaluate the gradient of the angle with respect to each particle position, and the main differences lie only in the gradient of the potential with respect to the angle (or cosine of the angle). This would significantly ease the pain of adding new functional forms for these types of potentials. It would also allow for convenient introduction of potential smoothing functions like I describe [here](https://doi.org/10.1063/1.4985251) for coarse-grained models that have degeneracies.

## Proposed solution

The python API would be unchanged. The C++ API should use evaluator templates analogous to the pair potentials. We would need to look at the different potentials to determine the functions the evaluator implements.

## Developer

This isn't a priority for me right now, just documenting as an idea after this [forum post](https://groups.google.com/d/msg/hoomd-users/S4OtayowxIM/nd2uid8xAgAJ).

**Comment by joaander** [comment]
I agree, this would be nice to have.
