### ISSUE TITLE
Using JIT for MD pair potentials

### ISSUE THREAD

**Issue by vyasr** [glotzerlab/hoomd-blue#507]
## Description

The ability to specify new pair potentials via a JIT kernel rather than having to implement a full new Evaluator.

## Proposed solution

The API for this could be similar to the current `jit.patch`. We could also take inspiration from OpenMM, which uses Sympy to accept arbitrary mathematical expressions and JIT-compile them. The hard part will be ensuring that CUDA-JIT (and potentially HIP-JIT) plays nicely with the rest of our infrastructure.

## Additional context

Josh and I have discussed this possibility before, I'm just creating the issue now so that we can keep track of it.

**Comment by lyrivera** [comment]
I'd be interested in contributing to this.

**Comment by joaander** [comment]
Given the difficulties with LLVM, I'd like to investigate whether a non-LLVM implementation on the CPU could perform well.
