### ISSUE TITLE
Support the new `__cuda_array_interface__` protocol

### ISSUE THREAD

**Issue by vyasr** [glotzerlab/hoomd-blue#508]
Brought to my attention by @bdice, this protocol enables e.g. Numba `cuda.jit` kernels to execute calculations on arrays stored on the GPU, and packages [like PyTorch](https://github.com/pytorch/pytorch/issues/11914) have implemented it to allow users to write high-performance methods in essentially pure Python. I have no idea exactly what this would look like or even if it's feasible without doing quite a bit more research, but it's worth keeping an eye on since it could enable high-performance pure-Python implementations of things like advanced sampling methods if you could directly access the particle data on the GPU with zero host-device copies.

**Comment by bdice** [comment]
Related resources:
- https://docs-cupy.chainer.org/en/stable/reference/interoperability.html#interoperability
- https://numba.pydata.org/numba-doc/latest/cuda/cuda_array_interface.html

**Comment by joaander** [comment]
The fundamental question here is whether we should expose the underlying C++/CUDA data structures to Python. Should we expose to the user things like:
- `position` and `type` are stored together in a Scalar4
- `velocity` and `mass` are stored together in a Scalar4
- The first `N` particles in the array are local to the rank, while indices `N` to `N+N_ghost` are ghost particles
- not all particle properties are set for ghost particles
- types are indices, not string names
- the type may be single or double precision depending on compiler options

Aside: If we do expose this to the user, then we cannot change data structures for optimization purposes without bumping the major version number.

This came up in another conversation on custom filters for particle groups. One way to implement that is a ParticleSelectorCustom that accepts a python callback: #510.

Another is to allow the user to create python classes derived from ParticleSelector (@b-butler's suggestion). This is more in line with designing HOOMD v3 as an API, but comes with the necessity to provide a Pythonic and performant interface to the underlying C++ data structures in SystemDefinition.

**Comment by vyasr** [comment]
In general I'm against any Python API in HOOMD that places any sort of specific requirements on the C++ API since we are consistently refactoring and changing parts of that for optimization, better compatibility with new architectures, etc. However, it may be possible to expose GPU data via a `memoryview`-like interface, in which case the requisite type casting would occur in the Python wrapper and the underlying C++ types would still be possible to change.

I agree that subclassing ParticleSelector is the right approach, but perhaps we can punt on that until we've finished more of v3 and have a sense of how much extra work it would require.

**Comment by bdice** [comment]
I agree that we should not constrain the C++ API or GPU data structures to enable this -- just wanted to toss out the idea. If it is natural to implement this interface without exorbitant work, it would be nice to enable GPU-accelerated methods for advanced sampling, analysis, etc. within Python callbacks. As v3 matures, we'll have a better idea of whether it's straightforward to implement.

**Comment by b-butler** [comment]
From [numba docs](https://numba.pydata.org/numba-doc/latest/cuda/cuda_array_interface.html) it looks fairly straight forward. The implementation seems like it should be similar in principle to #645 which does this for access on the CPU, but passing the information as a Python dictionary is a bit different and passing the pointer as an int in Python. Wtih the v2 of the interface, we can also specify strides which will let us pretend as we do in #645 that positions and types are stored separately.

**Comment by joaander** [comment]
Complete in #645
