### ISSUE TITLE
Allow performant snapshot reading from state object 

### ISSUE THREAD

**Issue by b-butler** [glotzerlab/hoomd-blue#509]
## Description
With the new API, the state object has a `snapshot` property that can be used to query about the state. Getting the snapshot object can be costly. Adding a caching feature for the `State` class snapshot object would be useful to users and allow both
```
snapshot = sim.state.snapshot
for ind in len(Np):
    print(snapshot.particles.position[ind])
```
and
```
for ind in len(Np):
    print(sim.state.snapshot.particles.position[ind])
```
to be equally fast. The only catch is that then setting an attribute of the cached snapshot would be allowed, not reflected in the simulation, but reflected in all future accesses of snapshot until another `sim.run` call.

## Proposed solution
I propose adding a cached snapshot that has a timestamp. As long as the timestamp is the same as the current simulation time step, then the cached value should be retrieved. As to how to prevent this snapshot from having its fields assigned, the problem is that this would actually work while being confusing,
```
for ind in len(Np):
    sim.state.snapshot.particles.position[ind] = [0, 0, 0]
sim.state.snapshot = sim.state.snapshot
```
This would create a simulation state where every particle was at the origin. We may be able to wrap the snapshot into a `ReadOnlySnapshot` class that disallows setting by overwriting the `__getattr__` and `__setattr__` methods. We could then force that a writable snapshot requires a `copy(snapshot)`. Then `sim.state.snapshot` and anything that points to it would always reflect the current state --until a `sim.run` call.

In the end, this may not be enough of a problem to be worried about, but for thoroughness I wanted to include it.

## Developer
This issue does not require much prior HOOMD-blue knowledge.

**Comment by joaander** [comment]
In practice, setting snapshots is much slower than getting them (especially on the GPU). Now that we have the performant local snapshot API, this work seems to not be worth the effort.
