### ISSUE TITLE
Port the HPMC muvt updater to v.3.0 API

### ISSUE THREAD

**Issue by b-butler** [glotzerlab/hoomd-blue#511]
## Description
Refactor the HPMC muvt updater to the HOOMD v.3.0 API. The template can be found in the `feature/new-object-API` branch's `Clusters` updater in `hoomd/hpmc/update.py`.

## Proposed solution
The solution involves following the template mentioned above.

## Additional context
Any pull request should merge into `feature/new-object-API` **not** `master`.

**Comment by lyrivera** [comment]
I think I familiarized myself enough with v.3.0 while working on #758 that I can do this without much extra effort.

**Comment by joaander** [comment]
Thanks @lyrivera , that will be helpful.
