### ISSUE TITLE
Unify Walls python API for HPMC and MD and enable deferred initialization

### ISSUE THREAD

**Issue by j-proc** [glotzerlab/hoomd-blue#551]
At some point we will have to make this have a deferred initialization for the walls. Since we want to be able to create walls without having a mc integrator instance at the time of creation. They need the same attach concept as well.

_Originally posted by @b-butler in https://github.com/glotzerlab/hoomd-blue/pull/536_

There MD python walls currently allows for deferred initialization via `wall.group`. Would be likely easier to utilize it for both HPMC and MD than keeping separate implementations.

**Comment by b-butler** [comment]
Is there a need to group walls outside of the `Operations` object. The `Operations` object for a `Simulation` parent object holds all of the relevant information to run a particle simulation complete with dumping, logging, updating, etc. The `Operations` object may be a natural place to store all of the walls, and upon initialization the walls would all be attached to the integrator.

**Comment by j-proc** [comment]
Note: Examples should be updated for these as well as the Wall updater in HPMC

**Comment by j-proc** [comment]
> Is there a need to group walls outside of the `Operations` object. The `Operations` object for a `Simulation` parent object holds all of the relevant information to run a particle simulation complete with dumping, logging, updating, etc. The `Operations` object may be a natural place to store all of the walls, and upon initialization the walls would all be attached to the integrator.

Wall groups have a purpose in MD because specifying individual walls for each potential is supported. I'll consider if it makes any sense to remove the concept, but my initial thought is that the groups themselves should be a concept under 'Operations' to retain this ability.

**Comment by j-proc** [comment]
Notes for the hackathon:
Hoomd v3 only exposes filters to the user. The walls groups is used mainly for efficiency and doesn't have to be exposed to the user. It should be possible to write a filters in such a way that they take many wall objects and internally spawn the required groups 

This likely isn't the cleanest solution so I welcome further discussion.

**Comment by j-proc** [comment]
Wall geometry definitions will be unified and have a common access at hoomd.wall. We ultimately need to decide if we're keeping to simple classes which are mainly used for data storage or param dicts that are used. The mutability of these objects is also unclear at this time and likely depends on the way in which NPT walls would be implemented.

We will keep a meta list of all walls that will then be split into sync'd lists of each wall type. Initially it will only accept spherical walls and will be left to expand. This is due to the need to handle indexing of multiple lists and the one meta list.

Wall groups was a necessity at the time of writing because managed arrays had not been implemented. This could be updated to enable arbitrary numbers of walls or an error can be given if the user tries to add too many walls.

If we work under the assumption all wall-particle interactions should always be used in an identical way, we don't need filters. This can be relaxed in the future by implementing filters for these forces, likely for particles than interact and the wall forces themselves to be specialized per wall.

Wall forces will be accessed at hoomd.md.external.wall(.lj).

We should make new issues for what work we're leaving for later with these changes.
