### ISSUE TITLE
New Logger API

### ISSUE THREAD

**Issue by joaander** [glotzerlab/hoomd-blue#552]
## Description

Replace `analyze.log` with a more complete and documented system. The new Logger system should be able to log vector quantities (i.e. force on each particle, 6-component pressure tensor, etc...). **ALL** loggable quantities should also be available via the user facing Python API. Thus, the natural implementation of the logger is in Python.

## Proposed solution
@b-butler and I are currently designing and implementing this. The overall structure is clear, but the specific form of the API calls is still under development.

### Properties

Loggable quantities will be implemented as properties. Examples:
```
lj.energy
lj.energies
thermo.pressure
mc.overlaps
```
Users can access these properties directly in their python script for real time access. There will be no need to create a logger with period=None and query it as in hoomd v2.

### Logger

A `Logger` object assembles a list of log quantities from any number of objects. Adding an object to a logger adds all of the loggable quantities by default:
```
Logger log()
log += mc
log += thermo
```
Users can specify only specific quantities if desired:
```
log.add_quantity(lj, lj.exports['energy'])
```

### Backends

Multiple backends may be implemented on top of `Logger`. We plan to implement a GSD backend first. This will enable logged quantities in GSD files to be read by OVITO. If the user wants a pure log output (no particles) at a higher rate that the trajectory output, they can pass the `None` particle filter to the GSD dump.

We also expect an HDF5 backend as a rewrite of the current HDF5 logger in HOOMD. Others are certainly possible, such as `pandas`.

### Data types

Supported data types include floats, ints, strings, 1- and 2- dimensional numpy arrays (and types convertible to numpy arrays). This choice is motivated by the support for data types in GSD and HDF5.

We will also support dicts and nested dicts that contain these base data types. More on this below.

### Namespaces

The new logging mechanism will maintain the namespace structure of the python library. While verbose, this makes a clear connection between a logged value in a file and where it came from in the simulation. In the current hoomd v2 system it is difficult to know what named quantity came from where, especially when many logged quantities are not even documented. At the Python level, the namespace is stored as a tuple, so that different backends may apply that in a way natural to their format: GSD will use /, HDF5 might use groups. I will use `/` here.

The namespace consists of several parts, the base, the class namespace, the private space and variables. Here are some examples:
```
hpmc/integrate/Sphere/overlap
md/pair/LJ/energy
particles/md/pair/LJ/energies
md/compute/Thermo/pressure
md/compute/Thermo_1/pressure
```
The base is empty for scalar and small vector quantities. Per-particle quantities have a 'particles' base, per-bond quantities have a 'bonds' base, etc... This is motivated by the GSD specification for custom logged quantities. Does it seem awkward? Should it instead be:
```
md/pair/LJ/energy
md/pair/LJ/energies
```
If so, we will need to work with OVITO to enable custom detection of per-particle quantities. Perhaps any array with a length matching the number of particles is per-particle?

The class namespace is derived from the location of the class in the hoomd python namespace: `md/pair/`, `hpmd/integrate`, etc... The private namespace is the name of the class by default, unless there are more than one instance of that class added to the `Logger`. Then the classes get a numbered suffix to disambiguate them.

The final part of the namespace is the name of the quantity which matches the name of the  property. If the property is a dict, the names of the dict keys will expand the namespace deeper.

### Custom quantities

Users will also be able to provide a custom callable that returns one of the supported datatypes. The user will need to provide a namespace to store it in the log file. Should we prepend all custom log types with "custom/"?

### State, parameter data, and restart files

Why allow dicts? 

@b-butler and I discussed the old and only partially implemented GSD state data for restart files. The new Python API makes a hard definition of the **parameters** of an object, which include values, values that are set per type in the system and values that are set per pair of types in the system. This concept is a subset of the **state** data currently saved in GSD. Recognizing that there is only a fuzzy line between *changing* **state** and *fixed* **parameters**, we decided to lump them all together. This is done in the interests of not duplicating code and expanding the ability to load state data for more objects in HOOMD. 

State data (which now includes parameters) will be lumped together in a dict for the log writer to unpack.
```
hpmc/integrate/Sphere/state/a
hpmc/integrate/Sphere/state/d
hpmc/integrate/Sphere/state/shape/diameter
```
Some per type parameters, like LJ potential params will store a dict for each particle type. Some backends may choose to implement the full dict behavior:
```
md/pair/LJ/state/coeff/A^A/epsilon
md/pair/LJ/state/coeff/A^A/sigma
md/pair/LJ/state/coeff/A^B/epsilon
md/pair/LJ/state/coeff/A^B/sigma
```
Others might choose to pack each entry of the dict in its own matrix
```
md/pair/LJ/state/coeff/epsilon (Ntypes x Ntypes)
md/pair/LJ/state/coeff/sigma (Ntypes x Ntypes)
```
In any case, the implementation will need to be able to unpack its representation back into the dict.

In this way, objects like MD integrators simply need to export their internal degrees of freedom as Python properties, advertise them in their `state` object and they will automatically get restart support!

### Restoring state from a log file

With all of the state stored in the log file, users can now fully initialize an object from a GSD file, even without a simulation context:
```
lj = md.pair.LJ.from_gsd('file.gsd', frame=-1)
```
or from a dict (e.g. loaded in from a JSON metadata)
```
lj = md.pair.LJ.from_dict(dict)
```

When there are multiple instances of the same class in the file, the user will need to specify the name:
```
lj = md.pair.LJ.from_gsd('file.gsd', frame=-1, private_namespace='LJ_1')
```

### Text log output

@b-butler and I do not plan to implement a column oriented text output backend like the output from `analyze.log`. I encourage interested users to write such an implementation, which could write straight to stdout for immediate feedback desired. Note that a text based implementation would need to somehow handle array quantities, or just ignore them.

### Version compatibility

New versions of HOOMD might add new loggable quantities. Thus the default use-case (`log += object`) will result in a different set of fields depending on which hoomd version one is running. This shouldn't pose a problem as new versions can only add fields without causing breaking changes. However, if a new per-particle field is added, this could unexpectedly cause larger and slower log files. Is this a problem? Should we alter the design, perhaps by separating large vector and small log quantities into separate add methods?

## Developer

@b-butler and I are implementing this. We think this is the best solution going forward for HOOMD to both make logging more useful and better documented.

We would appreciate any suggestions for improvements from users.

**Comment by joaander** [comment]
@mphoward @jglaser as requested, here is a detailed outline of our planned changes to the logging mechanism.

**Comment by joaander** [comment]
@InnocentBug you were asking about HDF5 logging in HOOMD v3. This issue documents our planned replacement to the current `analyze.log` and HDF5 logging system. It completely removes the `getProvidedLogQuantities`, `getLogQuantity`, and the related tight object dependencies at the C++ level and replaces it with a system based on numpy arrays and Python properties. It should be possible to write an HDF5 logging backed in this new system.

**Comment by jglaser** [comment]
For adding log quantities, can it be shortened to:
```
log.add_quantity(lj.energy)
```
?

And instead of inventing a namespace scheme, could we just use the class name *via* inspection?

**Comment by b-butler** [comment]
@jglaser that would cause the `energy` property to call its `__get__` method which would just return the current energy. By the time the function received the value it would just be a float. We are allowing users to use
```
log += lj
log.add_quantity(lj)
```
However, if they want to only log particular quantities they would have to list them. There isn't a way around that in python that I am aware.

Also to answer your namespace question, we are by default using the class name and the current module as a way to create the namespace for properties an object exports. The namespace is necessary to allow for multiple objects of the same class being logged and to support custom logged quantities.

**Comment by jglaser** [comment]
I guess you could implement a `__call__` interface (or any other internally used interface, such as `__log__`) that allows the logger to do sth different with the python object than what the user sees when they just want to use the quantities scalar value.

Regarding the namespaces, yes, I see that using multiple instances of the same class could lead to naming conflicts, but these could resolved in multiple ways. I now understand that the namespace scheme is a slightly more complex or general solution to what was previously accomplished with log suffices.

**Comment by mphoward** [comment]
I like this proposed set of changes, and it seems flexible enough that we could reimplement a (limited) text logger for conventional workflows.

**Comment by jglaser** [comment]
Here are two suggestions from the dev meeting.

- Implement a decorator `@loggable` for log properties, which confers them with an interface to export data to the logger
- export to pandas dataframes? From thereon, it is easy to generate .txt output or whatever

**Comment by InnocentBug** [comment]
I like the new approach to logging quantities a lot.
Making no distinction between scalars and matrices makes a lot of sense.
But as discussed above this only works if the plain TXT output is abandoned. I guess many users won't like that there is no simple plain text anymore. (If no one steps up and implements one.)

For the HDF5 logger. I can work on that if you want some help in there.
* I agree, the natural way would be again a python only interface.
* The naming scheme should be no problem. HDF5 would use group at that point which is represented as "/" as well.
* HDF5 in general offers the option to write matrices via MPI parallel output. This would help to write large loggable matrices that have a spatial meaning. (Such as mean velocity inside the simulation box.) I am not sure if that should be a priority at this point. This means that the attributes yield only part of a quantity (the part of the matrix that is there local information in their respective domain.)
* The possibilities is to compress data with HDF5 as it is written on the fly.
This can be very helpful for large matrices. This would require an option to tell the logger to treat certain loggable quantities differently when they are first written into the file. (At the creation of the dataset.) Is was for some time on my list to implement in the current HDF5 logger, maybe now is a good time to make it happen.

Other more general remarks.
* It would be nice if the ability to use a suffix for a property remain in the scheme. I am not sure how that would be possible on the python side though.
This could also help to solve some of the naming conflicts @jglaser mentioned earlier.
* I am not sure if I like the idea of providing a custom namespace for custom quantities.
The proposed naming convention should fix all the problems at least for custom plugins.
For python implemented callables this might not be true, though.

Thank you for mentioning me in the discussion. It certainly helps that I know ahead of time, to convert my custom plugins.

**Comment by joaander** [comment]
The new API is implemented in `feature/new-object-API`. We leave the re-implementation of optional backends like HDF5 either to the user or to contributions from an external developer.
