### ISSUE TITLE
hoomd.update.box_resize shifting particle positions

### ISSUE THREAD

**Issue by patricklawton** [glotzerlab/hoomd-blue#568]
## Description
When running with mpi, a call to hoomd.update.box_resize causes the particle positions to shift in the dimensions resized, even if scale_particles=False in hoomd.update.box_resize. 

## Script

import hoomd
from hoomd import hpmc
import numpy as np
hoomd.context.initialize("")
system = hoomd.init.create_lattice(hoomd.lattice.sc(a=0.5), n=[10,10,10])
mc = hpmc.integrate.sphere(d=1.05, seed=1)
mc.shape_param.set('A', diameter=1.0)

print ('Simulation box before resizing:', system.box)
print ('min and max particle positions before resizing:{0}/{1}'.format(np.amin([p.position for p in system.particles], axis=0),np.amax([p.position for p in system.particles], axis=0)))

hoomd.run(1e2)
hoomd.update.box_resize(Lx=system.box.Lx,Ly=system.box.Ly*2,Lz=system.box.Lz*2, scale_particles=False, period=None)

print ('Simulation box after resizing:', system.box)
print ('min and max particle positions after resizing:{0}/{1}'.format(np.amin([p.position for p in system.particles], axis=0),np.amax([p.position for p in system.particles], axis=0)))

## Output
Simulation box before resizing: Box: Lx=5.0 Ly=5.0 Lz=5.0 xy=0.0 xz=0.0 yz=0.0 dimensions=3
Simulation box before resizing: Box: Lx=5.0 Ly=5.0 Lz=5.0 xy=0.0 xz=0.0 yz=0.0 dimensions=3
min and max particle positions before resizing:[-2.25 -2.25 -2.25]/[2.25 2.25 2.25]
min and max particle positions before resizing:[-2.25 -2.25 -2.25]/[2.25 2.25 2.25]
resize_test.py:012  |  hoomd.run(1e2)
** starting run **
Time 00:00:00 | Step 100 / 100 | TPS 258.419 | ETA 00:00:00
Average TPS: 258.393
---------
notice(2): -- HPMC stats:
notice(2): Average translate acceptance: 0
notice(2): Trial moves per second:        458708
notice(2): Overlap checks per second:     4.4919e+06
notice(2): Overlap checks per trial move: 9.79251
notice(2): Number of overlap errors:      0
** run complete **
resize_test.py:013  |  hoomd.update.box_resize(Lx=system.box.Lx,Ly=system.box.Ly*2,Lz=system.box.Lz*2, scale_particles=False, period=None)
Simulation box after resizing: Box: Lx=5.0 Ly=10.0 Lz=10.0 xy=0.0 xz=0.0 yz=0.0 dimensions=3
Simulation box after resizing: Box: Lx=5.0 Ly=10.0 Lz=10.0 xy=0.0 xz=0.0 yz=0.0 dimensions=3
min and max particle positions after resizing:[-2.25 -4.25 -1.75]/[2.25 0.25 2.75]
min and max particle positions after resizing:[-2.25 -4.25 -1.75]/[2.25 0.25 2.75]

## Expected output

If working properly, the min and max particle position lists should match before and after resizing. 

## Configuration

Running hoomd version 2.8.1 on the dali vislab machine, script executed with two mpi ranks. 

Platform:
- Linux
- CPU

Installation method:
- Compiled from source

Versions:
- Python version: 3.8.0
- **HOOMD-blue** version: 2.8.1

## Developer

Fixing an mpi related issue in c is probably over my head, unfortunately.

**Comment by joaander** [comment]
This is a side-effect of grid shift that HPMC employs in parallel simulations. There is no simple fix to `box_resize` that can correct the behavior. `box_resize` would need to take a snapshot, serialize changes to the particles and then restore the snapshot which would reduce performance significantly. 

We could implement this as an alternate code path, run when needed. Or, you can work around this by taking a snapshot in python, changing the box, then restoring the snapshot.

**Comment by joaander** [comment]
After discussing this in person, there may be a solution that doesn't require the snapshot. @vyasr was going to investigate.

**Comment by joaander** [comment]
Any fixes to this issue should be based on #618 or on a higher branch after it gets merged in.
