### ISSUE TITLE
Dynamic Bonding in MD

### ISSUE THREAD

**Issue by atravitz** [glotzerlab/hoomd-blue#572]
## Description

I'm proposing support for dynamic bonds in the md package, allowing for bonds to be broken and formed between particles at each time step. 

## Proposed solution
The dynamic bond module will be an updater within md. If particles are closer than`r_cut`, a random number is generated and there is a probability of `prob_form` that a bond will be formed between the two particles. Likewise, at every time step, there is `prob_break` probability that an existing bond will break. 

```python
    nl = md.nlist.tree()
    dybond = md.update.dynamic_bond(group.all(), nlist=nl, seed=123, period=1)                                                                                        
    dybond.set_params(r_cut=2.0, bond_type='harmonic', prob_form=0.6, prob_break=0.3)   
```
## Additional context

Currently, the probabilities `prob_break` and `prob_form` are defined as the probability that *one* bridge breaks or forms at a given time step, and is evaluated for every particle neighbor pair. 

I'd appreciate your thoughts on the following:

- How, or if, we should allow for multiple bonds breaking/forming at each time step,
- I have a branch where `prob_form` and `prob_break` can be tables, implemented similar to `md.bond.table` or `md.pair.table`. Should this be an option?
- Should we have a limit on the number of bonds per particle? This could be defined by particle type.

## Developer

I have a working version that I can make a PR with, but would like feedback on appropriate features and API. I'm tagging @joaander and @mikemhenry since we've already had conversations about this.

**Comment by mikemhenry** [comment]
Also tagging @amburan

**Comment by InnocentBug** [comment]
I like the discussion about dynamic bonds.
My application of dynamic bonds is probably too complicated to fit into this approach:
in short the creation/deletion of bonds depends on the surrounding (neighbour list access) the other scheme allows the bond anchor points to slide along existing bonds of other types.

However, I would really like to see something like this integrated into HOOMD-blue. I would definitely use as a reference of how to actually add and remove bonds efficiently.

**Comment by InnocentBug** [comment]
I think, making it sensitive to the particles involved in the process is definitely helpful.

**Comment by InnocentBug** [comment]
One of my current questions would be: how is that implemented with multi-GPU/MPI support.
The current framework requires to delete/create bonds as a collective MPI operation.
This of course can be a massive slow down and doesn't scale.
I haven't figured out a better way yet.
Any ideas would be great.

**Comment by joaander** [comment]
The code @atravitz implemented is an example of how to reasonably efficiently handle dynamic bonds within the limitations of the current framework on the CPU. @jglaser would have to comment on the feasibility of updating the bond data structures to perform well with parallel updates which would be a separate project.
