### ISSUE TITLE
HOOMD-blue as git submodule

### ISSUE THREAD

**Issue by cslominski** [glotzerlab/hoomd-blue#577]
Hi,

If I add HOOMD-blue as a submodule to another git project, when I build I receive the error:

CMake Error: File hoomd-blue/.git/HEAD does not exist.

which comes from this file:

hoomd-blue/CMake/git/GetGitRevisionDescription.cmake

Is this the intended behavior? Is there a way to circumvent this?

Thanks,
Charlie

**Comment by joaander** [comment]
This is not intended behavior. This is the first I've heard of someone using HOOMD as a submodule.

`GetGitRevisionDescription.cmake` assumes that `.git` is a directory. In a submodule, it is a file that references another directory. I would welcome a pull request that corrects this behavior. If the embedded git version information is useful for you in your submodule build, you will need to update `GetGitRevisionDescription.cmake` to references the git submodule dir as listed in the `.git` file. Alternately, you could make this condition a warning and skip further git version processing if `.git` is not a directory (e.g. modify line 44).

**Comment by cslominski** [comment]
OK thanks. I'll complete in ~2 weeks.
