### ISSUE TITLE
Remove MKL support

### ISSUE THREAD

**Issue by jglaser** [glotzerlab/hoomd-blue#581]
## Description

MKL support is dysfunctional and leads to installation issues for new users. Current solution is to cmake with

```
-DMKL_LIBRARIES= -DMKL_INCLUDE_DIR=
```

## Script

```cmake -D ENABLE_MPI=ON ..```

## Output

```
ld: ../_md.cpython-37m-x86_64-linux-gnu.so: undefined reference to `DftiComputeForward'
ld: ../_md.cpython-37m-x86_64-linux-gnu.so: undefined reference to `DftiSetValue'
ld: ../_md.cpython-37m-x86_64-linux-gnu.so: undefined reference to `DftiCreateDescriptor_s_1d'
ld: ../_md.cpython-37m-x86_64-linux-gnu.so: undefined reference to `DftiComputeBackward'
ld: ../_md.cpython-37m-x86_64-linux-gnu.so: undefined reference to `DftiFreeDescriptor'
ld: ../_md.cpython-37m-x86_64-linux-gnu.so: undefined reference to `DftiCommitDescriptor'
```

## Expected output

No linker errors

## Configuration

Platform:
- Linux
- MPI
- MKL

Installation method:
- Compiled from source

Versions:
- Python version: any
- **HOOMD-blue** version: >=1.0

## Developer

yes

**Comment by phall-brown** [comment]
I am running into this issue trying to install hoomd on our cluster (RHEL7.3). The fix mentioned above (adding -DMKL_LIBRARIES and -DMKL_INCLUDE_DIR flags when invoking cmake) is not working for me. Is there another work around for this? Thanks!

**Comment by joaander** [comment]
Starting with cmake 3.17, the workaround `-DMKL_LIBRARIES= -DMKL_INCL
UDE_DIR=` seems to always be needed. We need to remove this support.

**Comment by joaander** [comment]
fixed on `next`
