### ISSUE TITLE
Use TBBConfig.cmake

### ISSUE THREAD

**Issue by jglaser** [glotzerlab/hoomd-blue#625]
## Description

the conda version of tbb comes with the above file. We should make use of it with `find_package`, instead of searching for header files and library manually.

## Script

the current logic is in `CMake/hoomd/FindTBB.cmake`

## Output

N/A

## Expected output

N/A

## Configuration

Platform:
- Mac
- Linux

Installation method:
- Conda package
- Compiled from source

Versions:
- Python version: 3.7 minconda
- **HOOMD-blue** version: `next` branch

## Developer

yes

**Comment by joaander** [comment]
Many systems still do not install the TBB config cmake files. Notably, Ubuntu 18.04: https://packages.ubuntu.com/bionic/amd64/libtbb-dev/filelist

**Comment by jglaser** [comment]
We should support both ways, with manual specification as a fallback. This would make installation much easier for distributions that support the config file mechanism.

**Comment by joaander** [comment]
fixed on `next`
