### ISSUE TITLE
Inconsistent placement of trigger and filter in object constructors

### ISSUE THREAD

**Issue by b-butler** [glotzerlab/hoomd-blue#630]
## Description

The position of `trigger` or `filter` as arguments for different HOOMD objects has not been consistent (my fault). A sweep for the new v3 Python objects needs to be made and the position of them in the argument list solidified either at the beginning or the end of the argument list.

Discussion on best placement if anyone has thoughts should be discussed here. If no one voices their preference, I will likely fix this myself with my preferred solution (likely place them at the beginning (triggers don't have reasonable defaults)).

**Comment by joaander** [comment]
Move trigger first (when the class has a trigger) and the filter next (when the object has a filter).
