### ISSUE TITLE
Simplify force.active

### ISSUE THREAD

**Issue by joaander** [glotzerlab/hoomd-blue#633]
## Description

I would like to simplify the active force class in HOOMD v3.0. The current implementation has too many parameters and we can accomplish the needed use-cases with fewer.

## Proposed solution

I propose the new class take only the parameters:
* `seed`
* `active_force` (magnitude and direction of the force in the particle's frame - per particle type)
* `active_torque` (magnitude and direction of the torque in the particle's frame - per particle type)
* `group`
* `rotation_diff` - now always applies to particle orientations

## Additional context

Specifically, this removes the v2 parameters
* `f_list` - replaced by per-type force
* `t_list` - replaced by per-type torque
* `orientation_link` - always True in the new implementation
* `orientation_reverse_link` - not needed
* `constraint` - to be replaced by a new integrator that applies constraints effectively in brownian dynamics

With the removal of `f_list` and `t_list`, the class can also be implemented in multi-GPU simulations.

As far as I can tell, this simplification removes the following two use-cases that were possible in v2.
* Polydisperse force and torque vectors. These now only vary by type.
* Anisotropic particles with a force vector that rotationally diffuses independent of the particle's orientation

## Community input

Are there use-cases you need that are not enabled by this simplification?
@shannon-moran

## Developer

@syjlee and @SchoeniPhlippsn are converting `force.active` to the v3 API.

**Comment by zmokhtari89** [comment]
I think another use-case that will be removed by your suggestion is when the active force is along the orientation and the change of orientation is not determined by the temperature, rather by a given diffusion constant. I think in this case one should use orientation_reverse_link=True and give the desired diffusion constant as the parameter to the active force. At least this is the way I ran my simulations. Or am I wrong and there is a better way to implement this model without using orientation_reverse_link?

**Comment by syjlee** [comment]
@zmokhtari89 thanks for the suggestions on use-case. But, I think I didn't fully understand your simulation setting. Isn't the change of orientation controlled by `rotation_diff` and you can reflect diffusion constant on `rotation_diff` without considering `orientation_reverse_link`? As far as I know, in current tentative plan for v3 API, isotropic point-like particles are considered and anisotropic particle when a force vector that rotationally diffuses independent of the particle's orientation, so that `orientation_reverse_link` doesn't have to be considered. Is the latter case is your use-case?

**Comment by zmokhtari89** [comment]
@syjlee as far as I understood the source code of active force and the Brownian integrator, once we use a Brownian integrator, the orientation performs a Brownian motion with a noise term characterized by k_BT. The parameter "rotation_diff" in the active force determines the rotational diffusion of the active force vector (and not the orientation). I use orientation_reverse_link so that the orientation is linked to the active force and changes with the given diffusion coefficient. Did I understand it correctly?

**Comment by shannon-moran** [comment]
@joaander apologies for just seeing that I was tagged in this. The polydisperse force vector case is an edge case that I was going to raise, but a rough way around this would be creating _N_ particle types where _N_ is also the number of particles. It would be good to know if this would slow simulations down in anyway (I'm not familiar with how much overhead storing/accessing _N_ type definitions would slow down simulations versus the average 2-3 type definitions).

**Comment by syjlee** [comment]
@zmokhtari89 I think you're right. In the above plans, `rotational diff` always applies to particle orientations, which means we don't need `orientation_reverse_link` anymore.

**Comment by joaander** [comment]
> @syjlee as far as I understood the source code of active force and the Brownian integrator, once we use a Brownian integrator, the orientation performs a Brownian motion with a noise term characterized by k_BT. The parameter "rotation_diff" in the active force determines the rotational diffusion of the active force vector (and not the orientation). I use orientation_reverse_link so that the orientation is linked to the active force and changes with the given diffusion coefficient. Did I understand it correctly?

@zmokhtari89 The Brownian integrator only applies to the particle orientations when the particles have a non-zero moment of inertia. In the proposed API you can get a similar effect as `rotation_diff=value` and `orientation_reverse_link=True` in the current API for spherical particles (the definition of the rotation quaternion would be different). So you do not lose that use-case at all.

With non-spherical particles, you could use either `rotation_diff > 0` (just set the moment of inertia to 0) or Brownian diffusion, but it would be inconsistent to use both as they would both modify the particle orientation in different ways.

I am approaching the new API design assuming that `rotation_diff` was "simulating" particle rotation, so why not replace it with actual rotation in an intuitive and consistent manner.

> @joaander apologies for just seeing that I was tagged in this. The polydisperse force vector case is an edge case that I was going to raise, but a rough way around this would be creating N particle types where N is also the number of particles. It would be good to know if this would slow simulations down in anyway (I'm not familiar with how much overhead storing/accessing N type definitions would slow down simulations versus the average 2-3 type definitions).

@shannon-moran The pair potentials store a matrix of `N_types^2` parameters, so setting `N_types = N_particles` causes a lot of problems. Do you have a strong need for polydisperse force vectors in the local reference frame? Until we add a general API for arbitrary per-particle quantities in the communicator, this is not easy to enable in MPI simulations.

**Comment by zmokhtari89** [comment]
@shannon-moran , @joaander , @syjlee Thank you all for your responses. I am looking forward to v3 now, it seems to be even better for my use case.

**Comment by joaander** [comment]
@zmokhtari89, thanks for reviewing the proposal and offering input!

**Comment by shannon-moran** [comment]
@joaander I think polydisperse force vectors is an unlikely edge case, and one not worth engineering around. Force polydispersity in active systems hasn't been explored too much, but I think one could be statistically smarter about using a limited set of types and exploring polydispersity within that constraint. (Leaving this note here in case some future grad student googles "polydispersity in active matter") Just wanted to highlight the workaround required if someone wanted to do this.

I'm very okay moving forward with this as is.
