### ISSUE TITLE
Decide on how public APIs will be documented for v3.0.0

### ISSUE THREAD

**Issue by vyasr** [glotzerlab/hoomd-blue#636]
This issue stems from a discussion on #618 regarding the use of `__all__` in HOOMD (see [here](https://github.com/glotzerlab/hoomd-blue/pull/618#discussion_r415909726). Before v3.0.0 is released, we should make a decision on how to handle using this and/or underscored names to indicate the public API.

**Comment by joaander** [comment]
The public API comprises the methods with names that PEP8 naming conventions define as public and that appear in the sphinx documentation.
