### ISSUE TITLE
Standardize numpy array type documentation

### ISSUE THREAD

**Issue by vyasr** [glotzerlab/hoomd-blue#638]
We should standardize documentation of function parameters, class constructor parameters, and properties that accept or return numpy arrays. This stems from discussion on #618. Our current consensus is to adopt a modified version of the style currently used in [freud](https://freud.readthedocs.io/en/latest), which reads like `(N_{particles}, 3) numpy.ndarray`. The specific format we settled on is

```
(SHAPE) numpy.ndarray [of TYPE][, optional]
```
(where square brackets indicate optional components).

Ideally, we should also use this across other [glotzerlab](https://github.com/glotzerlab/) packages as well, but that's out of scope for here.

**Comment by joaander** [comment]
Not that I'm recommending this, but I found that GSD uses the lovely format: ``(`numpy.ndarray` or `array_like` [int32, ndim=1, mode='c'])`` - so yeah, we definitely need to standardize this to something clean.

**Comment by joaander** [comment]
See GSD for an example of the formatting to use: https://gsd.readthedocs.io/en/stable/python-module-gsd.hoomd.html#gsd.hoomd.BondData.group

**Comment by joaander** [comment]
We have started using a consistent scheme in newly written documentation (see e.g. Snapshot: https://hoomd-blue.readthedocs.io/en/latest/package-hoomd.html#hoomd.Snapshot). We still need to review the existing docs and see what else needs to be updated.
