### ISSUE TITLE
precision of uniform floating point numbers

### ISSUE THREAD

**Issue by jglaser** [glotzerlab/hoomd-blue#641]
## Description

In `RandomNumbers.h` we currently generate 64bit unsigned longs and use the max value to scale to a uniform double. 2^64-1, however, is not exactly representable as a double, and therefore we're loosing precision. In practice that means that the generated float is not exactly uniform, it only is up to the number of mantissa bits (53). We should use rejection sampling in `u01` to generate actually uniform floats as described here:

https://stackoverflow.com/questions/24023799/how-to-convert-unsigned-long-long-to-double

## Script

compile HOOMD with clang10

## Output

```
/home/users/coe0176/hoomd-blue/hoomd/RandomNumbers.h:79:46: warning: implicit conversion from 'unsigned long' to 'double' changes value from 18446744073709551615 to 18446744073709551616 [-Wimplicit-int-float-conversion]
    R123_CONSTEXPR Ftype factor = Ftype(1.)/(maxTvalue<Utype>() + Ftype(1.));
```

## Expected output

no warning

## Configuration

Platform:
- Linux
- GPU: AMD MI60

Installation method:
- Compiled from source

Versions:
- Python version: 3.7.6
- **HOOMD-blue** version: HEAD of `depletants_new`

## Developer

perhaps

**Comment by joaander** [comment]
I solved the compiler warning by using appropriate types and casts. For double precision outputs and 64-bit inputs, `Ftype(maxTvalue<Utype>()) + Ftype(1.)` will still get rounded to `Ftype(maxTvalue<Utype>())` but the results should still be correct and uniform within the limited precision. There are unit tests that verify `u01<double>(uint64_t(0xffffffffffffffff)) == 1.0` and the +1 is to prevent the output from being larger than 1.0.

Do you have a test that demonstrates non-uniformity?

Rejection sampling the mantissa is an alternative, though it will incur a performance penalty. Also, it would increase the smallest generated value from ~2.71e-20 to machine epsilon ~1.11e-16.
