### ISSUE TITLE
Decouple C++ and pybind11 code

### ISSUE THREAD

**Issue by pabloferz** [glotzerlab/hoomd-blue#649]
## Description

I know HOOMD-blue C++ and Python APIs are tightly coupled, but it would be relatively easy to provide an additional API for the [Julia programming language](https://julialang.org/) if the dependency on `pybind11` were decoupled. I do not expect a Julia API to be maintained by HOOMD-blue core developers, it can live in a separate repository (unless they don't mind to have it here).

## Proposed solution

Decouple the code by taking all the `pybind11` headers out of the C++ files and moving them to mirroring or master API wrapper files. Then, an API similar to the Python one can be written in Julia.

## Additional context

[CxxWrap.jl](https://github.com/JuliaInterop/CxxWrap.jl) (which is Julia's equivalent to `pybind11`).

## Developer

Yes

**Comment by joaander** [comment]
Thanks for the request. This is not something we will be able to meet in the near to medium term. With the HOOMD v3 update, we are adding additional coupling between the Python and C++ APIs, such as custom modifiers #628, zero copy data access #645, and passing parameters back and forth between Python and C++ with dicts #537. This coupling could only be removed with judicious use of `#ifdef ENABLE_PYTHON` throughout the entire codebase. 

I would be willing to help support such use cases, provided that the community could provide most of the effort to make the necessary updates to the codebase and build system. However, any work on this should be delayed until after v3 is finalized.

**Comment by pabloferz** [comment]
I see, that's unfortunate. Looking at the linked PRs, I see that #628 doesn't get in the way of decoupling the APIs, as it is extending the current C++ API through `PythonSomeHeader.h` which in turns includes `SomeHeader.h`, in fact it keeps the bindings decoupled. That was mainly what I was actually proposing instead of `#ifdef ENABLE_PYTHON` statements (unless there is code hard to factor out).

**Comment by joaander** [comment]
Yes, but code that involves passing complex parameters from python through to C++ data structures is tightly coupled with the classes:
https://github.com/glotzerlab/hoomd-blue/blob/800b589e23976d0ab3abf95263257d7d176ed1b6/hoomd/hpmc/ShapePolyhedron.h#L81-L274
https://github.com/glotzerlab/hoomd-blue/blob/800b589e23976d0ab3abf95263257d7d176ed1b6/hoomd/hpmc/IntegratorHPMCMono.h#L1575-L1589

As I said, after 3.0 is finalized I will help support community driven changes to enable this use-case, but our primary mission is to make HOOMD the best Python package that it can be.

**Comment by pabloferz** [comment]
Probably, my last comment didn't come up as I intended, I was trying to point out a general strategy that could be followed in the future. I understand how currently the disentanglement is no easy nor a priority. 

I understand your mission and appreciate the openness to support proposals like this one to improve this otherwise great piece of software.
