### ISSUE TITLE
Remove support for adding types

### ISSUE THREAD

**Issue by jglaser** [glotzerlab/hoomd-blue#664]
## Description

I am thinking about adding per-type tuning in HMPC. To avoid too much complexity, we could remove the support for dynamically changing the number of particle types when the state of the simulation is initialized, and only allow setting the number of particle types through the snapshot.

## Proposed solution

remove `slotNumTypesChange()` methods.

## Additional context

Will be more obvious in the context of an upcoming `Autotuner` related PR.

## Developer

perhaps. Removing functionality is easy :)

**Comment by joaander** [comment]
Related to #819 which needs to document the intended purpose of the snapshot save and reload commands.
