### ISSUE TITLE
Permissions Error on Downloads

### ISSUE THREAD

**Issue by rskye144** [glotzerlab/hoomd-blue#671]
## Description

Starting recently, when attempting to download the Singularity images for Glotzer Lab software, I get a 403 Forbidden error. The same error occurs when going to the website to view available downloads. I've attached an image of the error. I'm following exactly the instructions here: https://glotzerlab-software.readthedocs.io/en/latest/

## Script

```bash
curl -o software.simg https://glotzerlab.engin.umich.edu/downloads/glotzerlab/software-nompi.simg

```

## Output

![image](https://user-images.githubusercontent.com/57418606/85300134-2ea51c00-b474-11ea-8926-700fea5bc069.png)

## Expected output

A downloaded container.

**Comment by joaander** [comment]
Temporary workaround, access the file via `http://`. I am working to restore `https://` access.

**Comment by joaander** [comment]
`https://` access seems to be working how. I am not sure what the root cause was or what change fixed it.

**Comment by rskye144** [comment]
Thank you! I appreciate the help.
