### ISSUE TITLE
Premature simulation stop with HOOMD_WALLTIME_STOP and long initialization

### ISSUE THREAD

**Issue by InnocentBug** [glotzerlab/hoomd-blue#690]
Using HOOMD-blue in a walltime environment with HOOMD_WALLTIME_STOP may cause the code to end prematurely if the initialization takes long.
System tries to estimate how long it may take to reach the next `limit_multiple` time steps.

https://github.com/glotzerlab/hoomd-blue/blob/4324daf075836f229000e42b346fc997cd16754f/hoomd/System.cc#L529

and ends the run if it takes longer than the allowed HOOMD_WALLTIME_STOP.
If the system has a long initialization (eg. many O(1e3) observables are registered) the performance of the first time step is estimated as very low (eg. TPS 0.00002), but the actual TPS can be higher.

This underestimation of the performance can trigger ending the run prematurely.

**Comment by InnocentBug** [comment]
I disabled the estimation of the `limit_multiple` as a work around.
But maybe someone has a clever idea of how to prevent this....

**Comment by mphoward** [comment]
As a quick workaround, I would try doing
```py
hoomd.run_upto(warmup_steps)
try:
    hoomd.run_upto(actual_steps, limit_multiple=limit)
except hoomd.WalltimeLimitReached:
    pass
```
Not sure if there's a better fix to the actual time estimation.

**Comment by InnocentBug** [comment]
Sure that work around works as well.
And it is nicer, since it doesn't require c++ modifications.

**Comment by joaander** [comment]
Thanks for reporting. I am considering redesigning the walltime limit system for v3 and will take this behavior into account. If you have any other thoughts on what you would like to see in a new design, let me know.

**Comment by joaander** [comment]
Users will be able to implement their own run stop conditions in v3.
