### ISSUE TITLE
ComputeThermo handling of 0 DOF groups

### ISSUE THREAD

**Issue by joaander** [glotzerlab/hoomd-blue#708]
## Description

As of #691 ComputeThermo will now provide NaN (probably) for the kinetic temperature of a group with 0 degrees of freedom. We need to decide on the correct behavior, implement it and document it. See further discussion in the comment on #691.

**Comment by mphoward** [comment]
In MPCD, the temperature of a cell with 0 or 1 particles (so having 0 degrees of freedom because the cell temperature is relative to the center-of-mass velocity of the cell) is defined to be zero.

**Comment by joaander** [comment]
Thanks, that is a reasonable behavior that we could replicate.
