### ISSUE TITLE
Help on nlist GPU Nlist iterations

### ISSUE THREAD

**Issue by whitead** [glotzerlab/hoomd-blue#724]
## Description

We have a plugin written for hoomd that relies on how nlists are stored/used. Currently, how we interface is fragile and as things are changed in hoomd we have to update by noticing if things break. I was wondering if there is a recommended or standard way for iterating nlists in GPU. Here is our [current approach](https://github.com/ur-whitelab/hoomd-tf/blob/master/htf/TensorflowCompute.cu#L81). Do you have a recommendation for how best to accomplish this? Is there a standard way we should be doing iterating neighbor lists on GPU? Essentially we're reshaping the nlist to be a (batched) N x NN x 4 matrix to be used as a tensor in TensorFlow. Also, will this break in the 3.0 version being worked on? Thanks!

## Developer

Yes, I can help

**Comment by mphoward** [comment]
I don't follow exactly the role of `offset` and `batch_size` in your algorithm (probably they come somewhere farther up in your code, and you're using this to process only chunks of the neighbor list at a time), but this is essentially how the neighbor list is looped over in the pair force calculations. @joaander can comment more on v3, but this C++ API has been the same since I modified it in HOOMD v1.3, I believe.

My only suggestion would be in how you write out the result, but this is minor. Premultiply the `rmax` before passing to the kernel and simplify the write:
```c++
        if (rsq < rmaxsq && dest_idx < NN)
        {
            dest[(idx - offset) * NN + dest_idx] = make_scalar4(dx.x,dx.y,dz.z,static_cast<Scalar>(typej));
	    ++dest_idx;
        }
```
The `if` should be a more robust check than your mod. If you need real error checking, move `if(dest_idx < NN)` inside the loop to guard the write, but always increment `dest_idx` and save it to an error flag with an atomic op (as in the neighbor list code).

**Comment by whitead** [comment]
Thanks for you review @mphoward! Yes, offset and batch_size are to batch this operation instead of creating one giant nlist. Error checking is hard for me, so we check if it's full later on in TensorFlow. The mod is just because I thought it would be faster than branches caused by `if`, but perhaps your approach would be good to do real error checking on gpu.

Yes @joaander if you could offer any note on if/how I should update for v3, that would be great. It seems like some GPU stuff is being abstracted, but I haven't looked closely.

**Comment by mphoward** [comment]
No problem! Based on your comment, you will probably rarely branch so I would expect the performance difference to be negligible. We have to use this approach when building the neighbor list to make sure we don't overflow the allocated size (and to repeat the build if we do).

**Comment by joaander** [comment]
@whitead We are not planning on modifying the internal nlist storage format in v3. I don't foresee changing it in the near future, but we may if we determine that a new format would provide significantly better performance or features.

You might be interested in the local zero-copy data access APIs we are providing to Python: https://github.com/glotzerlab/hoomd-blue/pull/645 We have currently implement this for particle data, and we could follow the same pattern for forces, neighbor lists, etc...

**Comment by whitead** [comment]
Thank you @joaander! #645 looks very interesting. We have to make the following changes though to prepare hoomd data for Tensorflow (or jax):

1. convert scalar4/scalar3 into numpy/TF dtypes
2. unpack stuffed type for positions
3. reshape nlist to be fixed-size array (or ragged array)

Sometimes we don't have to copy, like for forces, and just need to do some casting. But I don't know how we could get the nlist, which I believe is not stored as a ragged or fixed-size array that can be used directly in Tensorflow or Jax. #645 would definitely simplify some code like for forces, but I'm not sure if it would help with positions/nlsit. Having access to charges/angles/dihedrals is definitely nice for additional inputs though.

**Comment by joaander** [comment]
@b-butler can give more details. In #645 we don't make any copies of the data, we just provide an array interface variable that can be used bun numpy/cupy/other python tools. We handle the position and type by providing strided array definitions. If non-strided copies are required, numpy or cupy can make those copies (e.g. numpy.ascontiguousarray).

We haven't yet considered the details of providing nlist data. As you say, HOOMD's internal format is unlikely to be directly useful to any other tool so zero-copy access is probably not possible. We would need to provide a preprocessed copy in any Python API. I'm not sure there is one format that would be universally usable. Tools like freud operate on an ordered list of pairs [(i, j]) - I assume that format is not suitable for Tensorflow.
