### ISSUE TITLE
Particles on MPI Rank boundaries not properly migrated before simulations start

### ISSUE THREAD

**Issue by tommy-waltmann** [glotzerlab/hoomd-blue#726]
## Description

Particles which are on boundaries of different MPI ranks are not owned by any rank before the start of a simulation. This creates memory errors when trying to query properties like forces or energies before the start of a simulation with MPI. I came across this error in unit testing pair potentials in the v3 API.

## Script

```python
import hoomd
import itertools
import numpy as np
from hoomd import md


lj = md.pair.LJ(md.nlist.Cell(), r_cut=2.5)
lj.params[('A', 'A')] = {'sigma': 0.5, 'epsilon': 0.0005}

dev = hoomd.device.CPU()

snap = hoomd.snapshot.Snapshot(dev.comm)

if snap.exists:
    box = [15, 15, 15, 0, 0, 0]
    snap.configuration.box = box
    snap.configuration.dimensions = 3

    snap.particles.N = 2
    snap.particles.types = ['A']

    # using these positions will not create errors in getting energies
    #snap.particles.position[:] = np.asarray([[-.75, 0, .1],
    #                                         [.75, 0, .1]])

    # using these positions will not create errors in getting energies
    #snap.particles.position[:] = np.asarray([[-.75, 0, -.1],
    #                                         [.75, 0, -.1]])

    # using these positions causes the error in getting energies
    snap.particles.position[:] = np.asarray([[-.75, 0, 0],
                                             [.75, 0, 0]])

sim = hoomd.simulation.Simulation(dev)

sim.create_state_from_snapshot(snap)

integrator = hoomd.md.Integrator(dt=1)
integrator.forces.append(lj)
integrator.methods.append(md.methods.Langevin(hoomd.filter.All(), kT=1, seed=1))

sim.operations.integrator = integrator
sim.operations.schedule()

# Error occurs because of this call
E0 = sim.operations.integrator.forces[0].energies
```

## Output

HOOMD-blue v2.9.2-2288-gd8e2cbd92 GPU [CUDA] (10.2) DOUBLE HPMC_MIXED MPI SSE SSE2
Compiled: 08/17/2020
Copyright (c) 2009-2019 The Regents of the University of Michigan.
Ranks 0-1: HOOMD-blue is running on the CPU
HOOMD-blue is using domain decomposition: n_x = 1 n_y = 1 n_z = 2.
**ERROR**:  (Rank 0): Particle with unique tag 1 is no longer in the simulation box.

Cartesian coordinates:
x: 0.75 y: 0 z: 0
Fractional coordinates:
f.x: 0.55 f.y: 0.5 f.z: 1
Local box lo: (-7.5, -7.5, -7.5)
          hi: (7.5, 7.5, 0)
Traceback (most recent call last):
  File "mpi-cell-list-error.py", line 46, in <module>
    E0 = sim.operations.integrator.forces[0].energies
  File "/nfs/turbo/bi-vislab/tomwalt/code/hoomd-blue/build/hoomd/md/force.py", line 58, in energies
    self._cpp_obj.compute(self._simulation.timestep)
RuntimeError: Error computing cell list
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------

## Expected output

A list of energies for each particle

## Configuration

This was run on the vislab using a GPU/MPI release build of hoomd-blue compiled from source

Platform:
- Linux
- CPU

Installation method:
- Compiled from source

Versions:
- Python version: 3.8.3
- **HOOMD-blue** version: Compiled from `feature/new-pair-force` branch of hoomd-blue. Commit hash is d8e2cbd92

## Developer

Provided a little guidance, I could do this. There would have to be some collaborative discussion on a good solution to this problem first.

**Comment by joaander** [comment]
It may not catch all corner cases, but a simple solution in this case would be to force a migration after initialization and after setting a snapshot.

**Comment by joaander** [comment]
This is mitigated now that we made `schedule` private and the user must call `run(0)` to schedule operations.
