### ISSUE TITLE
compilation error of v2.9.2 with cuda 11.1

### ISSUE THREAD

**Issue by peicho-petkov** [glotzerlab/hoomd-blue#727]
## Description

compilation error
/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(72): error: class template "cub::If" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(81): error: class template "cub::If" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(98): error: class template "cub::Equals" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(109): error: class template "cub::Equals" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(132): error: class template "cub::Log2" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(141): error: class template "cub::Log2" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(155): error: class template "cub::PowerOfTwo" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(170): error: class template "cub::IsPointer" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(178): error: class template "cub::IsPointer" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(195): error: class template "cub::IsVolatile" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(203): error: class template "cub::IsVolatile" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(222): error: class template "cub::RemoveQualifiers" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(231): error: class template "cub::RemoveQualifiers" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(237): error: class template "cub::RemoveQualifiers" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(243): error: class template "cub::RemoveQualifiers" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(256): error: invalid redeclaration of type name "cub::NullType"
/usr/local/cuda/include/cub/block/../util_type.cuh(256): here

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(275): error: class template "cub::Int2Type" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(290): error: class template "cub::AlignBytes" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(316): error: class "cub::AlignBytes<short4>" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(317): error: class "cub::AlignBytes<ushort4>" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(318): error: class "cub::AlignBytes<int2>" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(319): error: class "cub::AlignBytes<uint2>" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(320): error: class "cub::AlignBytes<long long>" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(321): error: class "cub::AlignBytes<unsigned long long>" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(322): error: class "cub::AlignBytes<float2>" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(323): error: class "cub::AlignBytes<double>" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(328): error: class "cub::AlignBytes<long2>" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(329): error: class "cub::AlignBytes<ulong2>" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(331): error: class "cub::AlignBytes<int4>" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(332): error: class "cub::AlignBytes<uint4>" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(333): error: class "cub::AlignBytes<float4>" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(334): error: class "cub::AlignBytes<long4>" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(335): error: class "cub::AlignBytes<ulong4>" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(336): error: class "cub::AlignBytes<longlong2>" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(337): error: class "cub::AlignBytes<ulonglong2>" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(338): error: class "cub::AlignBytes<double2>" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(339): error: class "cub::AlignBytes<longlong4>" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(340): error: class "cub::AlignBytes<ulonglong4>" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(341): error: class "cub::AlignBytes<double4>" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(343): error: class template "cub::AlignBytes" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(344): error: class template "cub::AlignBytes" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(345): error: class template "cub::AlignBytes" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(350): error: class template "cub::UnitWord" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(393): error: class "cub::UnitWord<float2>" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(408): error: class "cub::UnitWord<float4>" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(424): error: class "cub::UnitWord<char2>" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(438): error: class template "cub::UnitWord" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(439): error: class template "cub::UnitWord" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(440): error: class template "cub::UnitWord" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(461): error: "MAX_VEC_ELEMENTS" has already been declared in the current scope

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(469): error: class template "cub::CubVector" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(481): error: class template "cub::CubVector" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(494): error: class template "cub::CubVector" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(508): error: class template "cub::CubVector" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(604): error: class "cub::CubVector<char, 1>" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(604): error: argument list for class template "cub::CubVector" is missing

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(604): error: argument list for class template "cub::CubVector" is missing

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(604): error: argument list for class template "cub::CubVector" is missing

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(604): error: argument list for class template "cub::CubVector" is missing

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(604): error: argument list for class template "cub::CubVector" is missing

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(604): error: argument list for class template "cub::CubVector" is missing

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(604): error: class "cub::CubVector<char, 2>" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(604): error: argument list for class template "cub::CubVector" is missing

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(604): error: argument list for class template "cub::CubVector" is missing

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(604): error: argument list for class template "cub::CubVector" is missing

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(604): error: argument list for class template "cub::CubVector" is missing

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(604): error: argument list for class template "cub::CubVector" is missing

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(604): error: argument list for class template "cub::CubVector" is missing

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(604): error: class "cub::CubVector<char, 3>" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(604): error: argument list for class template "cub::CubVector" is missing

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(604): error: argument list for class template "cub::CubVector" is missing

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(604): error: argument list for class template "cub::CubVector" is missing

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(604): error: argument list for class template "cub::CubVector" is missing

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(604): error: argument list for class template "cub::CubVector" is missing

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(604): error: argument list for class template "cub::CubVector" is missing

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(604): error: class "cub::CubVector<char, 4>" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(604): error: argument list for class template "cub::CubVector" is missing

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(604): error: argument list for class template "cub::CubVector" is missing

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(604): error: argument list for class template "cub::CubVector" is missing

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(604): error: argument list for class template "cub::CubVector" is missing

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(604): error: argument list for class template "cub::CubVector" is missing

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(604): error: argument list for class template "cub::CubVector" is missing

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(605): error: class "cub::CubVector<signed char, 1>" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(605): error: argument list for class template "cub::CubVector" is missing

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(605): error: argument list for class template "cub::CubVector" is missing

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(605): error: argument list for class template "cub::CubVector" is missing

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(605): error: argument list for class template "cub::CubVector" is missing

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(605): error: argument list for class template "cub::CubVector" is missing

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(605): error: argument list for class template "cub::CubVector" is missing

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(605): error: class "cub::CubVector<signed char, 2>" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(605): error: argument list for class template "cub::CubVector" is missing

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(605): error: argument list for class template "cub::CubVector" is missing

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(605): error: argument list for class template "cub::CubVector" is missing

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(605): error: argument list for class template "cub::CubVector" is missing

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(605): error: argument list for class template "cub::CubVector" is missing

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(605): error: argument list for class template "cub::CubVector" is missing

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(605): error: class "cub::CubVector<signed char, 3>" has already been defined

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(605): error: argument list for class template "cub::CubVector" is missing

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(605): error: argument list for class template "cub::CubVector" is missing

/home/milchev/Downloads/hoomd-v2.9.2/hoomd/extern/cub/cub/block/specializations/../../block/../util_type.cuh(605): error: argument list for class template "cub::CubVector" is missing

Error limit reached.
Platform:
- Linux - ubuntu 20.4

Installation method:
- Compiled from source

gcc-9
cuda 11.1

Versions:
- **HOOMD-blue** version: 2.9.2

## Developer

comment out the line 9 of the hoomd-v2.9.2/hoomd/extern/neighbor/neighbor/UniformGrid.cu
```
// #include "hoomd/extern/cub/cub/cub.cuh"
```
inclusion of hoomd/extern/cub/cub/cub.cuh since it should be included from the cuda toolkit

P.P if there is a configuration method to suppress that inclusion I apologize for posting the issue report.

**Comment by mphoward** [comment]
Please try HOOMD 2.9.3 and let us know if that works for you. This compile error should already be fixed there.

**Comment by peicho-petkov** [comment]
I had tried the master branch before I have submitted the issue. The 
line is still there...

BUT I see that in HOOMD 2.9.3 is correct.

Thanks a lot!

Best regards,

Peicho.
