### ISSUE TITLE
HPMC MPI error for large size asymmetry

### ISSUE THREAD

**Issue by scmartin** [glotzerlab/hoomd-blue#756]
## Description

While running HPMC simulations on multiple CPU's I'm having problems with simulations crashing. The system I am simulating is a fluid of particles with a single solute particle of a different size. If the solute particle is roughly the same size as the fluid particles, the solutions work fine. However if the solute particle is considerably larger (~20x) than the fluid particles, the simulation crashes with a RuntimeError: Error during communication.

## Script

```python
import hoomd
import hoomd.hpmc as hpmc
import numpy as np
import argparse

parser = argparse.ArgumentParser(description='start hoomd simulation')
parser.add_argument('-L', dest='L', type=float, required=True,
                    help='side length of square wall', metavar='wall length')
parser.add_argument('-rho', dest='rho', type=float, required=True,
                    help='target density', metavar='target density')
parser.add_argument('-p', dest='prod_cycles', type=int, required=True,
                    help='number of production cycles', metavar='prod cycles')
args = parser.parse_args()
L = args.L
rho = args.rho
prod_cycles = args.prod_cycles


# This section calculates the excess volume for the wall using
# SPT and then sets the lattice spacing to achieve the correct
# bulk density

y = 0.25*np.pi*rho             # target packing fraction
v_0 = 0.5*(1.0-y)/(1.0+y)      # flat wall SPT excess volume
h_v = 0.125*(1.0-y)**2/(1.0+y) # SPT curvature correction
H_bar = 0.5*np.pi/L            # average curvature of the square wall
vex = v_0 + h_v*H_bar          # excess volume per unit length of wall


# Calculate the lattice spacing to use

n_init = 100                             # number of lattice points to use
p = np.poly1d([rho*n_init**2, +4.0*vex*n_init*rho, # polynomial in lattice
               -(rho*L**2 + n_init**2), 0, L**2])  # constant
a = np.roots(p).max()  # use the largest root for the lattice spacing


# Initialize HOOMD

hoomd.context.initialize('--mode=cpu');


#Initialize the system the first time around
system = hoomd.init.create_lattice(unitcell=hoomd.lattice.sq(a=a),
                                   n=n_init);

mc = hoomd.hpmc.integrate.sphere(seed=1, move_ratio=1.0, nselect=1);
mc.shape_param.set('A', diameter=1.0)

# Add wall particle
system.particles.types.add(name='B')
mc.shape_param.set('B', diameter=L*2.0)

# Remove fluid particles which overlap wall particle
delete_me = []
for i in system.particles:
    if (i.position[0]**2+i.position[1]**2 >= 0.5+L):
        delete_me.append(i.tag)

for i in delete_me[::-1]:
    system.particles.remove(i)

system.particles.add('B')
mc.set_params(d={'A':0.5/rho, 'B':0})

hoomd.option.set_notice_level(6)

bins = 500
r_max=50

period=100
try:
    hoomd.run_upto(prod_cycles, limit_multiple=period)
except hoomd.WalltimeLimitReached:
    pass

```
## Output

> Running on nodes r14r38n03 using 4 cores on each node
> density = 0.4
> wall radius = 20.0
> HOOMD-blue v2.9.2-17-g54b0351 CUDA (10.1) DOUBLE HPMC_MIXED MPI SSE SSE2 SSE3 SSE4_1 SSE4_2 AVX AVX2
> Compiled: 08/10/20
> Copyright (c) 2009-2019 The Regents of the University of Michigan.
> -----
> You are using HOOMD-blue. Please cite the following:
> * J A Anderson, J Glaser, and S C Glotzer. "HOOMD-blue: A Python package for
>   high-performance molecular dynamics and hard particle Monte Carlo
>   simulations", Computational Materials Science 173 (2020) 109363
> -----
> -----
> You are using HPMC. Please cite the following:
> * J A Anderson, M E Irrgang, and S C Glotzer. "Scalable Metropolis Monte Carlo
>   for simulation of hard shapes", Computer Physics Communications 204 (2016) 21
>   --30
> -----
> CUDA driver version is insufficient for CUDA runtime version
> Ranks 0-3: HOOMD-blue is running on the CPU
> hoomdjob.py:042  |                 -(rho*L**2 + n_init**2), 0, L**2])  # constant
> a = np.roots(p).max()  # use the largest root for the lattice spacing
> 
> 
> # Initialize HOOMD
> 
> hoomd.context.initialize('--mode=cpu');
> 
> 
> #Initialize the system the first time around
> system = hoomd.init.create_lattice(unitcell=hoomd.lattice.sq(a=a),
> hoomdjob.py:052  |  system = hoomd.init.create_lattice(unitcell=hoomd.lattice.sq(a=a),
>                                    n=n_init);
> HOOMD-blue is using domain decomposition: n_x = 2 n_y = 2 n_z = 1.
> 2 x 2 x 1 local grid on 1 nodes
> notice(2): Group "all" created containing 10000 particles
> hoomdjob.py:055  |  mc = hoomd.hpmc.integrate.sphere(seed=1, move_ratio=1.0, nselect=1);
> hoomdjob.py:072  |  mc.set_params(d={'A':0.5/rho, 'B':0})
> ** starting run **
> Traceback (most recent call last):
>   File "hoomdjob.py", line 81, in <module>
>     hoomd.run_upto(prod_cycles, limit_multiple=period)
>   File "/panfs/pfs.local/work/laird/sether35/hoomd-blue-wallmuVT/hoomd-blue/build_wall_muVT/hoomd/__init__.py", line 242, in run_upto
>     run(n_steps, **keywords);
>   File "/panfs/pfs.local/work/laird/sether35/hoomd-blue-wallmuVT/hoomd-blue/build_wall_muVT/hoomd/__init__.py", line 201, in run
>     context.current.system.run(int(tsteps), callback_period, callback, limit_hours, int(limit_multiple));
> RuntimeError: Error during communication
> Traceback (most recent call last):
>   File "hoomdjob.py", line 81, in <module>
>     hoomd.run_upto(prod_cycles, limit_multiple=period)
>   File "/panfs/pfs.local/work/laird/sether35/hoomd-blue-wallmuVT/hoomd-blue/build_wall_muVT/hoomd/__init__.py", line 242, in run_upto
>     run(n_steps, **keywords);
>   File "/panfs/pfs.local/work/laird/sether35/hoomd-blue-wallmuVT/hoomd-blue/build_wall_muVT/hoomd/__init__.py", line 201, in run
>     context.current.system.run(int(tsteps), callback_period, callback, limit_hours, int(limit_multiple));
> RuntimeError: Error during communication
> Traceback (most recent call last):
>   File "hoomdjob.py", line 81, in <module>
>     hoomd.run_upto(prod_cycles, limit_multiple=period)
>   File "/panfs/pfs.local/work/laird/sether35/hoomd-blue-wallmuVT/hoomd-blue/build_wall_muVT/hoomd/__init__.py", line 242, in run_upto
>     run(n_steps, **keywords);
>   File "/panfs/pfs.local/work/laird/sether35/hoomd-blue-wallmuVT/hoomd-blue/build_wall_muVT/hoomd/__init__.py", line 201, in run
>     context.current.system.run(int(tsteps), callback_period, callback, limit_hours, int(limit_multiple));
> RuntimeError: Error during communication
> Traceback (most recent call last):
>   File "hoomdjob.py", line 81, in <module>
>     hoomd.run_upto(prod_cycles, limit_multiple=period)
>   File "/panfs/pfs.local/work/laird/sether35/hoomd-blue-wallmuVT/hoomd-blue/build_wall_muVT/hoomd/__init__.py", line 242, in run_upto
>     run(n_steps, **keywords);
>   File "/panfs/pfs.local/work/laird/sether35/hoomd-blue-wallmuVT/hoomd-blue/build_wall_muVT/hoomd/__init__.py", line 201, in run
>     context.current.system.run(int(tsteps), callback_period, callback, limit_hours, int(limit_multiple));
> RuntimeError: Error during communication
> --------------------------------------------------------------------------
> MPI_ABORT was invoked on rank 3 in communicator MPI_COMM_WORLD
> with errorcode 16.
> 
> NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
> You may or may not see output from other processes, depending on
> exactly when Open MPI kills them.
> --------------------------------------------------------------------------
> [r14r38n03:127279] 3 more processes have sent help message help-mpi-api.txt / mpi-abort
> [r14r38n03:127279] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
> 

## Configuration

Platform:
- Linux (CentOS 7)

Installation method:
- Compiled from source (with modifications for muVT / wall   #665 though these simulations do not use the grand canonical updater or the field.wall feature)

Versions:
- Python version: 3.7
- **HOOMD-blue** version: 2.9.2 (with above noted modifications)

**Comment by joaander** [comment]
The MPI domain decomposition is designed to parallelized over systems where there are many of the largest particle. The largest particle size in the system sets the width of the ghost layer communicated between neighboring domains, so the largest particle size in the system must be smaller than half the smallest domain length.

**Comment by scmartin** [comment]
That makes sense. Thanks for the clarification.

Seth
