### ISSUE TITLE
More Tab Completion

### ISSUE THREAD

**Issue by j-proc** [glotzerlab/hoomd-blue#757]
## Description

More extensive tab completion support. Opening this issue to keep track of the current status of tab completion by various users and discussion on possible solutions.

## Proposed solution

It seems like pybind11 considered better support in https://github.com/pybind/pybind11/issues/945 but ultimately hasn't implemented it due to PEP575 being rejected. I haven't seen further discussion.

However it should be possible on the python side to add wrappers and even type information via signature and text_signature dunders.

## Additional context

Increasingly common usage of jupyter notebooks makes it likely that many new users would expect tab completion to work fairly extensively. I would also consider this a quality of life improvement for current users.

Might fit well with HOOMD v3 python interface improvements, but should not delay release as no API changes would be needed.

**Comment by phcerdan** [comment]
I am interested on this as well.

> However it should be possible on the python side to add wrappers and even type information via signature and text_signature dunders.

Do you have an example on this? I would pursue whatever it takes to get ipython to autocomplete member functions and variables.

**Comment by phcerdan** [comment]
I found that you can `import rlcompleter`
and ipython will autocomplete members from pybind11.

**Comment by joaander** [comment]
I admit I don't understand the difficulties here. The vast majority of HOOMD's user-facing API is implemented in pure Python. Users should almost never need to tab-complete pybind11 objects. However, I don't use tab-completion myself in any coding environments so I don't know what does and doesn't work.

**Comment by joaander** [comment]
I don't think we need to tab complete low level, non-user-facing APIs. Reopen if you have a good use-case for this with the v3 API.
