### ISSUE TITLE
Add examples back into documentation. 

### ISSUE THREAD

**Issue by mikemhenry** [glotzerlab/hoomd-blue#763]
Once #743 gets merged in, we will need to add back in some examples. I'm going to use this issue to track this.  

- [x] example in `sphinx-doc/index.rst`
- [x] example in `README.md`
- [ ] example in `hoomd/md/constrain.py`

**Comment by joaander** [comment]
Whatever example was in `constrain.py` will be covered in a full tutorial on constraints (to be written https://github.com/glotzerlab/hoomd-examples/issues/38).
