### ISSUE TITLE
Rename move_ratio in HPMC

### ISSUE THREAD

**Issue by vyasr** [glotzerlab/hoomd-blue#777]
## Description

The `move_ratio` property of HPMC integrators is confusingly named. It is documented as the "ratio of translation moves to rotation moves", but really it's the percentage of moves that are translational: the actual check that is performed is `bool move_type_translate = !shape_i.hasOrientation() || (move_type_select < m_move_ratio)`. If it were truly a ratio, the default value of 0.5 would imply 1 translational move for every 2 rotational moves, but it actually implies a 1:1 ratio.

## Proposed solution

We should rename this property in v3. Something like `translational_move_probability` would more accurately reflect the meaning.

## Developer

I'm happy to help with this, although it might also be natural to fold into other ongoing efforts.

**Comment by joaander** [comment]
Yes, this is a good change to make. Feel free to start on this any time, it doesn't interfere with any other ongoing work.

**Comment by joaander** [comment]
#779 makes some of the changes, but there are more places to fix.
