### ISSUE TITLE
Improve documentation for CustomAnalyzer and similar classes

### ISSUE THREAD

**Issue by joaander** [glotzerlab/hoomd-blue#782]
## Description

`CustomAnalyzer`, `CustomUpdater`, and `CustomTuner` need improved documentation. Specifically, the `__init__` method needs to be documented. Additionally, `CustomAnalyzer`, `CustomUpdater`, and `CustomTuner` could provide additional overview and context in their docstrings.

## Motivation and context

In the current docs, `CustomAnalyzer` includes only stub documentation that points to `_CustomOperation`. `_CustomOperation` states "This object should not be instantiated or subclassed by an user." and points the reader to `Action`. The `Action` clearly describes what an `Action` is and how to create one, but does not mention how to actually use one with a `CustomAnalyzer`, `CustomUpdater`, or `CustomTuner`.

**Comment by b-butler** [comment]
Good catch.
