### ISSUE TITLE
Build with C++14 for Thrust

### ISSUE THREAD

**Issue by bdice** [glotzerlab/hoomd-blue#784]
## Description

I am using a new version of Thrust (`THRUST_VERSION 100909`) that requires C++14. Compiler support is available in gcc 5, clang 3.4, nvcc 9, xlc 13.1.2. https://en.cppreference.com/w/cpp/compiler_support

## Proposed solution

Upgrade CMake files to use `--std=c++14` instead of `c++11`.

## Additional context

@joaander mentioned the potential drawback of no `manylinux` support with C++14. If that is relevant, there are newer images `manylinux2014` and `manylinux2020` that can be used with full C++14 support. https://cibuildwheel.readthedocs.io/en/stable/cpp_standards/#manylinux1-and-c14

## Developer

@joaander recommends investigating this after releasing 3.0 beta 1.

**Comment by mphoward** [comment]
This may become a necessary requirement with future NVIDIA toolkits. I believe CUB deprecated C++11 in the version that shipped with CUDA 11.0 (1.9.9), and it will drop C++11 completely in a later release. This may be part of your thrust requirement, or in addition to!

**Comment by joaander** [comment]
When I started writing HOOMD, "C++1x" (the prototype to C++11) was only in an early draft state and only supported in bleeding edge compilers.
