### ISSUE TITLE
Walltime limited run_upto() followed by run()

### ISSUE THREAD

**Issue by scmartin** [glotzerlab/hoomd-blue#791]
## Description

I am trying to create restartable jobs that analyzers that run on the last step when the walltime is reached. To make the analyzer run, I use a `try` statement with `run_upto()` with the same `period` as the analyzer; when it catches the _WalltimeLimitReached_ exception, the `except` statement performs a `run(1)`. It works for large systems, but it seems that there is a lower limit to the systems size, at which point I get the output below.

## Script

```python
import hoomd
import hoomd.hpmc as hpmc
import numpy as np

hoomd.context.initialize('--mode=cpu');

prod_cycles = 1000000

a = 1.8
n_init=50 # This works
# n_init=10 # This throws a second WalltimeLimitReached exception while handling the first one
system = hoomd.init.create_lattice(unitcell=hoomd.lattice.sq(a=a),
                                   n=n_init);

mc = hoomd.hpmc.integrate.convex_spheropolygon(seed=np.random.randint(20000), move_ratio=1.0);
mc.shape_param.set('A', vertices=[(0,0)], sweep_radius=0.5)
mc.set_params(d=0.5, a=0)

period = 100
try:
    hoomd.run_upto(prod_cycles, limit_multiple=period)
except hoomd.WalltimeLimitReached:
    hoomd.run(1)

```

## Output

** starting run **
Time 00:00:10 | Step 6416 / 1000000 | TPS 641.524 | ETA 00:25:48
Time 00:00:20 | Step 12830 / 1000000 | TPS 641.318 | ETA 00:25:39
notice(2): Ending run before HOOMD_WALLTIME_STOP - current time step: 17600
Time 00:00:27 | Step 17600 / 1000000 | TPS 641.679 | ETA 00:25:30
Average TPS: 641.488

notice(2): -- HPMC stats:
notice(2): Average translate acceptance: 0.733109
notice(2): Trial moves per second:        256593
notice(2): Overlap checks per second:     4.10895e+06
notice(2): Overlap checks per trial move: 16.0135
notice(2): Number of overlap errors:      0
** starting run **
notice(2): Ending run before HOOMD_WALLTIME_STOP - current time step: 17600
Time 00:00:27 | Step 17600 / 17601 | TPS 0 | ETA -2562047:-47:-16
Average TPS: 0

notice(2): -- HPMC stats:
notice(2): Average translate acceptance: 0
notice(2): Trial moves per second:        0
notice(2): Overlap checks per second:     0
notice(2): Overlap checks per trial move: -nan
notice(2): Number of overlap errors:      0
Traceback (most recent call last):
  File "newjob.py", line 20, in <module>
    hoomd.run_upto(prod_cycles, limit_multiple=period)
  File "/panfs/pfs.local/work/laird/sether35/hoomd-blue-wallmuVT/hoomd-blue/build_HPMC_only/hoomd/__init__.py", line 242, in run_upto
    run(n_steps, **keywords);
  File "/panfs/pfs.local/work/laird/sether35/hoomd-blue-wallmuVT/hoomd-blue/build_HPMC_only/hoomd/__init__.py", line 201, in run
    context.current.system.run(int(tsteps), callback_period, callback, limit_hours, int(limit_multiple));
hoomd._hoomd.WalltimeLimitReached: HOOMD_WALLTIME_STOP reached

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "newjob.py", line 22, in <module>
    hoomd.run(1)
  File "/panfs/pfs.local/work/laird/sether35/hoomd-blue-wallmuVT/hoomd-blue/build_HPMC_only/hoomd/__init__.py", line 201, in run
    context.current.system.run(int(tsteps), callback_period, callback, limit_hours, int(limit_multiple));
hoomd._hoomd.WalltimeLimitReached: HOOMD_WALLTIME_STOP reached

## Expected output

** starting run **
Time 00:00:10 | Step 245 / 1000000 | TPS 24.4234 | ETA 11:22:14
Time 00:00:20 | Step 488 / 1000000 | TPS 24.2876 | ETA 11:25:53
notice(2): Ending run before HOOMD_WALLTIME_STOP - current time step: 500
Time 00:00:20 | Step 500 / 1000000 | TPS 24.3867 | ETA 11:23:05
Average TPS: 24.3562

notice(2): -- HPMC stats:
notice(2): Average translate acceptance: 0.73303
notice(2): Trial moves per second:        243559
notice(2): Overlap checks per second:     3.31034e+06
notice(2): Overlap checks per trial move: 13.5915
notice(2): Number of overlap errors:      0
** starting run **
Time 00:00:20 | Step 501 / 501 | TPS 23.0144 | ETA 00:00:00
Average TPS: 22.8959

notice(2): -- HPMC stats:
notice(2): Average translate acceptance: 0.7355
notice(2): Trial moves per second:        227376
notice(2): Overlap checks per second:     3.09934e+06
notice(2): Overlap checks per trial move: 13.6309
notice(2): Number of overlap errors:      0
** run complete **

## Configuration

Platform:
- Linux
- CPU

Installation method:
- Compiled from source

Versions:
- Python version: 3.7.3
- **HOOMD-blue** version: v2.9.2-17-g54b0351 CUDA (10.1) DOUBLE HPMC_MIXED MPI SSE SSE2 SSE3 SSE4_1 SSE4_2 AVX AVX2

**Comment by joaander** [comment]
Thanks for the detailed report. HOOMD 3.0 will solve one of these issues. In HOOMD 3.0, `run()` will trigger writers at the end of the loop: see #574 and #783.

The root cause for the behavior you describe is likely the same as in #690. I don't currently have any good ideas on how HOOMD can provide the walltime stop behavior in a way that will work well in all cases. #783 removes it for now, but we can add it back in a later beta if we can determine a good design. 

In HOOMD 3.0, `run()` has minimal overhead, so custom user-provided walltime handling is how feasible. For example:
```
while time.time() < stop and sim.timestep < 1000000:
    sim.run(10000)
```

Do you have any suggestions for an alternate design?

**Comment by scmartin** [comment]
I saw #690 but my thought process was that since the larger systems take longer for each step, if it was the same issue the larger systems would be more likely to exhibit this behavior, rather than the small systems, which is what I'm observing. I haven't dug into the exception handling, but I didn't realize that `run()` can also raise the walltime exception. But since it defaults to limit_multiple=1, I am really surprised that the small systems are raising the exception, but the larger ones are not.

**Comment by joaander** [comment]
There are a number of problems with the implementation. The code in `run` and `run_upto` estimate TPS with a timer. That timer is created during `init.*`. If there is a long time between `init` and the first time step, then the first time step will appear very slow. Note that initializing the particle sorter takes time, so the first time step will always be very slow. `run` continues to use the same timer in subsequent calls to `run`, so any gap between calls to `run` will cause the first timestep to report low TPS. 

`run` samples the TPS over multiple 10-second intervals and uses a rolling median to project whether the run can make it to the next `limit_multiple` steps before the given walltime. When there aren't enough 10-second samples, that median is not effective at smoothing out noise.

I don't know if or how any of this explains your particular case, but I do think that any future solution should be based solely on a less-than time check like I showed in the example. This would remove the chances for any inconsistencies that arrive from estimating performance. The API debate for v3 is whether or not `run` should provide a means to end early at all - and if yes, what form would that take? Simplicity is good and the current implementation in #783 allows for the user to run in smaller chunks of time and make control flow decisions based on whatever conditions are needed.

**Comment by joaander** [comment]
I do not plan on offering time based conditions to stop the run loop in the v3.0 API. In v3.0, the overhead for calling run() is small enough that users can implement their own conditions for stopping in their scripts as shown above.
