### ISSUE TITLE
BoxMC Weighted Selection

### ISSUE THREAD

**Issue by bdice** [glotzerlab/hoomd-blue#810]
## Description

PR #758 refactors BoxMC for the v3 API. I noticed the implementation of the weighted move selection seems like it could made more efficient.

## Proposed solution

The `UpdaterBoxMC::update` method should compute the `weight_sums` vector in advance (instead of for every move) with `std::partial_sum`. This vector should be stored as a class member. The move can be selected using `std::lower_bound`. This should reduce the amount of computations on each step, as well as make the computation more general for different move types.

Here is a code example: https://godbolt.org/z/7oYTo9

## Additional context

To be addressed after #758.

@joaander notes,
> Dynamic memory allocations are very expensive and should be avoided every time step. We can keep the `std::vector`s as member variables and reuse them. Better yet, we should implement a re-usable `WeightedSelection` class in `RandomNumbers.h` and `BoxMC` could keep one of these classes as a member variable.

## Developer

I can help contribute this improvement. A draft of the code is linked above.

**Comment by lyrivera** [comment]
@bdice please add me as a reviewer when you open the corresponding PR

**Comment by joaander** [comment]
Fixed in #897.
