### ISSUE TITLE
Property exceptions for unattached simulations

### ISSUE THREAD

**Issue by bdice** [glotzerlab/hoomd-blue#812]
## Description

While writing my first script using the HOOMD v3 API, I was tripped up a few times by objects returning `None` for a property when accessing information that isn't available until the simulation is attached. For example, `mc.type_shapes` isn't available until after calling `sim.run(timesteps)`. Though the `type_shapes` data is formally "defined" as soon as the shape definitions have been provided, it requires attachment and a round trip through C++ before that information can be accessed. I noticed that `None` is returned by many objects, such as other properties of an HPMC integrator like `mc.overlaps` but also things like `sim.state` before a state is created. I found this confusing, and would have expected errors instead of `None`.

For example, I expected this to work:
```python
mc = hoomd.hpmc.integrate.Ellipsoid(seed=42, d=0.1, a=0.1)
mc.shape['A'] = {'a': 3., 'b': 1., 'c': 1.}
print(mc.type_shapes)  # returns None
```

## Proposed solution

Raise an exception instead of returning `None` for properties that require C++ attachment. I suggested `AttributeError` but @joaander indicated there are reasons to avoid this (something to do with how Python interprets the failure?). @b-butler proposed creating a custom error. I would recommend creating an exception derived from `RuntimeError` (despite my claim in #811 that we sometimes overuse `RuntimeError` 😄) because I couldn't find a better option. Perhaps the class could have some standard boilerplate message with only minimal specification for the current class attribute name.

```python
class AttachedDataError(RuntimeError):
    """Raised when data is inaccessible until the simulation is attached."""
    def __init__(self, data_name):
        self.data_name = data_name

    def __str__(self):
        return f"The property {self.data_name} is unavailable until the simulation runs for 0 or more steps."

# Then use it like this:
@property
def property_name(self):
    if self._attached:
        return self._cpp_obj.getProperty()
    else:
        raise AttachedDataError('property_name')
```

From discussion with @joaander and @b-butler, the design decision to return `None` is partly informed by the logging infrastructure. The loggers would need to detect whatever exception is raised and log `None` instead.

## Additional context

@joaander noted that this pattern can be found easily by searching for `self._attached` in the code base.

**Comment by joaander** [comment]
I attempted to replicate the annoying behavior with `AttributeError` I described and wasn't able to. It may only occur in combination with pybind or with `__getattr__` and pybind. I know I run into the issue when the param dict machinery calls this code when the C++ object does not have the attr:
```
    def __getattr__(self, attr):
        if self._attached:
            return getattr(self._cpp_obj, attr)
```

I still think we need a custom error class because we need to be able to detect quantities unavailable for logging separately from errors where the property is not even defined. Users would expect an attribute error when they attempt to log a property that does not exist (i.e. due to a typo).
```
log = hoomd.Logger()
log.add(thermo, quantities=['not_an_attr'])
log.log() # raises AttributeError 'ThermoDynamicQuantities' has no attribute 'not_an_attr'
```
However, I think we can safely use `AttributeError` as the base class for this

**Comment by vyasr** [comment]
Agree that a custom error class is important to provide the users with sufficiently detailed information on _why_ things failed. If extending `AttributeError` works, great, if not, it's not the end of the world to subclass a different exception.

**Comment by joaander** [comment]
@b-butler mentioned that `AttributeError` will not work because it Python will interpret this as a property that does not exist. That would confuse users because the property itself exists, it just doesn't have a well-defined value.
