### ISSUE TITLE
Run won't stop when interrupting Jupyter kernel

### ISSUE THREAD

**Issue by bdice** [glotzerlab/hoomd-blue#813]
## Description

I ran the HPMC tutorial. During the call to `sim.run(2e6)`, I tried to stop the Jupyter kernel, but the SIGINT doesn't seem to pass through to HOOMD. I used the "stop kernel" button which is supposed to trigger a `KeyboardInterrupt`. I tested this with Jupyter Notebook and Jupyter Lab and saw the problem in both. The SIGINT / `KeyboardInterrupt` stops the run as expected in a Python shell and in an IPython shell. It's entirely possible this is a bug in Jupyter, I don't know.

## Script

See here: https://github.com/glotzerlab/hoomd-examples/blob/v3-api/00-Introducing-HOOMD-blue/06-Equilibrating-the-System.ipynb

## Output

Expected the run to stop. It did not.

```
[I 14:50:41.831 LabApp] Kernel interrupted: e051d5c2-ab07-4f30-bd18-26476a5d27d2
```

## Additional context

This snippet might help debug things. Be aware that it catches all signals. If you run `time.sleep(10)`, it captures and prints the signals as they arrive during the sleep. However, I didn't see it printing the captured signals during `sim.run`. Could be related?

```python
import signal
import time

def sighandler(signal, frame):
    print("signal", signal, frame)
    return

catchable_sigs = set(signal.Signals)
for sig in catchable_sigs:
    try:
        signal.signal(sig, sighandler)
        print(f"Setting {repr(sig)}, {sig}")
    except (ValueError, OSError, RuntimeError) as m:
        print(f"Skipping {repr(sig)}, {sig}")
```

## Configuration

Platform:
- WSL2 (Ubuntu), CPU

Installation method:
- Compiled from source

Jupyter / related package versions:
```
ipython                   7.18.1           py38h1cdfbd6_0    conda-forge
jupyter-server-proxy      1.5.0                      py_0    conda-forge
jupyter_client            6.1.7                      py_0    conda-forge
jupyter_core              4.6.3            py38h32f6830_2    conda-forge
jupyter_sphinx            0.3.1            py38h32f6830_0    conda-forge
jupyterlab                2.2.8                      py_0    conda-forge
jupyterlab_code_formatter 1.3.6                      py_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         1.2.0                      py_0    conda-forge
```

Versions:
- Python version: 3.8.3
- **HOOMD-blue** version: 3.0.0-beta1

**Comment by joaander** [comment]
I tested without Jupyter with this script:
```
import hoomd

sim = hoomd.Simulation(device=hoomd.device.CPU())
sim.create_state_from_gsd('random.gsd')

sim.run(1e9)
```
Ctrl-C works as expected.

However, when I add install the python signal handler:
```
import hoomd
import signal
import time

def sighandler(signal, frame):
    print("signal", signal, frame)
    return

catchable_sigs = set(signal.Signals)
for sig in catchable_sigs:
    try:
        signal.signal(sig, sighandler)
        print(f"Setting {repr(sig)}, {sig}")
    except (ValueError, OSError, RuntimeError) as m:
        print(f"Skipping {repr(sig)}, {sig}")

sim = hoomd.Simulation(device=hoomd.device.CPU())
sim.create_state_from_gsd('random.gsd')

sim.run(1e9)
```
The message is not printed.

The cause for this is how Python handles signals: https://docs.python.org/3/library/signal.html#execution-of-python-signal-handlers
> A Python signal handler does not get executed inside the low-level (C) signal handler. Instead, the low-level signal handler sets a flag which tells the virtual machine to execute the corresponding Python signal handler at a later point(for example at the next bytecode instruction). This has consequences:

> A long-running calculation implemented purely in C (such as regular expression matching on a large body of text) may run uninterrupted for an arbitrary amount of time, regardless of any signals received. The Python signal handlers will be called when the calculation finishes.

So, the message should print when `run()` finishes.

HOOMD also ignores the signal in this test case. I assume because python overwrote hoomd's signal handler and doesn't call the previous handler. HOOMD installs the signal handler on import.

**Comment by joaander** [comment]
Now, what is Jupyter doing. I added a debug print when HOOMD catches a signal and ran this test on the command line:
```
>>> import signal
>>> signal.getsignal(signal.SIGINT)
<built-in function default_int_handler>
>>> 
KeyboardInterrupt
>>> import hoomd
>>> signal.getsignal(signal.SIGINT)
<built-in function default_int_handler>
>>> HOOMD caught SIGINT

KeyboardInterrupt
>>> 
```
Works as expected, except that `getsignal` doesn't tell us about HOOMD's handler :(  It is supposed to return `None`: https://docs.python.org/3/library/signal.html#signal.getsignal

In Jupyter, interrupting this produces the debug message (as the only cell in the notebook and after a clean kernel restart):
```
import hoomd
for i in range(100000000000000):
    pass
```

However, if I rerun the cell or move the for loop into its own cell, HOOMD does not print the debug message. It would appear that Jupyter resets the signal at the start of every cell. `getsignal` agrees when the signal is set to a python function:
```
import signal
import time

def sighandler(signal, frame):
    print("signal", signal, frame)
    return

catchable_sigs = set(signal.Signals)
for sig in catchable_sigs:
    try:
        signal.signal(sig, sighandler)
        print(f"Setting {repr(sig)}, {sig}")
    except (ValueError, OSError, RuntimeError) as m:
        print(f"Skipping {repr(sig)}, {sig}")
signal.getsignal(signal.SIGINT)
```
Outputs:
```
<function __main__.sighandler(signal, frame)>
```

Next cell:
```
signal.getsignal(signal.SIGINT)
```
Outputs:
```
<function _signal.default_int_handler>
```
I don't know whether this is documented, is a feature, or is a bug.

**Comment by vyasr** [comment]
For context, this is not just a HOOMD problem. I've run into this before with our packages like freud (try running and killing an RDF with a large number of  bins, for instance; the freud-paper-figures notebook is a good example) and with external packages like pandas (trying to run some dumb first-pass implementations using unoptimized pandas code instead of the proper functions for a particular task can easily bottleneck for very large tables). In some of these cases restarting the kernel is invariably the only reliable solution.

**Comment by joaander** [comment]
Right, but HOOMD explicitly installs a signal handler to handle this. The problem here seems to be that Jupyter is "helping" somehow by resetting the handler at the start of every cell. We can work around this by re-installing the signal handler at the start of every run.

**Comment by vyasr** [comment]
Right, I think Jupyter's signal handling logic is conflicting with HOOMD's. But looks like you found a solution, so great 👍
