### ISSUE TITLE
Add example for logging type_shapes

### ISSUE THREAD

**Issue by bdice** [glotzerlab/hoomd-blue#814]
## Description

I would like a code example for logging `mc.type_shapes` data in the documentation. This may also be addressed in the logging tutorial that @joaander is planning. If possible, I would suggest that we include a snippet in the docs as well as the tutorial.

It would also be nice to show how to load a saved HPMC integrator state with `from_state`.

**Comment by joaander** [comment]
Where would you expect to find a mini-example in the documentation? In the base class HPMC integrator?
