### ISSUE TITLE
Inconsistency with filter and filter_

### ISSUE THREAD

**Issue by bdice** [glotzerlab/hoomd-blue#815]
## Description

It seems like there are some issues with Sphinx rendering `filter` and `filter_` correctly in the docstrings.

Example: https://hoomd-blue.readthedocs.io/en/v3.0.0-beta.1/module-hoomd-write.html#hoomd.write.GSD

It looks like this is written correctly in the source, but Sphinx is parsing it differently than anticipated.
https://github.com/glotzerlab/hoomd-blue/blob/376eab8c92b4b4c62b21abb68222efe06a6b81b9/hoomd/write/gsd.py#L23

There are also cases where the argument name is `filter` and might need to be changed to `filter_` for consistency. Some instances grepped with `"def.*\(.*filter[^_]"` (:warning: this regex won't catch instances where `filter` is on a different line than `def`):

https://github.com/glotzerlab/hoomd-blue/blob/376eab8c92b4b4c62b21abb68222efe06a6b81b9/hoomd/md/methods.py#L100
https://github.com/glotzerlab/hoomd-blue/blob/376eab8c92b4b4c62b21abb68222efe06a6b81b9/hoomd/md/force.py#L296
https://github.com/glotzerlab/hoomd-blue/blob/376eab8c92b4b4c62b21abb68222efe06a6b81b9/hoomd/state.py#L375

**Comment by joaander** [comment]
I think at one point we were using `filter_` in argument lists but have now changed it to `filter` - those docs need to be updated. @bdice do you think we need to be concerned about using `filter` in argument lists? The methods using these arguments are not likely to use the built in python class `filter`. If we use `filter_` then users will need to type that underscore in every invocation using keyword arguments.

**Comment by bdice** [comment]
@joaander I think it's totally fine to use `filter` internally, and in keyword arguments if it makes sense. The problem we want to discourage is users creating variables named `filter` and overwriting the function like often happened with `all` in HOOMD 2. If there is a good way to discourage that common mistake, it would be nice. Otherwise consistency should take precedent, regardless of `filter` or `filter_`. I don't have strong opinions on what the outcome should be, as long as it's consistent and renders correctly in the documentation.

**Comment by joaander** [comment]
It appears that we consistently use `filter` everywhere user-facing except for the one place where GSD documented the arg as `filter_`.
