### ISSUE TITLE
Logger won't take faceted ellipsoid

### ISSUE THREAD

**Issue by Tobias-Dwyer** [glotzerlab/hoomd-blue#824]
## Description

 The logger for hoomd v3 for some reason won't take faceted ellipsoids.

## Script

```python
# Include a minimal script that reproduces the problem
import freud
import gsd.hoomd
import hoomd
import numpy as np
import rowan
import util

unit_cell = freud.data.UnitCell.sc()
box, positions = unit_cell.generate_system(
    num_replicas=5, scale=3 * 2
)
N = len(positions)
orientations = rowan.random.rand(N)
snapshot = gsd.hoomd.Snapshot()
snapshot.particles.N = N
snapshot.particles.position = positions
snapshot.particles.orientation = orientations
snapshot.particles.typeid = [0] * N
snapshot.particles.types = ["A"]
snapshot.particles.type_shapes = [{'type': 'Ellipsoid', 'a': 3, 'b': 1, 'c': 1,'origin': (0,0,0)}]
snapshot.configuration.box = [box.Lx, box.Ly, box.Lz, box.xy, box.xz, box.yz]

with gsd.hoomd.open(name="lattice.gsd", mode="wb") as f:
    f.append(snapshot)

device = hoomd.device.auto_select()
sim = hoomd.Simulation(device=device)
sim.create_state_from_gsd(filename="lattice.gsd")
slab_verts = []
slab_normals = []
slab_offsets = []
mc = hoomd.hpmc.integrate.FacetedEllipsoid(seed=42, d=0.1, a=0.1)
mc.shape["A"] = dict(normals = slab_normals,offsets = slab_offsets,vertices=slab_verts,a= 3, b= 1, c= 1,origin=(0,0,0))
sim.operations += mc
logger = hoomd.logging.Logger()
logger += mc
gsd_writer = hoomd.write.GSD(
    filename="compress.gsd",
    trigger=hoomd.trigger.Periodic(1000),
    overwrite=True,
    dynamic=["property", "attribute"],
    log=logger,
)
sim.operations += gsd_writer
# Let particles move randomly before compressing
if sim.device.communicator.rank == 0:
    print("Initial movements to randomize system...")
sim.run(1000)

```

## Output

Initial movements to randomize system...
Traceback (most recent call last):
  File "minimal_code.py", line 49, in <module>
    sim.run(1000)
  File "/anaconda3/envs/hoomdV3_3.8/lib/python3.8/site-packages/hoomd/simulation.py", line 288, in run
    self._cpp_sys.run(int(steps), write_at_start)
  File "/anaconda3/envs/hoomdV3_3.8/lib/python3.8/site-packages/hoomd/write/gsd.py", line 278, in _write_frame
    _gsd.writeLogQuantities(self.log())
  File "/anaconda3/envs/hoomdV3_3.8/lib/python3.8/site-packages/hoomd/write/gsd.py", line 267, in log
    self._log_convert_value(
  File "/anaconda3/envs/hoomdV3_3.8/lib/python3.8/site-packages/hoomd/write/gsd.py", line 303, in _log_convert_value
    max_len = np.max([len(string) for string in value])
  File "<__array_function__ internals>", line 5, in amax
  File "/anaconda3/envs/hoomdV3_3.8/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 2705, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "/anaconda3/envs/hoomdV3_3.8/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity

## Expected output

Initial movements to randomize system...
## Configuration

Platform:
- Mac
- CPU

Installation method:
- Conda package

Versions:
- Python version: 3.8
- **HOOMD-blue** version: 3.0.0-beta.1

**Comment by b-butler** [comment]
@Tobias-Dwyer this issue you posted isn't related to the logger at all. The problem is that the documentation states that the `origin` key for the faceted ellipsoid shape definition has a default of `(0, 0, 0)`, but in the code it is a required argument.

**Comment by vyasr** [comment]
You need to specify an `origin` for the ellipsoids according to the error. We probably need to modify the code to have a default of `(0, 0, 0)`.

**Comment by vyasr** [comment]
@b-butler jinx

**Comment by Tobias-Dwyer** [comment]
ya'll are cute! and cool, resolved that error and am now having a hopefully more meaningful one.

**Comment by Tobias-Dwyer** [comment]
if you comment out the gsd writer the code runs fine.

**Comment by vyasr** [comment]
OK that error suggest that we're taking the `max` of an empty numpy array. This code in `gsd.py` looks off, why are there two separate `if` statements here? Seems redundant.

```
def _log_convert_value(self, dict_, key, flag, value):
    """Convert loggable types that cannot be directly stored by GSD."""
    if flag == TypeFlags.string:
        value = bytes(value, 'UTF-8')
        value = np.array([value], dtype=np.dtype((bytes, len(value) + 1)))
        value = value.view(dtype=np.int8)
    if flag == TypeFlags.strings:
        value = [bytes(v + '\0', 'UTF-8') for v in value]
        max_len = np.max([len(string) for string in value])
        num_strings = len(value)
        value = np.array(value)
        value = value.view(dtype=np.int8).reshape(num_strings, max_len)
    dict_[key] = value
```

@Tobias-Dwyer what if you comment out the `logger += mc` line? I assume that works? Definitely seems like one of the log quantities is empty.

**Comment by b-butler** [comment]
I fixed the bug, and am working on cleaning it up. @joaander it isn't erroring because we supply an origin in our tests. @vyasr it should be an `elif`.

**Comment by joaander** [comment]
> I fixed the bug, and am working on cleaning it up. @joaander it isn't erroring because we supply an origin in our tests. @vyasr it should be an `elif`.

I asked about tests on #826

**Comment by b-butler** [comment]
Haha @joaander sorry, I just saw the comment on my email and just assumed it was on this issue. My bad.

**Comment by b-butler** [comment]
Also, i noticed through working on this issue that we never dealt with the `GSD` writer being able to log the state of objects with a nested attribute structure like the union shapes which have list of `dict` objects. This will still lead to errors. I don't think I should fix that to fix this issue, but it does raise the question of the generality of the `GSD` writer logging quantities.

**Comment by b-butler** [comment]
@Tobias-Dwyer the branch on #827 fixes your issue.
