### ISSUE TITLE
compiling issue: pybind11::cast

### ISSUE THREAD

**Issue by HeavensInc** [glotzerlab/hoomd-blue#825]
## Description

Hoomd does not compile. It does not find a suitable `pybind11::cast<float>(float&)`
python3: 3.6.9 -- pybind11: 2.6.0

## Script

```bash
git clone --recursive https://github.com/glotzerlab/hoomd-blue hoomd-blue-3beta1
cd hoomd-blue-3beta1
mkdir build
cd build
cmake .. -Dpybind11_DIR=$( python3 -c "import pybind11; print(pybind11.get_cmake_dir())" )
make
```

## Output
```
hoomd-blue-3beta1/hoomd/hpmc/IntegratorHPMCMono.h:2174:50: error: no matching function for call to ‘cast<float>(float&)’
         energy_map.append(pybind11::cast<float>(i));
```

https://github.com/glotzerlab/hoomd-blue/blob/5e466c101ad82fdfe00817a3710954fd902bc184/hoomd/hpmc/IntegratorHPMCMono.h#L2174

## Expected output

None.

## Configuration

Platform:
- Linux
- CPU

Installation method:
- Compiled from source

Versions:
- Python version: 3.6.9
- **HOOMD-blue** version: github / 3.0.0_beta1

Version Details (shortened cmake output):
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Configuring HOOMD v3.0.0-beta.1-30-g5e466c101
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.9", minimum required is "3") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so
-- Performing Test HAS_FLTO - Success
-- Found pybind11: [...] /.local/lib/python3.6/site-packages/pybind11/include (found version "2.6.0" )
-- Found eigen: /usr/lib/cmake/eigen3 /usr/include/eigen3 (version 3.3.4)
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  

## Developer

Expected code:
An explicit cast to a python object `energy_map.append(pybind11::cast(i));` or implicit cast `energy_map.append(i);` to convert a float to a python object.

**Comment by joaander** [comment]
0e5515e fixes this and will be merged in #822.
