### ISSUE TITLE
GSD logging nested object states

### ISSUE THREAD

**Issue by b-butler** [glotzerlab/hoomd-blue#828]
## Description
The `GSD` writer was designed to be able to log objects' state loggable. However, in the of specific nested structures like `list[dict[...]]` this not only will not work, but will cause errors since the type of the quantity will be `'sequence'` see the definition of loggable types in `hoomd.logging.TypeFlags`.

## Fix
Any fix will be involved likely. Given the flexibility of HOOMD's object data model, for GSD to truly be robust to any object's state will be difficult using the current approach of reducing to NumPy arrays. That being said we could use an approach that takes sequences and converts them into dictionaries of the kind `{0: first_item, 1: second_item, ...}`, and detect this in the `from_state` method and other readers. To be honest, I recommended this before, but this seems inelegant and confusing. The other approach that i can immediately think of is storing these as serialized blobs either using something like JSON or pickles. This makes accessing the state from the `GSD` more difficult, but I think is more general and less error prone. I would recommend using the pickle standard as JSON also has limitations that I would worry about running up against eventually.

We could also create a new `TypeFlag` that represents arbitrary binary blobs for users to take advantage of this. It could either be specific to pickles or the deserializer could be unspecified.

The biggest con of using serialization is the access of state attributes directly from the GSD. We support custom logged quantities though, and assuming that only a few of these are actually desired to be directly queried we could just have users do something like
````python
logger[('state', 'attr')] = (obj, attr, 'flag')
````
We could also ease the burden by automatically deserializing in the gsd package.

**Comment by b-butler** [comment]
This will be fixed by making `Operations` objects picklable and removing state from both GSD and the Python API, as making operations picklable accomplishes the same purpose.

**Comment by joaander** [comment]
With the changes coming in #944 completely remove the state from the loggable properties? Or will we just ignore state in GSD files?

I ask because including the state in write_debug_data can be useful.

**Comment by b-butler** [comment]
Yes, state will be an obsolete concept. We can still add state information in those functions via just grabbing the `_param_dict` and `_typeparam_dict`. We could also keep state but just put it in the object category. If we do that though, how far should we go? Should we still allow objects to be initialized from a state dict?
