### ISSUE TITLE
JIT external fields only work in composite fields

### ISSUE THREAD

**Issue by vyasr** [glotzerlab/hoomd-blue#839]
## Description

Currently JIT external fields will be computed but not applied as part of the Metropolis criterion for move acceptance _except_ as part of an external field. The reason is that the constructor for the `jit.external.user` class is missing the following block:

```
if not composite:
    self.mc.set_external(self)
```

The current unit test passes because it only tests a composite field combining a wall and an external field. Adding the above two lines will fix the problem.

## Developer

I will contribute this patch.

**Comment by joaander** [comment]
Fixed in v3.
