### ISSUE TITLE
Saving particle images without saving particle velocity

### ISSUE THREAD

**Issue by shivrajkotkar** [glotzerlab/hoomd-blue#850]
## Description

 HOOMD-Blue 2.9.2 allows particles to save their positions and their images using 
hoomd.dump.gsd(filename,dynamic= ['property','momentum'],group=all, period=1000)
But this will also save particle velocities. If GSD files are huge and if a user does not want to store velocity data then significant space can be saved by dumping only images

## Proposed solution

Creating separate flags in dynamic for images and velocities

## Additional context
 Joshua's comment -  https://groups.google.com/g/hoomd-users/c/B96SgSgK8D4l

**Comment by joaander** [comment]
Thanks for the request. We will implement this in a future HOOMD v3.0 beta release.

**Comment by mphoward** [comment]
I had thought about implementing this before myself, and I thought a nice interface would be optionally allowing request of entries within each category by name:
```py
dynamic=['property','particles/image','particles/typeid']
```
A structure mimicking the schema (struct, bitset, etc.) could be used to track the entries from the schema are dynamic. Specifying the category (old behavior) would set the bits of multiple relevant entries to true.

**Comment by joaander** [comment]
Yes, one could implement such a scheme. I did not in the original dump.gsd implementation because the large number of options in the previous XML dump command resulted in user confusion leading to invalid XML files.
