### ISSUE TITLE
Per-particle lattice energies in Frenkel-Ladd method in hpmc

### ISSUE THREAD

**Issue by PeanutButtermitKase** [glotzerlab/hoomd-blue#853]
Per-particle lattice energies in MC are not currently available in v2 and this might be useful if one wants to work around with simulations in which the free energy is calculated in systems with PBC. The structures at the boundaries might melt and generate problems at performing Frenkel-Ladd. Individual particle lattice energies would help to overcome the imperfections at the surface.

**Comment by joaander** [comment]
Related to #878 . 

To support per-particle quantities, the implementation could expose a method that computes the external potential and returns the per-particle values as a numpy array. That array would then be loggable with the v3 logging framework or otherwise accessible to the user script.
