### ISSUE TITLE
Make Triggers Immutable

### ISSUE THREAD

**Issue by b-butler** [glotzerlab/hoomd-blue#854]
## Description

`Triggers` are small objects like `ParticleFilters` and `Variants`. I think in general it makes sense to make all these immutable as the cost of doing so is small, and `ParticleFilter`s are already effectively immutable through the public interface. This reasoning is purely aesthetic; however, there is a bigger reason this may be a good idea.

Our `And` and `Or` triggers in C++ contain a `std::vector` of shared pointers to `Trigger` objects allowing for n-way and and or logical operators on triggers. However, this leads to the following circumstance, if the triggers composing the `And` or `Or` instance have their only reference in the instance, they downcast to their exposed C++ type (e.g. `hoomd._hoomd.PeriodicTrigger`). This does not lead to any _current_ performance issues or bugs, but does expose the user to a private module class.

If we made `Trigger` subclasses immutable, we could just store a tuple of the composing triggers in Python and not expose the vector at all.

The other viable options including the one given above are 
1. Do nothing, this shouldn't break anything besides pickling*, and that problem may be surmountable.
2. Move the triggers to a public namespace using pybind11. We could then import this module in `hoomd.trigger`. This could still lead to pickling issues.*
3. Create a custom sequence type in Python to manage syncing of the vector of triggers in C++ and Python (similar to the `SyncedList` construct). The downside is that we create a new type and expose it to the user.
4. We make all triggers implemented in HOOMD-blue proper immutable from Python.

\* The pickling issue comes from the downcast. If we have nested `And` or `Or` triggers that are downcast, they will lose the ability to be pickled since their pickling cannot be done in C++ using pybind11 given their complexity (they instead have to use the `__reduce__` magic method).

**Comment by joaander** [comment]
I think it is fine to make them immutable.

**Comment by b-butler** [comment]
Addressed in #885
