### ISSUE TITLE
Port force.constant to the v3 API

### ISSUE THREAD

**Issue by joaander** [glotzerlab/hoomd-blue#866]
## Description

Port force.constant to the v3 API.

## Motivation and context

We should probably retool the interface for force.constant in the process. Also consider removing the unused IMD updater at the same time to remove restrictions on how force.constant needs to behave.

**Comment by joaander** [comment]
The v2 `force.constant` API allowed users to specify a single constant force and torque to an entire group of particles. That convenience API is also rather limiting.

What if instead, we replace it with a `Custom` force that exposes the local force, torque, and energy arrays with zero-copy protocols (like the local snapshots). It would also have an overridable method called when needed to compute the forces on the particle. Users could use this for full-fleged force computations, or with a minimal function body could set constant forces/torques on particles matching the filter (which we could demonstrate in a tutorial).

Any thoughts from the user/developer community? @b-butler ?

**Comment by b-butler** [comment]
This is actually how I imagined that a Python force would work, so I am greatly in favor of this. This would also allow (for free) computation of forces using ML on the GPU or just CuPy, Numba or something else on the GPU.
