### ISSUE TITLE
Refactor HPMC external fields and port to v3 API

### ISSUE THREAD

**Issue by joaander** [glotzerlab/hoomd-blue#878]
## Description

Port needed HPMC external fields to v3. We should also refactor the internals of how these fields are implemented as the code is very complex and hard to follow.

## Motivation and context

This issue is closely related with #551 which deals specifically with the walls and crosses over to MD as well.

As for the non-walls, we need to consider:
* hpmc.field.callback - What problem does this solve? Would it be better to provide a different interface for custom external potentials? Certainly in v3 it should be possible to leverage local snapshots.
* hpmc.field.external_field_composite - We should remove this and consider alternatives (i.e. HPMCIntegrator could store a list of external fields).
* hpmc.field.frenkel_ladd_energy - We should remove this. It is just a shortcut for lattice_field + remove_drift. Users should configure and manage those separately if they wish to.
* hpmc.field.lattice_field - Needed for frenkel-ladd compuations.

**Comment by joaander** [comment]
Note: #937 enables support for C++ run time compiled external potentials. It validates that the external class is specifically of that type. We will need to generalize that when we enable additional external potentials when working on this issue.

**Comment by tcmoore3** [comment]
@b-butler Doing Frenkel–Ladd calculations, which will require the simultaneous use of `lattice_field` and `remove_drift` after this issue is addressed, would be a good item in our how-to section of the docs.

**Comment by tcmoore3** [comment]
> * hpmc.field.callback - What problem does this solve? Would it be better to provide a different interface for custom external potentials? Certainly in v3 it should be possible to leverage local snapshots.

Unless I'm missing something, this problem is solved with the jit-compiled `CPPExternalPotential`s, and we can safely remove `hpmc.field.callback`.
