### ISSUE TITLE
Port getar to the v3 API

### ISSUE THREAD

**Issue by joaander** [glotzerlab/hoomd-blue#882]
## Description

Port getar (dump and init) to the v3 API.

## Motivation and context

Does anyone use getar any longer? Should we remove it instead?

**Comment by mphoward** [comment]
I would vote to remove since it eliminates a dependency, unless someone has a strong need for it.

**Comment by joaander** [comment]
@klarh are you you aware of anyone currently relying on getar files with HOOMD? Would you be interested or know someone would would be interested in porting it to the v3 API?

**Comment by klarh** [comment]
@joaander I still produce them regularly and some members of Julia's group may also use them, although I haven't kept track of who exactly is using them. I'm willing to port the code, assuming that APIs and data structures haven't changed too drastically, though I'm attending a conference this week so I won't be able to start for at least another week. Is there a written summary of hoomd v2->v3 changes that would be relevant to porting somewhere?

**Comment by joaander** [comment]
No worries on the timing, the v3 transition progress will be continuing for some time. The main changes needed are at the interface between the python and C++ code. There are a few changes in the python API relevant for enabling getar. 

1) Initialization of the state is now performed in `Simulation.create_state_from_*` methods - we'll need a `create_state_from_getar`. 

2) Parameter setting/getting is now handled by `_HOOMDBaseObject`. You can see the docs of this and its parent classes or ask @b-butler for details. The short version is that we now match property names for parameters on the Python and C++ levels and defer the initialization of the C++ object until `_attach` is called. Before attaching, `_HOOMDBaseObject` maintains parameters in Python only and after attaching it passes through all parameter get/set to the C++ object. Take a look at the GSD writer code changes between the 2.9 and master branches to see a good example of what is needed.

3) Unit tests are now in pytest. See the various files in hoomd/pytest/ for examples.

**Comment by joaander** [comment]
One other change to consider is that HOOMD v3 now uses cmake to find dependencies (pybind11, eigen, etc..) instead of building embedded copies. We could switch to depending on an external sqlite and maybe even an external libgetar. We could consider making libgetar a soft dependency in this case and disable those features when the library is not available.
