### ISSUE TITLE
Allow snapshots to be duck-typed in state creation

### ISSUE THREAD

**Issue by b-butler** [glotzerlab/hoomd-blue#891]
## Description

Some users have run into errors by creating a `gsd.hoomd.Snapshot` object, and attempting to use it for `hoomd.Simulation.create_state_from_snapshot`. This leads to an error since we currently only allow for a `hoomd.Snapshot` object. I would propose that we duck-type this function to allow for `gsd.hoomd.Snapshot` objects. While this is less performant that properly using a `hoomd.Snapshot` object, given that a user would have already created the `gsd.hoomd.Snapshot` object, this is better than an error. We could raise a `UserWarning` to let the user know that they may have made a sub-optimal decision in doing this (e.g. check if the `num_ranks > 1` for wasted memory usage).

## Proposed solution

I propose adding a `hoomd.Snapshot._from_gsd` class method for `hoomd.Snapshot` to create a `hoomd.Snapshot` from a `gsd.hoomd.Snapshot` object. This approach would also prepare a path in the future for other factory methods to create a `hoomd.Snapshot` object from other similar objects. For instance, given a box array and particle positions a simple snapshot could be created. If we decide to support this in the future, we could utilize the ability of `hoomd.Snapshot` to be initialized from a variety of objects to allow for state creation that way.

To also give useful performance warnings in MPI configurations, we should likely check after grabbing the communicator, if using multiple ranks that the passed snapshot like object is `None` on all but the root rank otherwise throw a warning (this does not need to be the case for `hoomd.Snapshot` objects as they only store data on the root rank). I believe this should be safe with the exception hook HOOMD-blue uses by default.

**Comment by b-butler** [comment]
@jennyfothergill Josh told me you were interested in this. Let me know if you decide to take it on and want help.

**Comment by jennyfothergill** [comment]
@b-butler Yes, I think this would be a good addition--it would make the code more intuitive for new users. I am interested in helping with this.
