### ISSUE TITLE
MPI Deadlock when setting snapshot

### ISSUE THREAD

**Issue by b-butler** [glotzerlab/hoomd-blue#912]
## Description

In #909 MPI tests were failing due to deadlock on commit 3e8a9e5700ef99d665da7929763fb6494d1cb585. @joaander thinks this may be due to running without an integrator. This issue is just to document the behavior for potential later examination.

## Script
Look at `hoomd/pytest/test_dcd.py` in the commit shown above.

## Configuration
This comes from the CI tests.

 **HOOMD-blue** version: 3.0beta.3

**Comment by joaander** [comment]
Not essential for the 3.0.0 release.
