### ISSUE TITLE
Rename MPIConfiguration to MPICommunicator

### ISSUE THREAD

**Issue by jglaser** [glotzerlab/hoomd-blue#915]
## Description

Rename the C++ class `MPIConfiguration` to `MPICommunicator`

## Motivation and context

from #659 : 

MPIConfiguration is just a holder for an MPI communicator (and the world communicator). I believe the name Configuration suggests slightly more than what it is and could be changed to MPICommunicator going forward.

**Comment by joaander** [comment]
It is more than just a communicator. It describes the configuration of the MPI environment for the whole submission, which includes the local and world communicators, convenience methods that get the rank and number of ranks, and partitions on each. It is named in a similar fashion to `ExecutionConfiguration`.
