### ISSUE TITLE
Add option to filter which particles scale with BoxResize

### ISSUE THREAD

**Issue by klywang** [glotzerlab/hoomd-blue#921]
## Description

Currently, particle scaling in `BoxResize` is applied globally based on a True/False argument. In some cases, users may need to add some structure (such as a seed to encourage crystal nucleation) in the box, then change the box size. In these situations, the user will need to filter which particles scale with the box, and which particles do not scale with the box size.

## Proposed solution

Here are potential solutions for the API:
    1. Allow the argument `scale_particles` to accept either a `bool` or `hoomd.filter.ParticleFilter`
    2. Add an additional argument `filter` that can be used in lieu of `scale_particles` (although this seems like it could get messy)
    3. Replace `scale_particles` with a `filter` argument, where the default is `hoomd.filter.Null`. Not sure if it's a good idea to remove an argument though.
    
## Additional context

I imagine there may be some issues with particle overlap, especially if resizing is done too quickly or the system is extremely dense. Should `hoomd` have a way to prevent this (ie. check for overlaps)? Or would this be a warning to mention in the docs?

## Developer

@klywang

**Comment by b-butler** [comment]
My suggestion would be to move `scale_particles` to accept a filter of particles to scale that would default to `hoomd.filter.All()`. We should no longer accept Boolean values in this case.

**Comment by klywang** [comment]
> My suggestion would be to move `scale_particles` to accept a filter of particles to scale that would default to `hoomd.filter.All()`. We should no longer accept Boolean values in this case.
> 
> Edit: The reason to default to `All` would be to have scaling on by default as it already is.

Thanks for the reminder! I forgot the default was "True".
