### ISSUE TITLE
Bug in create_state_from_snapshot

### ISSUE THREAD

**Issue by astatt** [glotzerlab/hoomd-blue#942]
## Description

There is a bug in sim.create_state_from_snapshot(). I might be misunderstanding or using it wrong, if so maybe clarification in the documentation could be helpful. 

## Script

```python
import hoomd
import hoomd.md
import gsd.hoomd

gpu = hoomd.device.GPU(notice_level=2)

sim = hoomd.Simulation(device=gpu)

snapshot = gsd.hoomd.Snapshot()
snapshot.particles.N = 1
snapshot.particles.position = [(0,0,0)]
snapshot.configuration.box = [5, 5, 5, 0, 0, 0]
snapshot.particles.types = ['A']

sim.create_state_from_snapshot(snapshot)

#with gsd.hoomd.open(name='test.gsd', mode='wb') as f:
#    f.append(snapshot)
#sim.create_state_from_gsd(filename='test.gsd')
```

## Output

```
Traceback (most recent call last):
  File "snapshot_min.hoomd", line 18, in <module>
    sim.create_state_from_snapshot(snapshot)
  File "/data/programs/hoomd-3.0.0/hoomd/simulation.py", line 144, in create_state_from_snapshot
    snapshot = Snapshot._from_gsd_snapshot(
AttributeError: type object 'Snapshot' has no attribute '_from_gsd_snapshot'
```

## Expected output

Working initialization. Same script is working if gsd is saved to disk first and then read in with sim.create_state_from_gsd()

## Configuration

Platform:
- Linux
- GPU

Installation method:
- Compiled from source (CUDA 10.1, gcc/g++ 8, no mpi)

Versions:
- Python version: 3.7.6 (anaconda)
- **HOOMD-blue** version: v3-beta.4

**Comment by joaander** [comment]
Fixed in #935
