### ISSUE TITLE
Abstract out GPUFactory from HPMC

### ISSUE THREAD

**Issue by b-butler** [glotzerlab/hoomd-blue#967]
## Description
Move generic `GPUFactory` code to an application agnostic state. Code can be found in `hoomd/jit/GPUEvalFactory.*`. Currently many functions are specific to functions in HPMC such as `setRCutUnion` and to application such as `setAlphaPtr`. These should be found in a application specific task if necessary.

## Motivation and context
Abstracting out the core JIT logic to simplify the extension of JIT to other tasks.

**Comment by jglaser** [comment]
I am working on related stuff, will publish as PR soon.

**Comment by b-butler** [comment]
@jglaser awesome, will this be a full JIT PR, because at our weekly hoomd developer meetings we have been discussing the future of JIT in hoomd, and it would be good to know what you are working on.

**Comment by joaander** [comment]
We will release 3.0.0 with the JIT as is and labelled experimental. We will delay this refactoring to a future 3.x release.
