### ISSUE TITLE
Separate PatchEnergyJit and PatchEnergyGPUJIT

### ISSUE THREAD

**Issue by b-butler** [glotzerlab/hoomd-blue#968]
## Description
Currently `PatchEnergyJIT` is the parent of  `PatchEnergyJITGPU`, but since `PatchEnergyJIT` maintains CPU compiled code among other things leads this to not be a good paradigm. A `PatchEnergyJIT` class (distinct from the one above) should be created with the things in common, and `PatchEnergyJITCPU` and `PatchEnergyJITGPU` both should inherit from the new `PatchEnergyJIT` class.

**Comment by joaander** [comment]
We will release 3.0.0 with the JIT as is and labelled experimental. We will delay this refactoring to a future 3.x release.

I do have a question about this though. Currently, PatchEnergyGPUJIT defers some of its computations, such as the total energy to the CPU via base class methods. Do you propose implementing all those methods on the GPU? This pattern is used throughout HOOMD where the base class implements the method on the CPU and the *GPU derived class overrides just a few methods to put the slow parts of the computation on the GPU.

**Comment by b-butler** [comment]
Hmm, I didn't notice that we used compiled CPU code on the GPU. In that case, it is fine as is.
