### ISSUE TITLE
Stop vendoring our own jitify.hpp

### ISSUE THREAD

**Issue by b-butler** [glotzerlab/hoomd-blue#971]
## Description
We currently vendor https://github.com/NVIDIA/jitify in `hoomd/jit`. Looking at the diffs, it seems we could likely just have `jitify` be a dependency for GPU JIT features in hoomd-blue and stop vendoring the header ourselves.

## Motivation and context
This would outsource any maintenance of jitify (for now at least).

**Comment by vyasr** [comment]
If you're doing this, be aware of `jitify2.hpp`, which is now available with a slightly modified API and I believe has CUDA 11.2 support.

**Comment by joaander** [comment]
We will release 3.0.0 with the JIT as is and labelled experimental. We will delay this refactoring to a future 3.x release.
