### ISSUE TITLE
Add ARCHITECTURE.md file

### ISSUE THREAD

**Issue by vyasr** [glotzerlab/hoomd-blue#979]
## Description

Add an [ARCHITECTURE.md](https://matklad.github.io//2021/02/06/ARCHITECTURE.md.html) file describing the internals of HOOMD-blue. 

## Motivation and context

This file would be very useful for developers to explain how different parts of the code are structured. Some topics that should be included (others should feel free to modify and add to this preliminary list):
- [x] Templating of PotentialPair on Evaluators, and the expected Evaluator API
- [x] Templating of Rattle integrators on Manifolds, and the expected Manifold API
- [x] How external fields work (ideally via templating in the future)
- [x] The use of driver functions to launch the kernels, how this logic is separated into files, and why
- [x] The core Python classes in the v3 infrastructure. In particular, definitions of
  - [x] Operation
  - [x] ParameterDict
  - [x] TypeParameterDict
- [x] How we link Python and C++. Focus should be on what attributes are typically defined for Python objects (e.g. param_dict) to set up the synchronization.

**Comment by b-butler** [comment]
@vyasr it as if you read our mind. Josh and I have been talking about this, and are planning on adding architecture files for all major subpackages as well as the package as a whole.

**Comment by joaander** [comment]
We should also cover the core C++ classes and how they combine together to implement an MD simulation, with some mention of how we use signals.

**Comment by joaander** [comment]
I did write docs like these before implementing HOOMD: https://github.com/glotzerlab/hoomd-blue/blob/master/doc/dev/DeveloperInfo.doc - however these docs have not been updated and are very out of date.

**Comment by joaander** [comment]
We should also document the pickling protocol for the Python objects and specifically mention what steps are needed for developers to maintain backward compatibility with existing pickle files in future releases.

**Comment by joaander** [comment]
Note that the `ARCHITECTURE.md` document is not an API specification - that should be documented in class comments. `ARCHITECTURE.md` should only generally describe the overall architecture of how the classes fit together.

**Comment by vyasr** [comment]
I agree, but it probably does need to include some information on the places in HOOMD where we intentionally avoid inheritance in favor of some abstract API and why. It would also be nice to codify the APIs for those things somewhere, but I agree that doesn't belong in ARCHITECTURE.md.

**Comment by vyasr** [comment]
@b-butler @joaander it looks like you two have made significant progress on this file since the last time I checked. Is there more that you'd like to add (and should the checklist above be updated), or can we close this issue?

**Comment by joaander** [comment]
I marked completed items on the checklist. We are still missing details on the C++ and build infrastructure.
